from Emperor.config import ModelConfig
from Emperor.base.utils import ConfigUtils
from Emperor.base.layer import LayerStackConfig
from Emperor.sampler.utils.presets import SamplerPresets
from Emperor.linears.utils.presets import LinearPresets
from Emperor.linears.options import LinearLayerStackOptions
from Emperor.experts.utils.layers import MixtureOfExpertsConfig
from Emperor.base.enums import ActivationOptions, LayerNormPositionOptions
from Emperor.experts.utils.enums import ExpertWeightingPositionOptions, LayerRoleOptions
from Emperor.behaviours.utils.enums import (
    DynamicBiasOptions,
    DynamicDepthOptions,
    DynamicDiagonalOptions,
    LinearMemoryOptions,
    LinearMemoryPositionOptions,
    LinearMemorySizeOptions,
)


class MixtureOfExpertsPresets:
    @staticmethod
    def experts_config(
        input_dim=8,
        hidden_dim=12,
        output_dim=6,
        layer_stack_option=LinearLayerStackOptions.ADAPTIVE,
        top_k=3,
        num_experts=6,
        compute_expert_mixture_flag=True,
        weighted_parameters_flag=True,
        weighting_position_option=ExpertWeightingPositionOptions.BEFORE_EXPERTS,
        init_sampler_model_flag=True,
        layer_role_option: LayerRoleOptions = LayerRoleOptions.GENERAL,
        bias_flag: bool = True,
        generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        noisy_topk_flag: bool = False,
        threshold=0.0,
        filter_above_threshold=False,
        num_topk_samples=0,
        normalize_probabilities_flag=False,
        switch_loss_weight=0.0,
        zero_centred_loss_weight=0.0,
        mutual_information_loss_weight=0.0,
        coefficient_of_variation_loss_weight=0.0,
        stack_num_layers: int = 2,
        stack_hidden_dim: int = 0,
        stack_activation: ActivationOptions = ActivationOptions.RELU,
        stack_residual_flag: bool = False,
        stack_dropout_probability: float = 0.0,
    ):
        return MixtureOfExpertsConfig(
            layer_stack_option=layer_stack_option,
            top_k=top_k,
            num_experts=num_experts,
            compute_expert_mixture_flag=compute_expert_mixture_flag,
            weighted_parameters_flag=weighted_parameters_flag,
            weighting_position_option=weighting_position_option,
            init_sampler_model_flag=init_sampler_model_flag,
            layer_role_option=layer_role_option,
            override_config=LayerStackConfig(
                input_dim=input_dim,
                hidden_dim=hidden_dim,
                output_dim=num_experts,
                num_layers=stack_num_layers,
                activation=stack_activation,
                layer_norm_position=LayerNormPositionOptions.NONE,
                residual_flag=stack_residual_flag,
                adaptive_computation_flag=False,
                dropout_probability=stack_dropout_probability,
                override_config=LinearPresets.adaptive_linear_layer_config(
                    input_dim=input_dim,
                    output_dim=output_dim,
                    bias_flag=bias_flag,
                    generator_depth=generator_depth,
                    diagonal_option=diagonal_option,
                    bias_option=bias_option,
                    memory_option=memory_option,
                    memory_size_option=memory_size_option,
                    memory_position_option=memory_position_option,
                    stack_num_layers=stack_num_layers,
                    stack_hidden_dim=stack_hidden_dim,
                    stack_activation=stack_activation,
                    stack_residual_flag=stack_residual_flag,
                    stack_dropout_probability=stack_dropout_probability,
                ),
            ),
            router_model_config=SamplerPresets.router_config(
                input_dim=input_dim,
                hidden_dim=hidden_dim,
                num_experts=num_experts,
                bias_flag=bias_flag,
                noisy_topk_flag=noisy_topk_flag,
                residual_flag=stack_residual_flag,
                dropout_probability=stack_dropout_probability,
                stack_num_layers=stack_num_layers,
                activation=stack_activation,
                layer_stack_option=layer_stack_option,
                bias_option=bias_option,
                memory_option=memory_option,
                generator_depth=generator_depth,
                diagonal_option=diagonal_option,
                memory_size_option=memory_size_option,
                memory_position_option=memory_position_option,
            ),
            sampler_model_config=SamplerPresets.sampler_config(
                num_experts=num_experts,
                top_k=top_k,
                threshold=threshold,
                filter_above_threshold=filter_above_threshold,
                num_topk_samples=num_topk_samples,
                normalize_probabilities_flag=normalize_probabilities_flag,
                noisy_topk_flag=noisy_topk_flag,
                coefficient_of_variation_loss_weight=coefficient_of_variation_loss_weight,
                switch_loss_weight=switch_loss_weight,
                zero_centred_loss_weight=zero_centred_loss_weight,
                mutual_information_loss_weight=mutual_information_loss_weight,
            ),
        )

    @staticmethod
    def experts_stack_preset(
        batch_size=8,
        input_dim=8,
        hidden_dim=12,
        output_dim=6,
        layer_stack_option=LinearLayerStackOptions.ADAPTIVE,
        router_layer_stack_option=LinearLayerStackOptions.BASE,
        top_k=3,
        num_experts=6,
        compute_expert_mixture_flag=True,
        weighted_parameters_flag=True,
        weighting_position_option=ExpertWeightingPositionOptions.BEFORE_EXPERTS,
        init_sampler_model_flag=True,
        layer_role_option: LayerRoleOptions = LayerRoleOptions.GENERAL,
        bias_flag: bool = True,
        generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        noisy_topk_flag: bool = False,
        threshold=0.0,
        filter_above_threshold=False,
        num_topk_samples=0,
        normalize_probabilities_flag=False,
        switch_loss_weight=0.0,
        zero_centred_loss_weight=0.0,
        mutual_information_loss_weight=0.0,
        coefficient_of_variation_loss_weight=0.0,
        stack_num_layers: int = 2,
        stack_hidden_dim: int = 0,
        stack_activation: ActivationOptions = ActivationOptions.RELU,
        stack_residual_flag: bool = False,
        stack_dropout_probability: float = 0.0,
    ):
        arguments = ConfigUtils.get_method_arguments()

        return ModelConfig(
            batch_size=batch_size,
            input_dim=input_dim,
            output_dim=output_dim,
            layer_stack_config=LayerStackConfig(
                model_type=LinearLayerOptions.BASE,
                input_dim=input_dim,
                hidden_dim=stack_hidden_dim,
                output_dim=output_dim,
                num_layers=stack_num_layers,
                activation=stack_activation,
                layer_norm_position=LayerNormPositionOptions.NONE,
                residual_flag=stack_residual_flag,
                adaptive_computation_flag=False,
                dropout_probability=stack_dropout_probability,
                override_config=MixtureOfExpertsPresets.experts_config(
                    input_dim=input_dim,
                    hidden_dim=hidden_dim,
                    output_dim=output_dim,
                    layer_stack_option=layer_stack_option,
                    top_k=top_k,
                    num_experts=num_experts,
                    compute_expert_mixture_flag=compute_expert_mixture_flag,
                    weighted_parameters_flag=weighted_parameters_flag,
                    weighting_position_option=weighting_position_option,
                    init_sampler_model_flag=init_sampler_model_flag,
                    layer_role_option=layer_role_option,
                    bias_flag=bias_flag,
                    generator_depth=generator_depth,
                    diagonal_option=diagonal_option,
                    bias_option=bias_option,
                    memory_option=memory_option,
                    memory_size_option=memory_size_option,
                    memory_position_option=memory_position_option,
                    noisy_topk_flag=noisy_topk_flag,
                    threshold=threshold,
                    filter_above_threshold=filter_above_threshold,
                    num_topk_samples=num_topk_samples,
                    normalize_probabilities_flag=normalize_probabilities_flag,
                    switch_loss_weight=switch_loss_weight,
                    zero_centred_loss_weight=zero_centred_loss_weight,
                    mutual_information_loss_weight=mutual_information_loss_weight,
                    coefficient_of_variation_loss_weight=coefficient_of_variation_loss_weight,
                    stack_num_layers=stack_num_layers,
                    stack_hidden_dim=stack_hidden_dim,
                    stack_activation=stack_activation,
                    stack_residual_flag=stack_residual_flag,
                    stack_dropout_probability=stack_dropout_probability,
                ),
            ),
        )

    @staticmethod
    def layer_base_linear_layer_preset(
        batch_size=8,
        input_dim=8,
        hidden_dim=12,
        output_dim=6,
        layer_stack_option=LinearLayerStackOptions.ADAPTIVE,
        router_layer_stack_option=LinearLayerStackOptions.BASE,
        top_k=3,
        num_experts=6,
        compute_expert_mixture_flag=True,
        weighted_parameters_flag=True,
        weighting_position_option=ExpertWeightingPositionOptions.BEFORE_EXPERTS,
        init_sampler_model_flag=True,
        layer_role_option: LayerRoleOptions = LayerRoleOptions.GENERAL,
        bias_flag: bool = True,
        generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        activation: ActivationOptions = ActivationOptions.RELU,
        residual_flag: bool = False,
        dropout_probability: float = 0.0,
        stack_num_layers: int = 2,
        noisy_topk_flag: bool = False,
        threshold=0.0,
        filter_above_threshold=False,
        num_topk_samples=0,
        normalize_probabilities_flag=False,
        switch_loss_weight=0.0,
        zero_centred_loss_weight=0.0,
        mutual_information_loss_weight=0.0,
        coefficient_of_variation_loss_weight=0.0,
    ):
        arguments = ConfigUtils.get_method_arguments()

        return ModelConfig(
            batch_size=batch_size,
            input_dim=input_dim,
            output_dim=output_dim,
            mixture_of_experts_config=MixtureOfExpertsPresets.experts_config(
                **arguments
            ),
        )
