from Emperor.config import ModelConfig
from Emperor.base.layer import LayerStackConfig
from Emperor.sampler.utils.presets import SamplerPresets
from Emperor.linears.utils.presets import LinearPresets
from Emperor.linears.options import LinearLayerStackOptions
from Emperor.experts.utils.layers import MixtureOfExpertsConfig
from Emperor.base.enums import ActivationOptions, LayerNormPositionOptions
from Emperor.experts.utils.enums import ExpertWeightingPositionOptions, LayerRoleOptions
from Emperor.behaviours.utils.enums import (
    DynamicBiasOptions,
    DynamicDepthOptions,
    DynamicDiagonalOptions,
    LinearMemoryOptions,
    LinearMemoryPositionOptions,
    LinearMemorySizeOptions,
)


class MixtureOfExpertsPresets:
    @staticmethod
    def experts_preset(
        return_model_config_flag: bool = False,
        batch_size=2,
        input_dim=8,
        output_dim=6,
        router_model_bias_flag: bool = False,
        router_model_noisy_topk_flag: bool = False,
        router_model_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        router_model_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        router_model_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        router_model_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        router_model_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        router_model_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        router_model_layer_stack_option=LinearLayerStackOptions.BASE,
        sampler_threshold=0.0,
        sampler_filter_above_threshold=False,
        sampler_num_topk_samples=0,
        sampler_normalize_probabilities_flag=False,
        sampler_switch_loss_weight=0.0,
        sampler_zero_centred_loss_weight=0.0,
        sampler_mutual_information_loss_weight=0.0,
        sampler_coefficient_of_variation_loss_weight=0.0,
        experts_top_k=3,
        experts_num_experts=6,
        experts_layer_stack_option=LinearLayerStackOptions.BASE,
        experts_compute_expert_mixture_flag=False,
        experts_weighting_position_option=ExpertWeightingPositionOptions.BEFORE_EXPERTS,
        experts_init_sampler_model_flag=False,
        experts_weighted_parameters_flag=False,
        experts_layer_role_option=LayerRoleOptions.GENERAL,
        experts_model_bias_flag: bool = False,
        experts_model_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        experts_model_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        experts_model_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        experts_model_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        experts_model_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        experts_model_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        stack_num_layers: int = 2,
        stack_hidden_dim: int = 0,
        stack_activation: ActivationOptions = ActivationOptions.RELU,
        stack_residual_flag: bool = False,
        stack_dropout_probability: float = 0.0,
    ) -> "MixtureOfExpertsConfig | ModelConfig":
        _hidden_dim = max(input_dim, output_dim)
        stack_hidden_dim = stack_hidden_dim if stack_hidden_dim > 0 else _hidden_dim

        expert_model_config = LinearPresets.base_linear_layer_stack_preset(
            input_dim=input_dim,
            output_dim=output_dim,
            bias_flag=experts_model_bias_flag,
            data_monitor=None,
            parameter_monitor=None,
            stack_num_layers=stack_num_layers,
            stack_hidden_dim=stack_hidden_dim,
            stack_activation=stack_activation,
            stack_residual_flag=stack_residual_flag,
            stack_dropout_probability=stack_dropout_probability,
        )
        if experts_layer_stack_option == LinearLayerStackOptions.ADAPTIVE:
            expert_model_config = LinearPresets.adaptive_linear_layer_stack_preset(
                input_dim=input_dim,
                output_dim=output_dim,
                bias_flag=experts_model_bias_flag,
                generator_depth=experts_model_generator_depth,
                diagonal_option=experts_model_diagonal_option,
                bias_option=experts_model_bias_option,
                memory_option=experts_model_memory_option,
                memory_size_option=experts_model_memory_size_option,
                memory_position_option=experts_model_memory_position_option,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=stack_hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            )

        config = MixtureOfExpertsConfig(
            top_k=experts_top_k,
            num_experts=experts_num_experts,
            layer_stack_option=experts_layer_stack_option,
            compute_expert_mixture_flag=experts_compute_expert_mixture_flag,
            weighted_parameters_flag=experts_weighted_parameters_flag,
            weighting_position_option=experts_weighting_position_option,
            init_sampler_model_flag=experts_init_sampler_model_flag,
            layer_role_option=experts_layer_role_option,
            override_config=expert_model_config,
            router_model_config=SamplerPresets.router_preset(
                input_dim=input_dim,
                num_experts=experts_num_experts,
                bias_flag=router_model_bias_flag,
                noisy_topk_flag=router_model_noisy_topk_flag,
                layer_stack_option=router_model_layer_stack_option,
                bias_option=router_model_bias_option,
                memory_option=router_model_memory_option,
                generator_depth=router_model_generator_depth,
                diagonal_option=router_model_diagonal_option,
                memory_size_option=router_model_memory_size_option,
                memory_position_option=router_model_memory_position_option,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=stack_hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            ),
            sampler_model_config=SamplerPresets.sampler_preset(
                num_experts=experts_num_experts,
                top_k=experts_top_k,
                threshold=sampler_threshold,
                filter_above_threshold=sampler_filter_above_threshold,
                num_topk_samples=sampler_num_topk_samples,
                normalize_probabilities_flag=sampler_normalize_probabilities_flag,
                noisy_topk_flag=router_model_noisy_topk_flag,
                coefficient_of_variation_loss_weight=sampler_coefficient_of_variation_loss_weight,
                switch_loss_weight=sampler_switch_loss_weight,
                zero_centred_loss_weight=sampler_zero_centred_loss_weight,
                mutual_information_loss_weight=sampler_mutual_information_loss_weight,
            ),
        )

        if not return_model_config_flag:
            return config
        return ModelConfig(
            batch_size=batch_size,
            input_dim=input_dim,
            output_dim=output_dim,
            mixture_of_experts_config=config,
        )

    @staticmethod
    def experts_stack_preset(
        return_model_config_flag: bool = False,
        batch_size=8,
        input_dim=8,
        output_dim=6,
        router_model_bias_flag: bool = False,
        router_model_noisy_topk_flag: bool = False,
        router_model_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        router_model_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        router_model_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        router_model_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        router_model_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        router_model_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        router_model_layer_stack_option=LinearLayerStackOptions.BASE,
        sampler_threshold=0.0,
        sampler_filter_above_threshold=False,
        sampler_num_topk_samples=0,
        sampler_normalize_probabilities_flag=False,
        sampler_switch_loss_weight=0.0,
        sampler_zero_centred_loss_weight=0.0,
        sampler_mutual_information_loss_weight=0.0,
        sampler_coefficient_of_variation_loss_weight=0.0,
        experts_top_k=3,
        experts_num_experts=6,
        experts_layer_stack_option=LinearLayerStackOptions.BASE,
        experts_compute_expert_mixture_flag=False,
        experts_weighting_position_option=ExpertWeightingPositionOptions.BEFORE_EXPERTS,
        experts_init_sampler_model_flag=False,
        experts_weighted_parameters_flag=False,
        experts_layer_role_option=LayerRoleOptions.GENERAL,
        experts_model_bias_flag: bool = False,
        experts_model_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        experts_model_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        experts_model_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        experts_model_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        experts_model_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        experts_model_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        experts_stack_num_layers: int = 2,
        experts_stack_activation: ActivationOptions = ActivationOptions.RELU,
        experts_stack_residual_flag: bool = False,
        experts_stack_dropout_probability: float = 0.0,
        stack_num_layers: int = 2,
        stack_hidden_dim: int = 0,
        stack_activation: ActivationOptions = ActivationOptions.RELU,
        stack_residual_flag: bool = False,
        stack_dropout_probability: float = 0.0,
    ) -> "LayerStackConfig | ModelConfig":
        _hidden_dim = max(input_dim, output_dim)
        stack_hidden_dim = stack_hidden_dim if stack_hidden_dim > 0 else _hidden_dim

        config = LayerStackConfig(
            input_dim=input_dim,
            hidden_dim=stack_hidden_dim,
            output_dim=output_dim,
            num_layers=experts_stack_num_layers,
            activation=experts_stack_activation,
            layer_norm_position=LayerNormPositionOptions.NONE,
            residual_flag=experts_stack_residual_flag,
            adaptive_computation_flag=False,
            dropout_probability=experts_stack_dropout_probability,
            override_config=MixtureOfExpertsPresets.experts_preset(
                input_dim=input_dim,
                output_dim=output_dim,
                router_model_bias_flag=router_model_bias_flag,
                router_model_noisy_topk_flag=router_model_noisy_topk_flag,
                router_model_generator_depth=router_model_generator_depth,
                router_model_diagonal_option=router_model_diagonal_option,
                router_model_bias_option=router_model_bias_option,
                router_model_memory_option=router_model_memory_option,
                router_model_memory_size_option=router_model_memory_size_option,
                router_model_memory_position_option=router_model_memory_position_option,
                router_model_layer_stack_option=router_model_layer_stack_option,
                sampler_threshold=sampler_threshold,
                sampler_filter_above_threshold=sampler_filter_above_threshold,
                sampler_num_topk_samples=sampler_num_topk_samples,
                sampler_normalize_probabilities_flag=sampler_normalize_probabilities_flag,
                sampler_switch_loss_weight=sampler_switch_loss_weight,
                sampler_zero_centred_loss_weight=sampler_zero_centred_loss_weight,
                sampler_mutual_information_loss_weight=sampler_mutual_information_loss_weight,
                sampler_coefficient_of_variation_loss_weight=sampler_coefficient_of_variation_loss_weight,
                experts_top_k=experts_top_k,
                experts_num_experts=experts_num_experts,
                experts_layer_stack_option=experts_layer_stack_option,
                experts_compute_expert_mixture_flag=experts_compute_expert_mixture_flag,
                experts_weighting_position_option=experts_weighting_position_option,
                experts_init_sampler_model_flag=experts_init_sampler_model_flag,
                experts_weighted_parameters_flag=experts_weighted_parameters_flag,
                experts_layer_role_option=experts_layer_role_option,
                experts_model_bias_flag=experts_model_bias_flag,
                experts_model_generator_depth=experts_model_generator_depth,
                experts_model_diagonal_option=experts_model_diagonal_option,
                experts_model_bias_option=experts_model_bias_option,
                experts_model_memory_option=experts_model_memory_option,
                experts_model_memory_size_option=experts_model_memory_size_option,
                experts_model_memory_position_option=experts_model_memory_position_option,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=stack_hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            ),
        )

        if not return_model_config_flag:
            return config
        return ModelConfig(
            batch_size=batch_size,
            input_dim=input_dim,
            output_dim=output_dim,
            layer_stack_config=config,
        )
