"""Generated package-owned Runtime Defaults presentation metadata."""

from model_runtime.packages.configuration_metadata import (
    RuntimeDefaultsSection,
)

# Generated by tools/generate_model_package_inspection_metadata.py.
# Do not edit by hand; run the generator after intentional metadata changes.
# fmt: off
CONFIGURATION_METADATA_SECTIONS: tuple[RuntimeDefaultsSection, ...] = (
    RuntimeDefaultsSection(('Trainer',), (
        ('TRAINER_ACCELERATOR', 16, (16,)),
        ('TRAINER_DEVICES', 17, (17,)),
        ('TRAINER_GRADIENT_CLIP_VAL', 18, (18,)),
        ('TRAINER_GRADIENT_CLIP_ALGORITHM', 19, (19,)),
        ('TRAINER_ACCUMULATE_GRAD_BATCHES', 20, (20,)),
        ('TRAINER_PRECISION', 21, (21,)),
        ('TRAINER_DETERMINISTIC', 22, (22,)),
        ('TRAINER_BENCHMARK', 23, (23,)),
        ('TRAINER_MAX_STEPS', 24, (24,)),
        ('TRAINER_MAX_TIME', 25, (25,)),
        ('TRAINER_VAL_CHECK_INTERVAL', 26, (26,)),
        ('TRAINER_LIMIT_TRAIN_BATCHES', 27, (27,)),
        ('TRAINER_LIMIT_VAL_BATCHES', 28, (28,)),
        ('TRAINER_OVERFIT_BATCHES', 29, (29,)),
        ('TRAINER_NUM_SANITY_VAL_STEPS', 30, (30,)),
        ('TRAINER_LOG_EVERY_N_STEPS', 31, (31,)),
        ('TRAINER_ENABLE_PROGRESS_BAR', 32, (32,)),
        ('TRAINER_ENABLE_CHECKPOINTING', 33, (33,)),
        ('TRAINER_ENABLE_MODEL_SUMMARY', 34, (34,)),
        ('TRAINER_PROFILER', 35, (35,)),
        ('MONITOR_LOG_EVERY_N_STEPS', 36, (36,)),
    )),
    RuntimeDefaultsSection(('Run',), (
        ('DATA_NUM_WORKERS', 39, (39,)),
        ('RUN_TEST_AFTER_FIT', 40, (40,)),
        ('SEED', 41, (41,)),
    )),
    RuntimeDefaultsSection(('Callback',), (
        ('CALLBACK_EARLY_STOPPING_PATIENCE', 44, (44,)),
        ('CALLBACK_EARLY_STOPPING_METRIC', 45, (45,)),
        ('CALLBACK_EARLY_STOPPING_MIN_DELTA', 46, (46,)),
        ('CALLBACK_EARLY_STOPPING_STRICT', 47, (47,)),
        ('CALLBACK_EARLY_STOPPING_CHECK_FINITE', 48, (48,)),
        ('CALLBACK_CHECKPOINT_FLAG', 49, (49,)),
    )),
    RuntimeDefaultsSection(('Global',), (
        ('BATCH_SIZE', 52, (52,)),
        ('LEARNING_RATE', 53, (53,)),
        ('NUM_EPOCHS', 54, (54,)),
    )),
    RuntimeDefaultsSection(('Model',), (
        ('INPUT_DIM', 57, (57,)),
        ('HIDDEN_DIM', 58, (58,)),
        ('RUNTIME_VALUE_CONSTRAINTS', 59, (59,)),
        ('OUTPUT_DIM', 60, (60,)),
    )),
    RuntimeDefaultsSection(('Layer Stack Options',), (
        ('STACK_NUM_LAYERS', 64, (64,)),
        ('STACK_ACTIVATION', 65, (65,)),
        ('STACK_DROPOUT_PROBABILITY', 66, (66,)),
    )),
    RuntimeDefaultsSection(('Residual Options',), (
        ('STACK_RESIDUAL_CONNECTION_OPTION', 72, (72,)),
        ('STACK_RESIDUAL_MODEL_FLAG', 73, (73,)),
    )),
    RuntimeDefaultsSection(('Residual Options', 'Residual Stack Options'), (
        ('RESIDUAL_STACK_INDEPENDENT_FLAG', 76, (76,)),
        ('RESIDUAL_STACK_HIDDEN_DIM', 77, (77,)),
        ('RESIDUAL_STACK_LAYER_NORM_POSITION', 78, (78,)),
        ('RESIDUAL_STACK_NORMALIZATION', 79, (79,)),
        ('RESIDUAL_STACK_NUM_LAYERS', 80, (80,)),
        ('RESIDUAL_STACK_ACTIVATION', 81, (81,)),
        ('RESIDUAL_STACK_RESIDUAL_CONNECTION_OPTION', 82, (82,)),
        ('RESIDUAL_STACK_RESIDUAL_MODEL_FLAG', 83, (83,)),
        ('RESIDUAL_STACK_DROPOUT_PROBABILITY', 84, (84,)),
        ('RESIDUAL_STACK_LAST_LAYER_BIAS_OPTION', 85, (85,)),
        ('RESIDUAL_STACK_APPLY_OUTPUT_POSTPROCESSING_FLAG', 86, (86,)),
        ('RESIDUAL_STACK_BIAS_FLAG', 87, (87,)),
    )),
    RuntimeDefaultsSection(('Parametric Vector Mixture Options',), (
        ('ADAPTIVE_MIXTURE_TOP_K', 90, (90,)),
        ('ADAPTIVE_MIXTURE_NUM_EXPERTS', 91, (91,)),
        ('ADAPTIVE_MIXTURE_WEIGHTED_PARAMETERS_FLAG', 92, (92,)),
        ('ADAPTIVE_MIXTURE_CLIP_PARAMETER_OPTION', 93, (93,)),
        ('ADAPTIVE_MIXTURE_CLIP_RANGE', 96, (96,)),
    )),
    RuntimeDefaultsSection(('Sampler Model Options',), (
        ('SAMPLER_THRESHOLD', 99, (99,)),
        ('SAMPLER_FILTER_ABOVE_THRESHOLD', 100, (100,)),
        ('SAMPLER_NUM_TOPK_SAMPLES', 101, (101,)),
        ('SAMPLER_NORMALIZE_PROBABILITIES_FLAG', 102, (102,)),
        ('SAMPLER_NOISY_TOPK_FLAG', 103, (103,)),
        ('SAMPLER_COEFFICIENT_OF_VARIATION_LOSS_WEIGHT', 104, (104,)),
        ('SAMPLER_SWITCH_LOSS_WEIGHT', 105, (105,)),
        ('SAMPLER_ZERO_CENTRED_LOSS_WEIGHT', 106, (106,)),
        ('SAMPLER_MUTUAL_INFORMATION_LOSS_WEIGHT', 107, (107,)),
    )),
)

SEARCH_METADATA_SECTIONS: tuple[RuntimeDefaultsSection, ...] = (
    RuntimeDefaultsSection((), (
        ('SEARCH_SPACE_LEARNING_RATE', 5, (5,)),
        ('SEARCH_SPACE_HIDDEN_DIM', 7, (7,)),
        ('SEARCH_SPACE_STACK_NUM_LAYERS', 9, (9,)),
        ('SEARCH_SPACE_STACK_DROPOUT_PROBABILITY', 11, (11,)),
        ('SEARCH_SPACE_STACK_ACTIVATION', 13, (13,)),
        ('SEARCH_SPACE_ADAPTIVE_MIXTURE_NUM_EXPERTS', 18, (18,)),
    )),
)
# fmt: on

__all__ = ["CONFIGURATION_METADATA_SECTIONS", "SEARCH_METADATA_SECTIONS"]
