from __future__ import annotations

MAX_TRAINING_DATASETS = 50
MAX_TRAINING_MONITORS = 100
MAX_TRAINING_PLANNED_RUNS = 2000
MAX_TRAINING_SEARCH_AXES = 16
MAX_TRAINING_SEARCH_AXIS_VALUES = 50

__all__ = [
    "MAX_TRAINING_DATASETS",
    "MAX_TRAINING_MONITORS",
    "MAX_TRAINING_PLANNED_RUNS",
    "MAX_TRAINING_SEARCH_AXES",
    "MAX_TRAINING_SEARCH_AXIS_VALUES",
]
