from __future__ import annotations

import argparse
import json
import os
from enum import Enum
from typing import Any

os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")

from models.catalog import model_id_from_parts
from models.parser import (
    get_experiment_parser,
    resolve_dataset_names,
    resolve_experiment_mode,
)

from workbench.backend.inspector.discovery import (
    dataset_options_for_task,
    load_model_parts,
    preset_cli_name,
    preset_description,
)
from workbench.backend.inspector.errors import InspectorError
from workbench.backend.inspector.graph import ROOT_NODE_ID
from workbench.backend.inspector.service import inspect_model


def _details_suffix(details: dict[str, Any]) -> str:
    pieces = []
    if "gate" in details:
        pieces.append(f"gate={'enabled' if details['gate'] else 'off'}")
    if "halting" in details:
        pieces.append(f"halting={'enabled' if details['halting'] else 'off'}")
    if "dims" in details:
        pieces.append(str(details["dims"]).replace(" -> ", "->"))
    if "dropout" in details:
        pieces.append(f"dropout={details['dropout']}")
    if "activation" in details:
        pieces.append(f"activation={details['activation']}")
    if "layerNorm" in details:
        pieces.append(f"layer_norm={details['layerNorm']}")
    recurrent = details.get("recurrent")
    if isinstance(recurrent, dict):
        pieces.append(
            "recurrent="
            f"steps:{recurrent.get('maxSteps')},"
            f"gate:{'enabled' if recurrent.get('gate') else 'off'},"
            f"halting:{'enabled' if recurrent.get('halting') else 'off'}"
        )
    return " [" + ", ".join(pieces) + "]" if pieces else ""


def _children_by_source(edges: list[dict[str, str]]) -> dict[str, list[str]]:
    children: dict[str, list[str]] = {}
    for edge in edges:
        children.setdefault(edge["source"], []).append(edge["target"])
    return children


def _print_tree(result: dict[str, Any]) -> None:
    node_by_id = {node["id"]: node for node in result["nodes"]}
    children_by_source = _children_by_source(result["edges"])
    root = node_by_id[ROOT_NODE_ID]
    print(f"model: {root['typeName']}{_details_suffix(root['details'])}")

    def walk(node_id: str, prefix: str) -> None:
        children = children_by_source.get(node_id, [])
        for index, child_id in enumerate(children):
            child = node_by_id[child_id]
            branch = "`- " if index == len(children) - 1 else "|- "
            next_prefix = prefix + ("   " if index == len(children) - 1 else "|  ")
            child_name = child["path"].split(".")[-1]
            print(
                f"{prefix}{branch}{child_name}: "
                f"{child['typeName']}{_details_suffix(child['details'])}"
            )
            walk(child_id, next_prefix)

    walk(ROOT_NODE_ID, "")


def _print_result(
    preset: Enum,
    presets: Any,
    index: int,
    count: int,
    result: dict[str, Any],
) -> None:
    suffix = f" config {index + 1}/{count}" if count > 1 else ""
    print("=" * 100)
    print(f"{preset.name}{suffix}")
    description = preset_description(preset, presets)
    if description:
        print(f"description: {description}")
    _print_tree(result)


def _parse_args() -> argparse.Namespace:
    model_parser = argparse.ArgumentParser(add_help=False)
    model_parser.add_argument("--model-type", required=True)
    model_parser.add_argument("--model", required=True)
    model_args, _ = model_parser.parse_known_args()
    model_id = model_id_from_parts(model_args.model_type, model_args.model)
    if model_id is None:
        raise SystemExit(
            f"Unknown model: --model-type {model_args.model_type} "
            f"--model {model_args.model}"
        )
    parts = load_model_parts(model_id)
    parser = get_experiment_parser(
        parts.experiment_preset_enum.names(),
        parts.config_module.__name__.rsplit(".", 1)[0],
    )
    parser.description = "Inspect model structures generated by experiment presets."
    parser.add_argument("--model-type", required=True, help="Model type to inspect.")
    parser.add_argument("--model", required=True, help="Model package to inspect.")
    parser.add_argument(
        "--format",
        choices=["text", "json"],
        default="text",
        help="Output text tree or JSON graph.",
    )
    args = parser.parse_args()
    args.model_id = model_id_from_parts(args.model_type, args.model)
    if args.model_id is None:
        raise SystemExit(
            f"Unknown model: --model-type {args.model_type} --model {args.model}"
        )
    return args


def main() -> None:
    args = _parse_args()
    parts = load_model_parts(args.model_id)
    if getattr(args, "monitors", None):
        raise SystemExit("--print-model inspection does not support --monitors.")
    mode = resolve_experiment_mode(args, parts.experiment_preset_enum)
    if (
        mode.search_mode is not None
        or mode.search_keys is not None
        or mode.search_overrides
    ):
        raise SystemExit("--print-model inspection does not support search modes.")
    if mode.selected_presets is not None:
        raise SystemExit("--print-model inspection requires one --preset.")

    preset_members = (
        list(parts.experiment_preset_enum)
        if args.all_presets
        else [parts.experiment_preset_enum.get_member(args.preset)]
    )
    datasets = resolve_dataset_names(
        dataset_options_for_task(parts, mode.experiment_task),
        args.datasets,
    )
    dataset = datasets[0].__name__

    results = []
    for preset in preset_members:
        result = inspect_model(
            args.model_id,
            preset_cli_name(parts.experiment_preset_enum, preset),
            dataset=dataset,
            parsed_overrides=mode.config_overrides,
        )
        results.append((preset, result))

    if args.format == "json":
        payload = (
            [result for _, result in results] if args.all_presets else results[0][1]
        )
        print(json.dumps(payload, indent=2))
        return

    for preset, result in results:
        _print_result(preset, parts.presets, 0, 1, result)


if __name__ == "__main__":
    try:
        main()
    except InspectorError as exc:
        raise SystemExit(str(exc)) from exc
