"""Shared Viewer backend size limits."""

from __future__ import annotations

DEFAULT_MAX_LOG_ARCHIVE_UPLOAD_SIZE = 512 * 1024 * 1024
DEFAULT_MAX_LOG_ARCHIVE_EXTRACTED_SIZE = 2 * 1024 * 1024 * 1024

__all__ = [
    "DEFAULT_MAX_LOG_ARCHIVE_UPLOAD_SIZE",
    "DEFAULT_MAX_LOG_ARCHIVE_EXTRACTED_SIZE",
]
