from emperor.parametric.options import AdaptiveLayerOptions
from emperor.config import ModelConfig
from emperor.base.layer import LayerStackConfig
from emperor.linears.utils.presets import LinearPresets
from emperor.sampler.utils.presets import SamplerPresets
from emperor.linears.options import LinearLayerStackOptions
from emperor.experts.utils.presets import MixtureOfExpertsPresets
from emperor.augmentations.model import AdaptiveParameterBehaviourConfig
from emperor.parametric.utils.mixtures.base import AdaptiveMixtureConfig
from emperor.base.enums import ActivationOptions, LayerNormPositionOptions
from emperor.parametric.utils.mixtures.types.utils.enums import ClipParameterOptions
from emperor.experts.utils.enums import (
    ExpertWeightingPositionOptions,
    InitSamplerOptions,
)
from emperor.parametric.utils.mixtures.options import (
    AdaptiveBiasOptions,
    AdaptiveWeightOptions,
)
from emperor.parametric.utils.layers import (
    AdaptiveParameterLayerConfig,
    AdaptiveRouterOptions,
)
from emperor.augmentations.options import (
    DynamicBiasOptions,
    DynamicDepthOptions,
    DynamicDiagonalOptions,
    LinearMemoryOptions,
    LinearMemoryPositionOptions,
    LinearMemorySizeOptions,
)


class AdaptiveParameterLayerPresets:
    @staticmethod
    def adaptive_generator_mixture_preset(
        input_dim=8,
        output_dim=6,
        weighted_parameters_flag=False,
        clip_parameter_option=ClipParameterOptions.BEFORE,
        clip_range=5.0,
        top_k=3,
        num_experts=6,
    ) -> "AdaptiveMixtureConfig":
        return AdaptiveMixtureConfig(
            input_dim=input_dim,
            output_dim=output_dim,
            top_k=top_k,
            num_experts=num_experts,
            weighted_parameters_flag=weighted_parameters_flag,
            clip_parameter_option=clip_parameter_option,
            clip_range=clip_range,
        )

    @staticmethod
    def adaptive_generator_mixture_generator_preset(
        input_dim=8,
        output_dim=6,
        top_k=3,
        num_experts=6,
        weighted_parameters_flag=False,
        clip_parameter_option=ClipParameterOptions.BEFORE,
        clip_range=5.0,
        router_model_bias_flag: bool = False,
        router_model_noisy_topk_flag: bool = False,
        router_model_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        router_model_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        router_model_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        router_model_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        router_model_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        router_model_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        router_model_layer_stack_option=LinearLayerStackOptions.BASE,
        sampler_threshold=0.0,
        sampler_filter_above_threshold=False,
        sampler_num_topk_samples=0,
        sampler_normalize_probabilities_flag=False,
        sampler_switch_loss_weight=0.0,
        sampler_zero_centred_loss_weight=0.0,
        sampler_mutual_information_loss_weight=0.0,
        sampler_coefficient_of_variation_loss_weight=0.0,
        experts_layer_stack_option=LinearLayerStackOptions.BASE,
        experts_compute_expert_mixture_flag=False,
        experts_weighting_position_option=ExpertWeightingPositionOptions.BEFORE_EXPERTS,
        experts_init_sampler_option=InitSamplerOptions.SHARED,
        experts_weighted_parameters_flag=False,
        experts_capacity_factor: float = 0.0,
        experts_model_bias_flag: bool = False,
        experts_model_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        experts_model_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        experts_model_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        experts_model_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        experts_model_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        experts_model_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        stack_num_layers: int = 2,
        stack_hidden_dim: int = 0,
        stack_activation: ActivationOptions = ActivationOptions.RELU,
        stack_residual_flag: bool = False,
        stack_dropout_probability: float = 0.0,
    ) -> "AdaptiveMixtureConfig":
        _hidden_dim = max(input_dim, output_dim)
        stack_hidden_dim = stack_hidden_dim if stack_hidden_dim > 0 else _hidden_dim

        return AdaptiveMixtureConfig(
            input_dim=input_dim,
            output_dim=output_dim,
            top_k=top_k,
            num_experts=num_experts,
            weighted_parameters_flag=weighted_parameters_flag,
            clip_parameter_option=clip_parameter_option,
            clip_range=clip_range,
            override_config=MixtureOfExpertsPresets.experts_preset(
                input_dim=input_dim,
                output_dim=output_dim,
                router_model_bias_flag=router_model_bias_flag,
                router_model_noisy_topk_flag=router_model_noisy_topk_flag,
                router_model_generator_depth=router_model_generator_depth,
                router_model_diagonal_option=router_model_diagonal_option,
                router_model_bias_option=router_model_bias_option,
                router_model_memory_option=router_model_memory_option,
                router_model_memory_size_option=router_model_memory_size_option,
                router_model_memory_position_option=router_model_memory_position_option,
                router_model_layer_stack_option=router_model_layer_stack_option,
                sampler_threshold=sampler_threshold,
                sampler_filter_above_threshold=sampler_filter_above_threshold,
                sampler_num_topk_samples=sampler_num_topk_samples,
                sampler_normalize_probabilities_flag=sampler_normalize_probabilities_flag,
                sampler_switch_loss_weight=sampler_switch_loss_weight,
                sampler_zero_centred_loss_weight=sampler_zero_centred_loss_weight,
                sampler_mutual_information_loss_weight=sampler_mutual_information_loss_weight,
                sampler_coefficient_of_variation_loss_weight=sampler_coefficient_of_variation_loss_weight,
                experts_top_k=top_k,
                experts_num_experts=num_experts,
                experts_layer_stack_option=experts_layer_stack_option,
                experts_compute_expert_mixture_flag=experts_compute_expert_mixture_flag,
                experts_weighting_position_option=experts_weighting_position_option,
                experts_init_sampler_option=experts_init_sampler_option,
                experts_weighted_parameters_flag=experts_weighted_parameters_flag,
                experts_capacity_factor=experts_capacity_factor,
                experts_model_bias_flag=experts_model_bias_flag,
                experts_model_generator_depth=experts_model_generator_depth,
                experts_model_diagonal_option=experts_model_diagonal_option,
                experts_model_bias_option=experts_model_bias_option,
                experts_model_memory_option=experts_model_memory_option,
                experts_model_memory_size_option=experts_model_memory_size_option,
                experts_model_memory_position_option=experts_model_memory_position_option,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=stack_hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            ),
        )

    @staticmethod
    def adaptive_parameter_layer_preset(
        return_model_config_flag: bool = False,
        batch_size=8,
        input_dim=8,
        output_dim=6,
        adaptive_weight_option: AdaptiveWeightOptions = AdaptiveWeightOptions.GENERATOR,
        adaptive_bias_option: AdaptiveBiasOptions = AdaptiveBiasOptions.DISABLED,
        init_sampler_model_option: AdaptiveRouterOptions = AdaptiveRouterOptions.SHARED_ROUTER,
        time_tracker_flag: bool = False,
        adaptive_mixture_top_k=3,
        adaptive_mixture_num_experts=6,
        adaptive_mixture_weighted_parameters_flag=False,
        adaptive_mixture_clip_parameter_option=ClipParameterOptions.BEFORE,
        adaptive_mixture_clip_range=5.0,
        adaptive_behaviour_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        adaptive_behaviour_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        adaptive_behaviour_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        adaptive_behaviour_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        adaptive_behaviour_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        adaptive_behaviour_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        experts_router_model_bias_flag: bool = False,
        experts_router_model_noisy_topk_flag: bool = False,
        experts_router_model_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        experts_router_model_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        experts_router_model_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        experts_router_model_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        experts_router_model_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        experts_router_model_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        experts_router_model_layer_stack_option=LinearLayerStackOptions.BASE,
        experts_sampler_threshold=0.0,
        experts_sampler_filter_above_threshold=False,
        experts_sampler_num_topk_samples=0,
        experts_sampler_normalize_probabilities_flag=False,
        experts_sampler_switch_loss_weight=0.0,
        experts_sampler_zero_centred_loss_weight=0.0,
        experts_sampler_mutual_information_loss_weight=0.0,
        experts_sampler_coefficient_of_variation_loss_weight=0.0,
        experts_layer_stack_option=LinearLayerStackOptions.BASE,
        experts_compute_expert_mixture_flag=False,
        experts_weighting_position_option=ExpertWeightingPositionOptions.BEFORE_EXPERTS,
        experts_init_sampler_option=InitSamplerOptions.SHARED,
        experts_weighted_parameters_flag=False,
        experts_model_bias_flag: bool = False,
        experts_model_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        experts_model_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        experts_model_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        experts_model_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        experts_model_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        experts_model_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        stack_bias_flag: bool = False,
        stack_num_layers: int = 2,
        stack_hidden_dim: int = 0,
        stack_activation: ActivationOptions = ActivationOptions.RELU,
        stack_residual_flag: bool = False,
        stack_dropout_probability: float = 0.0,
    ) -> "AdaptiveParameterLayerConfig":
        _hidden_dim = max(input_dim, output_dim)
        stack_hidden_dim = stack_hidden_dim if stack_hidden_dim > 0 else _hidden_dim

        if (
            adaptive_weight_option == AdaptiveWeightOptions.GENERATOR
            or adaptive_bias_option == AdaptiveBiasOptions.GENERATOR
        ):
            override_config = AdaptiveParameterLayerPresets.adaptive_generator_mixture_generator_preset(
                input_dim=input_dim,
                output_dim=output_dim,
                top_k=adaptive_mixture_top_k,
                num_experts=adaptive_mixture_num_experts,
                weighted_parameters_flag=adaptive_mixture_weighted_parameters_flag,
                clip_parameter_option=adaptive_mixture_clip_parameter_option,
                clip_range=adaptive_mixture_clip_range,
                router_model_bias_flag=experts_router_model_bias_flag,
                router_model_noisy_topk_flag=experts_router_model_noisy_topk_flag,
                router_model_generator_depth=experts_router_model_generator_depth,
                router_model_diagonal_option=experts_router_model_diagonal_option,
                router_model_bias_option=experts_router_model_bias_option,
                router_model_memory_option=experts_router_model_memory_option,
                router_model_memory_size_option=experts_router_model_memory_size_option,
                router_model_memory_position_option=experts_router_model_memory_position_option,
                router_model_layer_stack_option=experts_router_model_layer_stack_option,
                sampler_threshold=experts_sampler_threshold,
                sampler_filter_above_threshold=experts_sampler_filter_above_threshold,
                sampler_num_topk_samples=experts_sampler_num_topk_samples,
                sampler_normalize_probabilities_flag=experts_sampler_normalize_probabilities_flag,
                sampler_switch_loss_weight=experts_sampler_switch_loss_weight,
                sampler_zero_centred_loss_weight=experts_sampler_zero_centred_loss_weight,
                sampler_mutual_information_loss_weight=experts_sampler_mutual_information_loss_weight,
                sampler_coefficient_of_variation_loss_weight=experts_sampler_coefficient_of_variation_loss_weight,
                experts_layer_stack_option=experts_layer_stack_option,
                experts_compute_expert_mixture_flag=experts_compute_expert_mixture_flag,
                experts_weighting_position_option=experts_weighting_position_option,
                experts_init_sampler_option=experts_init_sampler_option,
                experts_weighted_parameters_flag=experts_weighted_parameters_flag,
                experts_model_bias_flag=experts_model_bias_flag,
                experts_model_generator_depth=experts_model_generator_depth,
                experts_model_diagonal_option=experts_model_diagonal_option,
                experts_model_bias_option=experts_model_bias_option,
                experts_model_memory_option=experts_model_memory_option,
                experts_model_memory_size_option=experts_model_memory_size_option,
                experts_model_memory_position_option=experts_model_memory_position_option,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=stack_hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            )
        else:
            override_config = (
                AdaptiveParameterLayerPresets.adaptive_generator_mixture_preset(
                    input_dim=input_dim,
                    output_dim=output_dim,
                    top_k=adaptive_mixture_top_k,
                    num_experts=adaptive_mixture_num_experts,
                    weighted_parameters_flag=adaptive_mixture_weighted_parameters_flag,
                    clip_parameter_option=adaptive_mixture_clip_parameter_option,
                    clip_range=adaptive_mixture_clip_range,
                )
            )

        config = AdaptiveParameterLayerConfig(
            input_dim=input_dim,
            output_dim=output_dim,
            adaptive_weight_option=adaptive_weight_option,
            adaptive_bias_option=adaptive_bias_option,
            init_sampler_model_option=init_sampler_model_option,
            time_tracker_flag=time_tracker_flag,
            adaptive_behaviour_config=AdaptiveParameterBehaviourConfig(
                input_dim=input_dim,
                output_dim=output_dim,
                generator_depth=adaptive_behaviour_generator_depth,
                diagonal_option=adaptive_behaviour_diagonal_option,
                bias_option=adaptive_behaviour_bias_option,
                memory_option=adaptive_behaviour_memory_option,
                memory_size_option=adaptive_behaviour_memory_size_option,
                memory_position_option=adaptive_behaviour_memory_position_option,
                override_config=LinearPresets.adaptive_linear_layer_stack_preset(
                    input_dim=input_dim,
                    output_dim=output_dim,
                    bias_flag=stack_bias_flag,
                    generator_depth=adaptive_behaviour_generator_depth,
                    stack_num_layers=stack_num_layers,
                    stack_hidden_dim=stack_hidden_dim,
                    stack_activation=stack_activation,
                    stack_residual_flag=stack_residual_flag,
                    stack_dropout_probability=stack_dropout_probability,
                ),
            ),
            router_config=SamplerPresets.router_preset(
                input_dim=input_dim,
                num_experts=adaptive_mixture_num_experts,
                bias_flag=experts_router_model_bias_flag,
                noisy_topk_flag=experts_router_model_noisy_topk_flag,
                layer_stack_option=experts_router_model_layer_stack_option,
                bias_option=experts_router_model_bias_option,
                memory_option=experts_router_model_memory_option,
                generator_depth=experts_router_model_generator_depth,
                diagonal_option=experts_router_model_diagonal_option,
                memory_size_option=experts_router_model_memory_size_option,
                memory_position_option=experts_router_model_memory_position_option,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=stack_hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            ),
            sampler_config=SamplerPresets.sampler_preset(
                num_experts=adaptive_mixture_num_experts,
                top_k=adaptive_mixture_top_k,
                threshold=experts_sampler_threshold,
                filter_above_threshold=experts_sampler_filter_above_threshold,
                num_topk_samples=experts_sampler_num_topk_samples,
                normalize_probabilities_flag=experts_sampler_normalize_probabilities_flag,
                noisy_topk_flag=experts_router_model_noisy_topk_flag,
                coefficient_of_variation_loss_weight=experts_sampler_coefficient_of_variation_loss_weight,
                switch_loss_weight=experts_sampler_switch_loss_weight,
                zero_centred_loss_weight=experts_sampler_zero_centred_loss_weight,
                mutual_information_loss_weight=experts_sampler_mutual_information_loss_weight,
            ),
            override_config=override_config,
        )

        if not return_model_config_flag:
            return config

        return ModelConfig(
            batch_size=batch_size,
            input_dim=input_dim,
            output_dim=output_dim,
            parameter_generator_model_config=config,
        )

    @staticmethod
    def adaptive_parameter_layer_stack_preset(
        return_model_config_flag: bool = False,
        batch_size=4,
        input_dim=8,
        output_dim=6,
        hidden_dim: int = 4,
        num_layers: int = 2,
        activation: ActivationOptions = ActivationOptions.RELU,
        residual_flag: bool = False,
        dropout_probability: float = 0.0,
        adaptive_weight_option: AdaptiveWeightOptions = AdaptiveWeightOptions.GENERATOR,
        adaptive_bias_option: AdaptiveBiasOptions = AdaptiveBiasOptions.DISABLED,
        adaptive_mixture_top_k=3,
        adaptive_mixture_num_experts=6,
        adaptive_mixture_weighted_parameters_flag=False,
        adaptive_mixture_clip_parameter_option=ClipParameterOptions.BEFORE,
        adaptive_mixture_clip_range=5.0,
        adaptive_init_sampler_model_option: AdaptiveRouterOptions = AdaptiveRouterOptions.SHARED_ROUTER,
        adaptive_time_tracker_flag: bool = False,
        adaptive_behaviour_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        adaptive_behaviour_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        adaptive_behaviour_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        adaptive_behaviour_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        adaptive_behaviour_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        adaptive_behaviour_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        experts_router_model_bias_flag: bool = False,
        experts_router_model_noisy_topk_flag: bool = False,
        experts_router_model_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        experts_router_model_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        experts_router_model_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        experts_router_model_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        experts_router_model_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        experts_router_model_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        experts_router_model_layer_stack_option=LinearLayerStackOptions.BASE,
        experts_sampler_threshold=0.0,
        experts_sampler_filter_above_threshold=False,
        experts_sampler_num_topk_samples=0,
        experts_sampler_normalize_probabilities_flag=False,
        experts_sampler_switch_loss_weight=0.0,
        experts_sampler_zero_centred_loss_weight=0.0,
        experts_sampler_mutual_information_loss_weight=0.0,
        experts_sampler_coefficient_of_variation_loss_weight=0.0,
        experts_layer_stack_option=LinearLayerStackOptions.BASE,
        experts_compute_expert_mixture_flag=False,
        experts_weighting_position_option=ExpertWeightingPositionOptions.BEFORE_EXPERTS,
        experts_init_sampler_option=InitSamplerOptions.SHARED,
        experts_weighted_parameters_flag=False,
        experts_model_bias_flag: bool = False,
        experts_model_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        experts_model_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        experts_model_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        experts_model_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        experts_model_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        experts_model_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        stack_bias_flag: bool = False,
        stack_num_layers: int = 2,
        stack_hidden_dim: int = 0,
        stack_activation: ActivationOptions = ActivationOptions.RELU,
        stack_residual_flag: bool = False,
        stack_dropout_probability: float = 0.0,
    ) -> "LayerStackConfig":
        _hidden_dim = max(input_dim, output_dim)
        stack_hidden_dim = stack_hidden_dim if stack_hidden_dim > 0 else _hidden_dim

        config = LayerStackConfig(
            model_type=AdaptiveLayerOptions.BASE,
            input_dim=input_dim,
            hidden_dim=hidden_dim,
            output_dim=output_dim,
            num_layers=num_layers,
            activation=activation,
            layer_norm_position=LayerNormPositionOptions.NONE,
            residual_flag=residual_flag,
            adaptive_computation_flag=False,
            dropout_probability=dropout_probability,
            override_config=AdaptiveParameterLayerPresets.adaptive_parameter_layer_preset(
                input_dim=input_dim,
                output_dim=output_dim,
                adaptive_weight_option=adaptive_weight_option,
                adaptive_bias_option=adaptive_bias_option,
                init_sampler_model_option=adaptive_init_sampler_model_option,
                time_tracker_flag=adaptive_time_tracker_flag,
                adaptive_mixture_top_k=adaptive_mixture_top_k,
                adaptive_mixture_num_experts=adaptive_mixture_num_experts,
                adaptive_mixture_weighted_parameters_flag=adaptive_mixture_weighted_parameters_flag,
                adaptive_mixture_clip_parameter_option=adaptive_mixture_clip_parameter_option,
                adaptive_mixture_clip_range=adaptive_mixture_clip_range,
                adaptive_behaviour_generator_depth=adaptive_behaviour_generator_depth,
                adaptive_behaviour_diagonal_option=adaptive_behaviour_diagonal_option,
                adaptive_behaviour_bias_option=adaptive_behaviour_bias_option,
                adaptive_behaviour_memory_option=adaptive_behaviour_memory_option,
                adaptive_behaviour_memory_size_option=adaptive_behaviour_memory_size_option,
                adaptive_behaviour_memory_position_option=adaptive_behaviour_memory_position_option,
                experts_router_model_bias_flag=experts_router_model_bias_flag,
                experts_router_model_noisy_topk_flag=experts_router_model_noisy_topk_flag,
                experts_router_model_generator_depth=experts_router_model_generator_depth,
                experts_router_model_diagonal_option=experts_router_model_diagonal_option,
                experts_router_model_bias_option=experts_router_model_bias_option,
                experts_router_model_memory_option=experts_router_model_memory_option,
                experts_router_model_memory_size_option=experts_router_model_memory_size_option,
                experts_router_model_memory_position_option=experts_router_model_memory_position_option,
                experts_router_model_layer_stack_option=experts_router_model_layer_stack_option,
                experts_sampler_threshold=experts_sampler_threshold,
                experts_sampler_filter_above_threshold=experts_sampler_filter_above_threshold,
                experts_sampler_num_topk_samples=experts_sampler_num_topk_samples,
                experts_sampler_normalize_probabilities_flag=experts_sampler_normalize_probabilities_flag,
                experts_sampler_switch_loss_weight=experts_sampler_switch_loss_weight,
                experts_sampler_zero_centred_loss_weight=experts_sampler_zero_centred_loss_weight,
                experts_sampler_mutual_information_loss_weight=experts_sampler_mutual_information_loss_weight,
                experts_sampler_coefficient_of_variation_loss_weight=experts_sampler_coefficient_of_variation_loss_weight,
                experts_layer_stack_option=experts_layer_stack_option,
                experts_compute_expert_mixture_flag=experts_compute_expert_mixture_flag,
                experts_weighting_position_option=experts_weighting_position_option,
                experts_init_sampler_option=experts_init_sampler_option,
                experts_weighted_parameters_flag=experts_weighted_parameters_flag,
                experts_model_bias_flag=experts_model_bias_flag,
                experts_model_generator_depth=experts_model_generator_depth,
                experts_model_diagonal_option=experts_model_diagonal_option,
                experts_model_bias_option=experts_model_bias_option,
                experts_model_memory_option=experts_model_memory_option,
                experts_model_memory_size_option=experts_model_memory_size_option,
                experts_model_memory_position_option=experts_model_memory_position_option,
                stack_bias_flag=stack_bias_flag,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=stack_hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            ),
        )

        if not return_model_config_flag:
            return config

        return ModelConfig(
            batch_size=batch_size,
            input_dim=input_dim,
            output_dim=output_dim,
            layer_stack_config=config,
        )
