from torch import float32
from Emperor.linears.utils.presets import LinearPresets
from Emperor.attention.utils.enums import AttentionOptions
from Emperor.linears.options import LinearLayerStackOptions
from Emperor.adaptive.utils.layers import AdaptiveRouterOptions
from Emperor.experts.utils.presets import MixtureOfExpertsPresets
from Emperor.attention.utils.layer import MultiHeadAttentionConfig
from Emperor.adaptive.utils.presets import AdaptiveParameterLayerPresets
from Emperor.base.enums import ActivationOptions, LayerNormPositionOptions
from Emperor.adaptive.utils.mixtures.types.utils.enums import ClipParameterOptions
from Emperor.experts.utils.enums import (
    ExpertWeightingPositionOptions,
    InitSamplerOptions,
)
from Emperor.adaptive.utils.mixtures.options import (
    AdaptiveBiasOptions,
    AdaptiveWeightOptions,
)
from Emperor.behaviours.utils.enums import (
    DynamicBiasOptions,
    DynamicDepthOptions,
    DynamicDiagonalOptions,
    LinearMemoryOptions,
    LinearMemoryPositionOptions,
    LinearMemorySizeOptions,
)


class MultiHeadAttentionPresets:
    @staticmethod
    def multi_head_attention_preset(
        input_dim=8,
        hidden_dim=4,
        output_dim=6,
        model_type=LinearLayerStackOptions.ADAPTIVE,
        batch_size=8,
        num_heads=4,
        embedding_dim=12,
        query_key_projection_dim=14,
        value_projection_dim=16,
        target_sequence_length=18,
        source_sequence_length=20,
        target_dtype=float32,
        attention_option=AttentionOptions.INDEPENDENT,
        dropout_probability=0.0,
        key_value_bias_flag=False,
        zero_attention_flag=False,
        causal_attention_mask_flag=False,
        add_key_value_bias_flag=False,
        average_attention_weights_flag=False,
        return_attention_weights_flag=False,
        use_kv_expert_models_flag=False,
        adaptive_stack_num_layers=2,
        adaptive_stack_activation=ActivationOptions.RELU,
        adaptive_stack_residual_flag=False,
        adaptive_stack_dropout_probability=0.0,
        projector_adaptive_weight_option: AdaptiveWeightOptions = AdaptiveWeightOptions.GENERATOR,
        projector_adaptive_bias_option: AdaptiveBiasOptions = AdaptiveBiasOptions.GENERATOR,
        projector_adaptive_mixture_top_k=3,
        projector_adaptive_mixture_num_experts=6,
        projector_adaptive_mixture_weighted_parameters_flag=False,
        projector_adaptive_mixture_clip_parameter_option=ClipParameterOptions.BEFORE,
        projector_adaptive_mixture_clip_range=5.0,
        projector_adaptive_init_sampler_model_option: AdaptiveRouterOptions = AdaptiveRouterOptions.SHARED_ROUTER,
        projector_adaptive_time_tracker_flag: bool = False,
        projector_adaptive_behaviour_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        projector_adaptive_behaviour_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        projector_adaptive_behaviour_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        projector_adaptive_behaviour_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        projector_adaptive_behaviour_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        projector_adaptive_behaviour_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        projector_router_bias_flag: bool = False,
        projector_router_noisy_topk_flag: bool = False,
        projector_router_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        projector_router_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        projector_router_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        projector_router_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        projector_router_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        projector_router_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        projector_router_layer_stack_option=LinearLayerStackOptions.BASE,
        projector_sampler_threshold=0.0,
        projector_sampler_filter_above_threshold=False,
        projector_sampler_num_topk_samples=0,
        projector_sampler_normalize_probabilities_flag=False,
        projector_sampler_switch_loss_weight=0.0,
        projector_sampler_zero_centred_loss_weight=0.0,
        projector_sampler_mutual_information_loss_weight=0.0,
        projector_sampler_coefficient_of_variation_loss_weight=0.0,
        projector_experts_layer_stack_option=LinearLayerStackOptions.BASE,
        projector_experts_compute_expert_mixture_flag=True,
        projector_experts_weighting_position_option=ExpertWeightingPositionOptions.BEFORE_EXPERTS,
        projector_experts_init_sampler_option=InitSamplerOptions.LAYER,
        projector_experts_stack_num_layers: int = 2,
        projector_experts_weighted_parameters_flag=False,
        projector_experts_bias_flag: bool = False,
        projector_experts_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        projector_experts_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        projector_experts_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        projector_experts_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        projector_experts_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        projector_experts_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        stack_bias_flag=False,
        stack_num_layers: int = 2,
        stack_hidden_dim: int = 0,
        stack_activation: ActivationOptions = ActivationOptions.RELU,
        stack_residual_flag: bool = False,
        stack_dropout_probability: float = 0.0,
    ) -> "MultiHeadAttentionConfig":
        _hidden_dim = max(input_dim, output_dim)
        stack_hidden_dim = stack_hidden_dim if stack_hidden_dim > 0 else _hidden_dim

        projector_config = AdaptiveParameterLayerPresets.adaptive_parameter_layer_stack_preset(
            input_dim=input_dim,
            output_dim=output_dim,
            hidden_dim=hidden_dim,
            num_layers=adaptive_stack_num_layers,
            activation=adaptive_stack_activation,
            residual_flag=adaptive_stack_residual_flag,
            dropout_probability=adaptive_stack_dropout_probability,
            adaptive_weight_option=projector_adaptive_weight_option,
            adaptive_bias_option=projector_adaptive_bias_option,
            adaptive_mixture_top_k=projector_adaptive_mixture_top_k,
            adaptive_mixture_num_experts=projector_adaptive_mixture_num_experts,
            adaptive_mixture_weighted_parameters_flag=projector_adaptive_mixture_weighted_parameters_flag,
            adaptive_mixture_clip_parameter_option=projector_adaptive_mixture_clip_parameter_option,
            adaptive_mixture_clip_range=projector_adaptive_mixture_clip_range,
            adaptive_init_sampler_model_option=projector_adaptive_init_sampler_model_option,
            adaptive_time_tracker_flag=projector_adaptive_time_tracker_flag,
            adaptive_behaviour_generator_depth=projector_adaptive_behaviour_generator_depth,
            adaptive_behaviour_diagonal_option=projector_adaptive_behaviour_diagonal_option,
            adaptive_behaviour_bias_option=projector_adaptive_behaviour_bias_option,
            adaptive_behaviour_memory_option=projector_adaptive_behaviour_memory_option,
            adaptive_behaviour_memory_size_option=projector_adaptive_behaviour_memory_size_option,
            adaptive_behaviour_memory_position_option=projector_adaptive_behaviour_memory_position_option,
            experts_router_model_bias_flag=projector_router_bias_flag,
            experts_router_model_noisy_topk_flag=projector_router_noisy_topk_flag,
            experts_router_model_generator_depth=projector_router_generator_depth,
            experts_router_model_diagonal_option=projector_router_diagonal_option,
            experts_router_model_bias_option=projector_router_bias_option,
            experts_router_model_memory_option=projector_router_memory_option,
            experts_router_model_memory_size_option=projector_router_memory_size_option,
            experts_router_model_memory_position_option=projector_router_memory_position_option,
            experts_router_model_layer_stack_option=projector_router_layer_stack_option,
            experts_sampler_threshold=projector_sampler_threshold,
            experts_sampler_filter_above_threshold=projector_sampler_filter_above_threshold,
            experts_sampler_num_topk_samples=projector_sampler_num_topk_samples,
            experts_sampler_normalize_probabilities_flag=projector_sampler_normalize_probabilities_flag,
            experts_sampler_switch_loss_weight=projector_sampler_switch_loss_weight,
            experts_sampler_zero_centred_loss_weight=projector_sampler_zero_centred_loss_weight,
            experts_sampler_mutual_information_loss_weight=projector_sampler_mutual_information_loss_weight,
            experts_sampler_coefficient_of_variation_loss_weight=projector_sampler_coefficient_of_variation_loss_weight,
            experts_layer_stack_option=projector_experts_layer_stack_option,
            experts_compute_expert_mixture_flag=projector_experts_compute_expert_mixture_flag,
            experts_weighting_position_option=projector_experts_weighting_position_option,
            experts_init_sampler_option=projector_experts_init_sampler_option,
            experts_weighted_parameters_flag=projector_experts_weighted_parameters_flag,
            experts_model_bias_flag=projector_experts_bias_flag,
            experts_model_generator_depth=projector_experts_generator_depth,
            experts_model_diagonal_option=projector_experts_diagonal_option,
            experts_model_bias_option=projector_experts_bias_option,
            experts_model_memory_option=projector_experts_memory_option,
            experts_model_memory_size_option=projector_experts_memory_size_option,
            experts_model_memory_position_option=projector_experts_memory_position_option,
            stack_bias_flag=stack_bias_flag,
            stack_num_layers=stack_num_layers,
            stack_hidden_dim=stack_hidden_dim,
            stack_activation=stack_activation,
            stack_residual_flag=stack_residual_flag,
            stack_dropout_probability=stack_dropout_probability,
        )
        if model_type == LinearLayerStackOptions.BASE:
            projector_config = LinearPresets.base_linear_layer_stack_preset(
                input_dim=input_dim,
                output_dim=output_dim,
                bias_flag=stack_bias_flag,
                data_monitor=None,
                parameter_monitor=None,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=stack_hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            )
        if model_type == LinearLayerStackOptions.ADAPTIVE:
            projector_config = LinearPresets.adaptive_linear_layer_stack_preset(
                input_dim=input_dim,
                output_dim=output_dim,
                bias_flag=projector_router_bias_flag,
                generator_depth=projector_experts_generator_depth,
                diagonal_option=projector_experts_diagonal_option,
                bias_option=projector_experts_bias_option,
                memory_option=projector_experts_memory_option,
                memory_size_option=projector_experts_memory_size_option,
                memory_position_option=projector_experts_memory_position_option,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=stack_hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            )

        experts_config = MixtureOfExpertsPresets.experts_stack_preset(
            input_dim=input_dim,
            output_dim=output_dim,
            router_model_bias_flag=projector_router_bias_flag,
            router_model_noisy_topk_flag=projector_router_noisy_topk_flag,
            router_model_generator_depth=projector_router_generator_depth,
            router_model_diagonal_option=projector_router_diagonal_option,
            router_model_bias_option=projector_router_bias_option,
            router_model_memory_option=projector_router_memory_option,
            router_model_memory_size_option=projector_router_memory_size_option,
            router_model_memory_position_option=projector_router_memory_position_option,
            router_model_layer_stack_option=projector_router_layer_stack_option,
            sampler_threshold=projector_sampler_threshold,
            sampler_filter_above_threshold=projector_sampler_filter_above_threshold,
            sampler_num_topk_samples=projector_sampler_num_topk_samples,
            sampler_normalize_probabilities_flag=projector_sampler_normalize_probabilities_flag,
            sampler_switch_loss_weight=projector_sampler_switch_loss_weight,
            sampler_zero_centred_loss_weight=projector_sampler_zero_centred_loss_weight,
            sampler_mutual_information_loss_weight=projector_sampler_mutual_information_loss_weight,
            sampler_coefficient_of_variation_loss_weight=projector_sampler_coefficient_of_variation_loss_weight,
            experts_layer_stack_option=projector_experts_layer_stack_option,
            experts_compute_expert_mixture_flag=projector_experts_compute_expert_mixture_flag,
            experts_weighting_position_option=projector_experts_weighting_position_option,
            experts_init_sampler_option=projector_experts_init_sampler_option,
            experts_weighted_parameters_flag=projector_experts_weighted_parameters_flag,
            experts_model_bias_flag=projector_experts_bias_flag,
            experts_model_generator_depth=projector_experts_generator_depth,
            experts_model_diagonal_option=projector_experts_diagonal_option,
            experts_model_bias_option=projector_experts_bias_option,
            experts_model_memory_option=projector_experts_memory_option,
            experts_model_memory_size_option=projector_experts_memory_size_option,
            experts_model_memory_position_option=projector_experts_memory_position_option,
            experts_stack_num_layers=projector_experts_stack_num_layers,
            experts_stack_activation=ActivationOptions.RELU,
            experts_stack_residual_flag=False,
            experts_stack_dropout_probability=0.0,
            stack_num_layers=stack_num_layers,
            stack_hidden_dim=stack_hidden_dim,
            stack_activation=stack_activation,
            stack_residual_flag=stack_residual_flag,
            stack_dropout_probability=stack_dropout_probability,
        )

        return MultiHeadAttentionConfig(
            model_type=model_type,
            batch_size=batch_size,
            num_heads=num_heads,
            query_key_projection_dim=query_key_projection_dim,
            value_projection_dim=value_projection_dim,
            embedding_dim=embedding_dim,
            target_sequence_length=target_sequence_length,
            source_sequence_length=source_sequence_length,
            target_dtype=target_dtype,
            attention_option=attention_option,
            dropout_probability=dropout_probability,
            key_value_bias_flag=key_value_bias_flag,
            zero_attention_flag=zero_attention_flag,
            causal_attention_mask_flag=causal_attention_mask_flag,
            add_key_value_bias_flag=add_key_value_bias_flag,
            average_attention_weights_flag=average_attention_weights_flag,
            return_attention_weights_flag=return_attention_weights_flag,
            experts_config=experts_config,
            use_kv_expert_models_flag=use_kv_expert_models_flag,
            override_config=projector_config,
        )

    @staticmethod
    def multi_head_attention_linear_base_preset(
        batch_size: int = 8,
        layer_norm_position: LayerNormPositionOptions = LayerNormPositionOptions.NONE,
        bias_flag: bool = False,
        num_heads: int = 4,
        embedding_dim: int = 0,
        query_key_projection_dim: int = 0,
        value_projection_dim: int = 0,
        target_sequence_length: int = 0,
        source_sequence_length: int = 0,
        target_dtype=float32,
        attention_option: AttentionOptions = AttentionOptions.INDEPENDENT,
        dropout_probability: float = 0.0,
        key_value_bias_flag: bool = False,
        zero_attention_flag: bool = False,
        causal_attention_mask_flag: bool = False,
        add_key_value_bias_flag: bool = False,
        average_attention_weights_flag: bool = False,
        return_attention_weights_flag: bool = False,
        stack_num_layers: int = 1,
        stack_activation: ActivationOptions = ActivationOptions.RELU,
        stack_residual_flag: bool = False,
        stack_dropout_probability: float = 0.0,
    ) -> "MultiHeadAttentionConfig":
        layer_stack_model_option = LinearLayerStackOptions.BASE

        return MultiHeadAttentionConfig(
            batch_size=batch_size,
            num_heads=num_heads,
            model_type=layer_stack_model_option,
            query_key_projection_dim=query_key_projection_dim,
            value_projection_dim=value_projection_dim,
            embedding_dim=embedding_dim,
            target_sequence_length=target_sequence_length,
            source_sequence_length=source_sequence_length,
            target_dtype=target_dtype,
            attention_option=attention_option,
            dropout_probability=dropout_probability,
            key_value_bias_flag=key_value_bias_flag,
            zero_attention_flag=zero_attention_flag,
            causal_attention_mask_flag=causal_attention_mask_flag,
            add_key_value_bias_flag=add_key_value_bias_flag,
            average_attention_weights_flag=average_attention_weights_flag,
            return_attention_weights_flag=return_attention_weights_flag,
            override_config=LinearPresets.base_linear_layer_stack_preset(
                input_dim=embedding_dim,
                output_dim=embedding_dim,
                bias_flag=bias_flag,
                data_monitor=None,
                parameter_monitor=None,
                layer_norm_position=layer_norm_position,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=embedding_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            ),
        )

    @staticmethod
    def multi_head_attention_linear_adaptive_preset(
        batch_size: int = 8,
        bias_flag: bool = False,
        num_heads: int = 4,
        embedding_dim: int = 0,
        layer_norm_position: LayerNormPositionOptions = LayerNormPositionOptions.NONE,
        generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        query_key_projection_dim: int = 0,
        value_projection_dim: int = 0,
        target_sequence_length: int = 0,
        source_sequence_length: int = 0,
        target_dtype=float32,
        attention_option: AttentionOptions = AttentionOptions.INDEPENDENT,
        dropout_probability: float = 0.0,
        key_value_bias_flag: bool = False,
        zero_attention_flag: bool = False,
        causal_attention_mask_flag: bool = False,
        add_key_value_bias_flag: bool = False,
        average_attention_weights_flag: bool = False,
        return_attention_weights_flag: bool = False,
        stack_num_layers: int = 1,
        stack_activation: ActivationOptions = ActivationOptions.RELU,
        stack_residual_flag: bool = False,
        stack_dropout_probability: float = 0.0,
        adaptive_behaviour_stack_num_layers: int = 2,
    ) -> "MultiHeadAttentionConfig":
        layer_stack_model_option = LinearLayerStackOptions.ADAPTIVE

        return MultiHeadAttentionConfig(
            batch_size=batch_size,
            num_heads=num_heads,
            model_type=layer_stack_model_option,
            query_key_projection_dim=query_key_projection_dim,
            value_projection_dim=value_projection_dim,
            embedding_dim=embedding_dim,
            target_sequence_length=target_sequence_length,
            source_sequence_length=source_sequence_length,
            target_dtype=target_dtype,
            attention_option=attention_option,
            dropout_probability=dropout_probability,
            key_value_bias_flag=key_value_bias_flag,
            zero_attention_flag=zero_attention_flag,
            causal_attention_mask_flag=causal_attention_mask_flag,
            add_key_value_bias_flag=add_key_value_bias_flag,
            average_attention_weights_flag=average_attention_weights_flag,
            return_attention_weights_flag=return_attention_weights_flag,
            override_config=LinearPresets.adaptive_linear_layer_stack_preset(
                batch_size=batch_size,
                input_dim=embedding_dim,
                output_dim=embedding_dim,
                bias_flag=bias_flag,
                layer_norm_position=layer_norm_position,
                generator_depth=generator_depth,
                diagonal_option=diagonal_option,
                bias_option=bias_option,
                memory_option=memory_option,
                memory_size_option=memory_size_option,
                memory_position_option=memory_position_option,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=embedding_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
                adaptive_behaviour_stack_num_layers=adaptive_behaviour_stack_num_layers,
            ),
        )
