"""Shared Workbench backend size limits."""

from __future__ import annotations

DEFAULT_MAX_LOG_ARCHIVE_UPLOAD_SIZE = 512 * 1024 * 1024
DEFAULT_MAX_LOG_ARCHIVE_EXTRACTED_SIZE = 2 * 1024 * 1024 * 1024
DEFAULT_MAX_LOG_ARCHIVE_MEMBER_COUNT = 32_000
DEFAULT_MAX_LOG_ARCHIVE_PATH_BYTES = 4 * 1024 * 1024
DEFAULT_LOG_ARCHIVE_UPLOAD_CONCURRENCY = 1

__all__ = [
    "DEFAULT_LOG_ARCHIVE_UPLOAD_CONCURRENCY",
    "DEFAULT_MAX_LOG_ARCHIVE_UPLOAD_SIZE",
    "DEFAULT_MAX_LOG_ARCHIVE_EXTRACTED_SIZE",
    "DEFAULT_MAX_LOG_ARCHIVE_MEMBER_COUNT",
    "DEFAULT_MAX_LOG_ARCHIVE_PATH_BYTES",
]
