from Emperor.base.enums import ActivationOptions
from Emperor.linears.utils.presets import LinearPresets
from Emperor.linears.options import LinearLayerStackOptions
from Emperor.adaptive.utils.layers import AdaptiveRouterOptions
from Emperor.transformer.utils.feed_forward import FeedForwardConfig
from Emperor.adaptive.utils.presets import AdaptiveParameterLayerPresets
from Emperor.adaptive.utils.mixtures.types.utils.enums import ClipParameterOptions
from Emperor.experts.utils.enums import ExpertWeightingPositionOptions, LayerRoleOptions
from Emperor.adaptive.utils.mixtures.options import (
    AdaptiveBiasOptions,
    AdaptiveWeightOptions,
)
from Emperor.behaviours.utils.enums import (
    DynamicBiasOptions,
    DynamicDepthOptions,
    DynamicDiagonalOptions,
    LinearMemoryOptions,
    LinearMemoryPositionOptions,
    LinearMemorySizeOptions,
)


class TransformerPresets:
    @staticmethod
    def transformer_feed_forward_preset(
        input_dim=8,
        hidden_dim=4,
        output_dim=6,
        layer_stack_option=LinearLayerStackOptions.ADAPTIVE,
        num_layers=2,
        adaptive_stack_num_layers=2,
        adaptive_stack_activation=ActivationOptions.RELU,
        adaptive_stack_residual_flag=False,
        adaptive_stack_dropout_probability=0.0,
        projector_adaptive_weight_option: AdaptiveWeightOptions = AdaptiveWeightOptions.GENERATOR,
        projector_adaptive_bias_option: AdaptiveBiasOptions = AdaptiveBiasOptions.GENERATOR,
        projector_adaptive_mixture_top_k=3,
        projector_adaptive_mixture_num_experts=6,
        projector_adaptive_mixture_weighted_parameters_flag=False,
        projector_adaptive_mixture_clip_parameter_option=ClipParameterOptions.BEFORE,
        projector_adaptive_mixture_clip_range=5.0,
        projector_adaptive_init_sampler_model_option: AdaptiveRouterOptions = AdaptiveRouterOptions.SHARED_ROUTER,
        projector_adaptive_time_tracker_flag: bool = False,
        projector_adaptive_behaviour_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        projector_adaptive_behaviour_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        projector_adaptive_behaviour_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        projector_adaptive_behaviour_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        projector_adaptive_behaviour_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        projector_adaptive_behaviour_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        projector_router_bias_flag: bool = False,
        projector_router_noisy_topk_flag: bool = False,
        projector_router_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        projector_router_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        projector_router_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        projector_router_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        projector_router_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        projector_router_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        projector_router_layer_stack_option=LinearLayerStackOptions.BASE,
        projector_sampler_threshold=0.0,
        projector_sampler_filter_above_threshold=False,
        projector_sampler_num_topk_samples=0,
        projector_sampler_normalize_probabilities_flag=False,
        projector_sampler_switch_loss_weight=0.0,
        projector_sampler_zero_centred_loss_weight=0.0,
        projector_sampler_mutual_information_loss_weight=0.0,
        projector_sampler_coefficient_of_variation_loss_weight=0.0,
        projector_experts_layer_stack_option=LinearLayerStackOptions.BASE,
        projector_experts_compute_expert_mixture_flag=True,
        projector_experts_weighting_position_option=ExpertWeightingPositionOptions.BEFORE_EXPERTS,
        projector_experts_init_sampler_model_flag=False,
        projector_experts_weighted_parameters_flag=False,
        projector_experts_layer_role_option=LayerRoleOptions.GENERAL,
        projector_experts_bias_flag: bool = False,
        projector_experts_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        projector_experts_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        projector_experts_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        projector_experts_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        projector_experts_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        projector_experts_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        stack_bias_flag=False,
        stack_num_layers: int = 2,
        stack_hidden_dim: int = 0,
        stack_activation: ActivationOptions = ActivationOptions.RELU,
        stack_residual_flag: bool = False,
        stack_dropout_probability: float = 0.0,
    ) -> "FeedForwardConfig":
        _hidden_dim = max(input_dim, output_dim)
        stack_hidden_dim = stack_hidden_dim if stack_hidden_dim > 0 else _hidden_dim

        projector_config = AdaptiveParameterLayerPresets.adaptive_parameter_layer_stack_preset(
            input_dim=input_dim,
            output_dim=output_dim,
            hidden_dim=hidden_dim,
            num_layers=adaptive_stack_num_layers,
            activation=adaptive_stack_activation,
            residual_flag=adaptive_stack_residual_flag,
            dropout_probability=adaptive_stack_dropout_probability,
            adaptive_weight_option=projector_adaptive_weight_option,
            adaptive_bias_option=projector_adaptive_bias_option,
            adaptive_mixture_top_k=projector_adaptive_mixture_top_k,
            adaptive_mixture_num_experts=projector_adaptive_mixture_num_experts,
            adaptive_mixture_weighted_parameters_flag=projector_adaptive_mixture_weighted_parameters_flag,
            adaptive_mixture_clip_parameter_option=projector_adaptive_mixture_clip_parameter_option,
            adaptive_mixture_clip_range=projector_adaptive_mixture_clip_range,
            adaptive_init_sampler_model_option=projector_adaptive_init_sampler_model_option,
            adaptive_time_tracker_flag=projector_adaptive_time_tracker_flag,
            adaptive_behaviour_generator_depth=projector_adaptive_behaviour_generator_depth,
            adaptive_behaviour_diagonal_option=projector_adaptive_behaviour_diagonal_option,
            adaptive_behaviour_bias_option=projector_adaptive_behaviour_bias_option,
            adaptive_behaviour_memory_option=projector_adaptive_behaviour_memory_option,
            adaptive_behaviour_memory_size_option=projector_adaptive_behaviour_memory_size_option,
            adaptive_behaviour_memory_position_option=projector_adaptive_behaviour_memory_position_option,
            experts_router_model_bias_flag=projector_router_bias_flag,
            experts_router_model_noisy_topk_flag=projector_router_noisy_topk_flag,
            experts_router_model_generator_depth=projector_router_generator_depth,
            experts_router_model_diagonal_option=projector_router_diagonal_option,
            experts_router_model_bias_option=projector_router_bias_option,
            experts_router_model_memory_option=projector_router_memory_option,
            experts_router_model_memory_size_option=projector_router_memory_size_option,
            experts_router_model_memory_position_option=projector_router_memory_position_option,
            experts_router_model_layer_stack_option=projector_router_layer_stack_option,
            experts_sampler_threshold=projector_sampler_threshold,
            experts_sampler_filter_above_threshold=projector_sampler_filter_above_threshold,
            experts_sampler_num_topk_samples=projector_sampler_num_topk_samples,
            experts_sampler_normalize_probabilities_flag=projector_sampler_normalize_probabilities_flag,
            experts_sampler_switch_loss_weight=projector_sampler_switch_loss_weight,
            experts_sampler_zero_centred_loss_weight=projector_sampler_zero_centred_loss_weight,
            experts_sampler_mutual_information_loss_weight=projector_sampler_mutual_information_loss_weight,
            experts_sampler_coefficient_of_variation_loss_weight=projector_sampler_coefficient_of_variation_loss_weight,
            experts_layer_stack_option=projector_experts_layer_stack_option,
            experts_compute_expert_mixture_flag=projector_experts_compute_expert_mixture_flag,
            experts_weighting_position_option=projector_experts_weighting_position_option,
            experts_init_sampler_model_flag=projector_experts_init_sampler_model_flag,
            experts_weighted_parameters_flag=projector_experts_weighted_parameters_flag,
            experts_layer_role_option=projector_experts_layer_role_option,
            experts_model_bias_flag=projector_experts_bias_flag,
            experts_model_generator_depth=projector_experts_generator_depth,
            experts_model_diagonal_option=projector_experts_diagonal_option,
            experts_model_bias_option=projector_experts_bias_option,
            experts_model_memory_option=projector_experts_memory_option,
            experts_model_memory_size_option=projector_experts_memory_size_option,
            experts_model_memory_position_option=projector_experts_memory_position_option,
            stack_bias_flag=stack_bias_flag,
            stack_num_layers=stack_num_layers,
            stack_hidden_dim=stack_hidden_dim,
            stack_activation=stack_activation,
            stack_residual_flag=stack_residual_flag,
            stack_dropout_probability=stack_dropout_probability,
        )
        if layer_stack_option == LinearLayerStackOptions.BASE:
            projector_config = LinearPresets.base_linear_layer_stack_preset(
                input_dim=input_dim,
                output_dim=output_dim,
                bias_flag=stack_bias_flag,
                data_monitor=None,
                parameter_monitor=None,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=stack_hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            )
        if layer_stack_option == LinearLayerStackOptions.ADAPTIVE:
            projector_config = LinearPresets.adaptive_linear_layer_stack_preset(
                input_dim=input_dim,
                output_dim=output_dim,
                bias_flag=projector_router_bias_flag,
                generator_depth=projector_experts_generator_depth,
                diagonal_option=projector_experts_diagonal_option,
                bias_option=projector_experts_bias_option,
                memory_option=projector_experts_memory_option,
                memory_size_option=projector_experts_memory_size_option,
                memory_position_option=projector_experts_memory_position_option,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=stack_hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            )

        return FeedForwardConfig(
            layer_stack_option=layer_stack_option,
            input_dim=input_dim,
            output_dim=output_dim,
            num_layers=num_layers,
            override_config=projector_config,
        )
