from __future__ import annotations

import argparse
import json
import os
from enum import Enum
from typing import Any

os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")

from models.parser import get_experiment_parser, resolve_experiment_mode

from viewer.backend.inspector.discovery import (
    load_model_parts,
    option_cli_name,
    option_description,
)
from viewer.backend.inspector.errors import InspectorError
from viewer.backend.inspector.graph import ROOT_NODE_ID
from viewer.backend.inspector.service import inspect_model


def _details_suffix(details: dict[str, Any]) -> str:
    pieces = []
    if "gate" in details:
        pieces.append(f"gate={'enabled' if details['gate'] else 'off'}")
    if "halting" in details:
        pieces.append(f"halting={'enabled' if details['halting'] else 'off'}")
    if "dims" in details:
        pieces.append(str(details["dims"]).replace(" -> ", "->"))
    if "dropout" in details:
        pieces.append(f"dropout={details['dropout']}")
    if "activation" in details:
        pieces.append(f"activation={details['activation']}")
    if "layerNorm" in details:
        pieces.append(f"layer_norm={details['layerNorm']}")
    recurrent = details.get("recurrent")
    if isinstance(recurrent, dict):
        pieces.append(
            "recurrent="
            f"steps:{recurrent.get('maxSteps')},"
            f"gate:{'enabled' if recurrent.get('gate') else 'off'},"
            f"halting:{'enabled' if recurrent.get('halting') else 'off'}"
        )
    return " [" + ", ".join(pieces) + "]" if pieces else ""


def _children_by_source(edges: list[dict[str, str]]) -> dict[str, list[str]]:
    children: dict[str, list[str]] = {}
    for edge in edges:
        children.setdefault(edge["source"], []).append(edge["target"])
    return children


def _print_tree(result: dict[str, Any]) -> None:
    node_by_id = {node["id"]: node for node in result["nodes"]}
    children_by_source = _children_by_source(result["edges"])
    root = node_by_id[ROOT_NODE_ID]
    print(f"model: {root['typeName']}{_details_suffix(root['details'])}")

    def walk(node_id: str, prefix: str) -> None:
        children = children_by_source.get(node_id, [])
        for index, child_id in enumerate(children):
            child = node_by_id[child_id]
            branch = "`- " if index == len(children) - 1 else "|- "
            next_prefix = prefix + ("   " if index == len(children) - 1 else "|  ")
            child_name = child["path"].split(".")[-1]
            print(
                f"{prefix}{branch}{child_name}: "
                f"{child['typeName']}{_details_suffix(child['details'])}"
            )
            walk(child_id, next_prefix)

    walk(ROOT_NODE_ID, "")


def _print_result(option: Enum, index: int, count: int, result: dict[str, Any]) -> None:
    suffix = f" config {index + 1}/{count}" if count > 1 else ""
    print("=" * 100)
    print(f"{option.name}{suffix}")
    description = option_description(option)
    if description:
        print(f"description: {description}")
    _print_tree(result)


def _parse_args() -> argparse.Namespace:
    model_parser = argparse.ArgumentParser(add_help=False)
    model_parser.add_argument("--model", required=True)
    model_args, _ = model_parser.parse_known_args()
    parts = load_model_parts(model_args.model)
    parser = get_experiment_parser(
        parts.experiment_options.names(),
        f"models.{model_args.model}",
    )
    parser.description = "Inspect model structures generated by experiment presets."
    parser.add_argument("--model", required=True, help="Model package to inspect.")
    parser.add_argument(
        "--format",
        choices=["text", "json"],
        default="text",
        help="Output text tree or JSON graph.",
    )
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    parts = load_model_parts(args.model)
    (
        _,
        search_mode,
        search_keys,
        config_overrides,
        search_overrides,
    ) = resolve_experiment_mode(args, parts.experiment_options)
    if search_mode is not None or search_keys is not None or search_overrides:
        raise SystemExit("--print-model inspection does not support search modes.")

    options = (
        list(parts.experiment_options)
        if args.all_options
        else [parts.experiment_options.get_option(args.option)]
    )

    results = []
    for option in options:
        result = inspect_model(
            args.model,
            option_cli_name(parts.experiment_options, option),
            parsed_overrides=config_overrides,
        )
        results.append((option, result))

    if args.format == "json":
        payload = [result for _, result in results] if args.all_options else results[0][1]
        print(json.dumps(payload, indent=2))
        return

    for option, result in results:
        _print_result(option, 0, 1, result)


if __name__ == "__main__":
    try:
        main()
    except InspectorError as exc:
        raise SystemExit(str(exc)) from exc
