from torch import float32
from Emperor.attention.utils.enums import AttentionOptions
from Emperor.config import ModelConfig
from Emperor.linears.utils.presets import LinearPresets
from Emperor.linears.options import LinearLayerStackOptions
from Emperor.adaptive.options import AdaptiveLayerStackOptions
from Emperor.transformer.utils.layers import TransformerConfig
from Emperor.adaptive.utils.layers import AdaptiveRouterOptions
from Emperor.experts.options import MixtureOfExpertsStackOptions
from Emperor.experts.utils.presets import MixtureOfExpertsPresets
from Emperor.transformer.utils.patch.selector import PatchOptions
from Emperor.transformer.utils.feed_forward import FeedForwardConfig
from Emperor.transformer.utils.patch.options.base import PatchConfig
from Emperor.attention.utils.presets import MultiHeadAttentionPresets
from Emperor.adaptive.utils.presets import AdaptiveParameterLayerPresets
from Emperor.base.enums import ActivationOptions, LayerNormPositionOptions
from Emperor.adaptive.utils.mixtures.types.utils.enums import ClipParameterOptions
from Emperor.embedding.options import AbsolutePositionalEmbeddingOptions, RelativePositionalEmbeddingOptions
from Emperor.embedding.absolute.options.config import AbsolutePositionalEmbeddingConfig
from Emperor.embedding.relative.options.config import RelativePositionalEmbeddingConfig
from Emperor.experts.utils.enums import (
    ExpertWeightingPositionOptions,
    InitSamplerOptions,
)
from Emperor.adaptive.utils.mixtures.options import (
    AdaptiveBiasOptions,
    AdaptiveWeightOptions,
)
from Emperor.behaviours.utils.enums import (
    DynamicBiasOptions,
    DynamicDepthOptions,
    DynamicDiagonalOptions,
    LinearMemoryOptions,
    LinearMemoryPositionOptions,
    LinearMemorySizeOptions,
)


class TransformerPresets:
    @staticmethod
    def transformer_positional_embedding_preset(
        text_processing_flag=False,
        positional_embedding_option: AbsolutePositionalEmbeddingOptions = AbsolutePositionalEmbeddingOptions.LEARNED,
        num_embeddings: int = 24,
        embedding_dim: int = 8,
        padding_idx: int = 0,
        init_size: int = 1024,
        auto_expand_flag: bool = False,
        class_token_flag: bool = False,
    ) -> "AbsolutePositionalEmbeddingConfig":
        return AbsolutePositionalEmbeddingConfig(
            text_processing_flag=text_processing_flag,
            positional_embedding_option=positional_embedding_option,
            num_embeddings=num_embeddings,
            embedding_dim=embedding_dim,
            padding_idx=padding_idx,
            init_size=init_size,
            auto_expand_flag=auto_expand_flag,
            class_token_flag=class_token_flag,
        )

    @staticmethod
    def transformer_relative_positional_embedding_preset(
        positional_embedding_option: RelativePositionalEmbeddingOptions = RelativePositionalEmbeddingOptions.LEARNED,
        num_embeddings: int = 64,
        embedding_dim: int = 8,
        num_heads: int = 4,
        max_positions: int = 32,
        padding_idx: int = 0,
        init_size: int = 64,
        auto_expand_flag: bool = False,
    ) -> "RelativePositionalEmbeddingConfig":
        return RelativePositionalEmbeddingConfig(
            positional_embedding_option=positional_embedding_option,
            num_embeddings=num_embeddings,
            embedding_dim=embedding_dim,
            num_heads=num_heads,
            max_positions=max_positions,
            padding_idx=padding_idx,
            init_size=init_size,
            auto_expand_flag=auto_expand_flag,
        )

    @staticmethod
    def transformer_patch_preset(
        patch_option: "PatchOptions" = PatchOptions.LINEAR,
        embedding_dim: int = 32,
        patch_size: int = 3,
        stride: int = 3,
        padding: int = 0,
        dropout: float = 0.0,
        input_dim: int = 8,
        hidden_dim: int = 4,
        output_dim: int = 6,
        num_input_channels: int = 1,
        layer_norm_position: LayerNormPositionOptions = LayerNormPositionOptions.NONE,
        bias_flag: bool = False,
        stack_num_layers: int = 2,
        stack_activation: ActivationOptions = ActivationOptions.RELU,
        stack_residual_flag: bool = False,
        stack_dropout_probability: float = 0.0,
    ) -> "PatchConfig":
        return PatchConfig(
            patch_option=patch_option,
            embedding_dim=embedding_dim,
            patch_size=patch_size,
            stride=stride,
            padding=padding,
            dropout_probability=dropout,
            num_input_channels=num_input_channels,
            override_config=LinearPresets.base_linear_layer_stack_preset(
                input_dim=input_dim,
                output_dim=output_dim,
                bias_flag=bias_flag,
                data_monitor=None,
                parameter_monitor=None,
                layer_norm_position=layer_norm_position,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            ),
        )

    @staticmethod
    def transformer_feed_forward_preset(
        input_dim=8,
        hidden_dim=4,
        output_dim=6,
        layer_stack_option=LinearLayerStackOptions.ADAPTIVE,
        num_layers=2,
        adaptive_stack_num_layers=2,
        adaptive_stack_activation=ActivationOptions.RELU,
        adaptive_stack_residual_flag=False,
        adaptive_stack_dropout_probability=0.0,
        adaptive_weight_option: AdaptiveWeightOptions = AdaptiveWeightOptions.GENERATOR,
        adaptive_bias_option: AdaptiveBiasOptions = AdaptiveBiasOptions.GENERATOR,
        adaptive_mixture_top_k=3,
        adaptive_mixture_num_experts=6,
        adaptive_mixture_weighted_parameters_flag=False,
        adaptive_mixture_clip_parameter_option=ClipParameterOptions.BEFORE,
        adaptive_mixture_clip_range=5.0,
        adaptive_init_sampler_model_option: AdaptiveRouterOptions = AdaptiveRouterOptions.SHARED_ROUTER,
        adaptive_time_tracker_flag: bool = False,
        adaptive_behaviour_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        adaptive_behaviour_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        adaptive_behaviour_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        adaptive_behaviour_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        adaptive_behaviour_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        adaptive_behaviour_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        router_bias_flag: bool = False,
        router_noisy_topk_flag: bool = False,
        router_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        router_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        router_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        router_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        router_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        router_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        router_layer_stack_option=LinearLayerStackOptions.BASE,
        sampler_threshold=0.0,
        sampler_filter_above_threshold=False,
        sampler_num_topk_samples=0,
        sampler_normalize_probabilities_flag=False,
        sampler_switch_loss_weight=0.0,
        sampler_zero_centred_loss_weight=0.0,
        sampler_mutual_information_loss_weight=0.0,
        sampler_coefficient_of_variation_loss_weight=0.0,
        experts_layer_stack_option=LinearLayerStackOptions.BASE,
        experts_compute_expert_mixture_flag=True,
        experts_weighting_position_option=ExpertWeightingPositionOptions.BEFORE_EXPERTS,
        experts_init_sampler_option=InitSamplerOptions.SHARED,
        experts_weighted_parameters_flag=False,
        experts_bias_flag: bool = False,
        experts_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        experts_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        experts_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        experts_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        experts_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        experts_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        experts_stack_num_layers=2,
        experts_stack_activation=ActivationOptions.RELU,
        experts_stack_residual_flag=False,
        experts_stack_dropout_probability=0.0,
        stack_bias_flag=False,
        stack_num_layers: int = 2,
        stack_hidden_dim: int = 0,
        stack_activation: ActivationOptions = ActivationOptions.RELU,
        stack_residual_flag: bool = False,
        stack_dropout_probability: float = 0.0,
    ) -> "FeedForwardConfig":
        _hidden_dim = max(input_dim, output_dim)
        stack_hidden_dim = stack_hidden_dim if stack_hidden_dim > 0 else _hidden_dim

        projector_config = None
        if layer_stack_option == MixtureOfExpertsStackOptions.BASE:
            projector_config = MixtureOfExpertsPresets.experts_stack_preset(
                input_dim=input_dim,
                output_dim=output_dim,
                router_model_bias_flag=router_bias_flag,
                router_model_noisy_topk_flag=router_noisy_topk_flag,
                router_model_generator_depth=router_generator_depth,
                router_model_diagonal_option=router_diagonal_option,
                router_model_bias_option=router_bias_option,
                router_model_memory_option=router_memory_option,
                router_model_memory_size_option=router_memory_size_option,
                router_model_memory_position_option=router_memory_position_option,
                router_model_layer_stack_option=router_layer_stack_option,
                sampler_threshold=sampler_threshold,
                sampler_filter_above_threshold=sampler_filter_above_threshold,
                sampler_num_topk_samples=sampler_num_topk_samples,
                sampler_normalize_probabilities_flag=sampler_normalize_probabilities_flag,
                sampler_switch_loss_weight=sampler_switch_loss_weight,
                sampler_zero_centred_loss_weight=sampler_zero_centred_loss_weight,
                sampler_mutual_information_loss_weight=sampler_mutual_information_loss_weight,
                sampler_coefficient_of_variation_loss_weight=sampler_coefficient_of_variation_loss_weight,
                experts_layer_stack_option=experts_layer_stack_option,
                experts_compute_expert_mixture_flag=experts_compute_expert_mixture_flag,
                experts_weighting_position_option=experts_weighting_position_option,
                experts_init_sampler_option=experts_init_sampler_option,
                experts_weighted_parameters_flag=experts_weighted_parameters_flag,
                experts_model_bias_flag=experts_bias_flag,
                experts_model_generator_depth=experts_generator_depth,
                experts_model_diagonal_option=experts_diagonal_option,
                experts_model_bias_option=experts_bias_option,
                experts_model_memory_option=experts_memory_option,
                experts_model_memory_size_option=experts_memory_size_option,
                experts_model_memory_position_option=experts_memory_position_option,
                experts_stack_num_layers=experts_stack_num_layers,
                experts_stack_activation=experts_stack_activation,
                experts_stack_residual_flag=experts_stack_residual_flag,
                experts_stack_dropout_probability=experts_stack_dropout_probability,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=stack_hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            )

        if layer_stack_option == AdaptiveLayerStackOptions.BASE:
            projector_config = AdaptiveParameterLayerPresets.adaptive_parameter_layer_stack_preset(
                input_dim=input_dim,
                output_dim=output_dim,
                hidden_dim=hidden_dim,
                num_layers=adaptive_stack_num_layers,
                activation=adaptive_stack_activation,
                residual_flag=adaptive_stack_residual_flag,
                dropout_probability=adaptive_stack_dropout_probability,
                adaptive_weight_option=adaptive_weight_option,
                adaptive_bias_option=adaptive_bias_option,
                adaptive_mixture_top_k=adaptive_mixture_top_k,
                adaptive_mixture_num_experts=adaptive_mixture_num_experts,
                adaptive_mixture_weighted_parameters_flag=adaptive_mixture_weighted_parameters_flag,
                adaptive_mixture_clip_parameter_option=adaptive_mixture_clip_parameter_option,
                adaptive_mixture_clip_range=adaptive_mixture_clip_range,
                adaptive_init_sampler_model_option=adaptive_init_sampler_model_option,
                adaptive_time_tracker_flag=adaptive_time_tracker_flag,
                adaptive_behaviour_generator_depth=adaptive_behaviour_generator_depth,
                adaptive_behaviour_diagonal_option=adaptive_behaviour_diagonal_option,
                adaptive_behaviour_bias_option=adaptive_behaviour_bias_option,
                adaptive_behaviour_memory_option=adaptive_behaviour_memory_option,
                adaptive_behaviour_memory_size_option=adaptive_behaviour_memory_size_option,
                adaptive_behaviour_memory_position_option=adaptive_behaviour_memory_position_option,
                experts_router_model_bias_flag=router_bias_flag,
                experts_router_model_noisy_topk_flag=router_noisy_topk_flag,
                experts_router_model_generator_depth=router_generator_depth,
                experts_router_model_diagonal_option=router_diagonal_option,
                experts_router_model_bias_option=router_bias_option,
                experts_router_model_memory_option=router_memory_option,
                experts_router_model_memory_size_option=router_memory_size_option,
                experts_router_model_memory_position_option=router_memory_position_option,
                experts_router_model_layer_stack_option=router_layer_stack_option,
                experts_sampler_threshold=sampler_threshold,
                experts_sampler_filter_above_threshold=sampler_filter_above_threshold,
                experts_sampler_num_topk_samples=sampler_num_topk_samples,
                experts_sampler_normalize_probabilities_flag=sampler_normalize_probabilities_flag,
                experts_sampler_switch_loss_weight=sampler_switch_loss_weight,
                experts_sampler_zero_centred_loss_weight=sampler_zero_centred_loss_weight,
                experts_sampler_mutual_information_loss_weight=sampler_mutual_information_loss_weight,
                experts_sampler_coefficient_of_variation_loss_weight=sampler_coefficient_of_variation_loss_weight,
                experts_layer_stack_option=experts_layer_stack_option,
                experts_compute_expert_mixture_flag=experts_compute_expert_mixture_flag,
                experts_weighting_position_option=experts_weighting_position_option,
                experts_init_sampler_option=experts_init_sampler_option,
                experts_weighted_parameters_flag=experts_weighted_parameters_flag,
                experts_model_bias_flag=experts_bias_flag,
                experts_model_generator_depth=experts_generator_depth,
                experts_model_diagonal_option=experts_diagonal_option,
                experts_model_bias_option=experts_bias_option,
                experts_model_memory_option=experts_memory_option,
                experts_model_memory_size_option=experts_memory_size_option,
                experts_model_memory_position_option=experts_memory_position_option,
                stack_bias_flag=stack_bias_flag,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=stack_hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            )
        if layer_stack_option == LinearLayerStackOptions.BASE:
            projector_config = LinearPresets.base_linear_layer_stack_preset(
                input_dim=input_dim,
                output_dim=output_dim,
                bias_flag=stack_bias_flag,
                data_monitor=None,
                parameter_monitor=None,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=stack_hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            )
        if layer_stack_option == LinearLayerStackOptions.ADAPTIVE:
            projector_config = LinearPresets.adaptive_linear_layer_stack_preset(
                input_dim=input_dim,
                output_dim=output_dim,
                bias_flag=router_bias_flag,
                generator_depth=experts_generator_depth,
                diagonal_option=experts_diagonal_option,
                bias_option=experts_bias_option,
                memory_option=experts_memory_option,
                memory_size_option=experts_memory_size_option,
                memory_position_option=experts_memory_position_option,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=stack_hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            )

        return FeedForwardConfig(
            layer_stack_option=layer_stack_option,
            input_dim=input_dim,
            output_dim=output_dim,
            num_layers=num_layers,
            override_config=projector_config,
        )

    @staticmethod
    def transformer_feed_forward_linear_base_preset(
        input_dim: int = 8,
        hidden_dim: int = 4,
        output_dim: int = 6,
        layer_norm_position: LayerNormPositionOptions = LayerNormPositionOptions.NONE,
        bias_flag: bool = False,
        stack_num_layers: int = 2,
        stack_activation: ActivationOptions = ActivationOptions.RELU,
        stack_residual_flag: bool = False,
        stack_dropout_probability: float = 0.0,
    ) -> "FeedForwardConfig":
        layer_stack_model_option = LinearLayerStackOptions.BASE

        return FeedForwardConfig(
            layer_stack_option=layer_stack_model_option,
            input_dim=input_dim,
            output_dim=output_dim,
            num_layers=stack_num_layers,
            override_config=LinearPresets.base_linear_layer_stack_preset(
                input_dim=input_dim,
                output_dim=output_dim,
                bias_flag=bias_flag,
                data_monitor=None,
                parameter_monitor=None,
                layer_norm_position=layer_norm_position,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            ),
        )

    @staticmethod
    def transformer_feed_forward_linear_adaptive_preset(
        batch_size: int = 8,
        input_dim: int = 12,
        hidden_dim: int = 4,
        output_dim: int = 6,
        layer_norm_position: LayerNormPositionOptions = LayerNormPositionOptions.NONE,
        bias_flag: bool = True,
        generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        stack_num_layers: int = 2,
        stack_activation: ActivationOptions = ActivationOptions.RELU,
        stack_residual_flag: bool = False,
        stack_dropout_probability: float = 0.0,
        adaptive_behaviour_stack_num_layers: int = 2,
    ) -> "FeedForwardConfig":
        layer_stack_model_option = LinearLayerStackOptions.ADAPTIVE

        return FeedForwardConfig(
            layer_stack_option=layer_stack_model_option,
            input_dim=input_dim,
            output_dim=output_dim,
            num_layers=stack_num_layers,
            override_config=LinearPresets.adaptive_linear_layer_stack_preset(
                batch_size=batch_size,
                input_dim=input_dim,
                output_dim=output_dim,
                bias_flag=bias_flag,
                layer_norm_position=layer_norm_position,
                generator_depth=generator_depth,
                diagonal_option=diagonal_option,
                bias_option=bias_option,
                memory_option=memory_option,
                memory_size_option=memory_size_option,
                memory_position_option=memory_position_option,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
                adaptive_behaviour_stack_num_layers=adaptive_behaviour_stack_num_layers,
            ),
        )

    @staticmethod
    def transformer_preset(
        return_model_config_flag: bool = False,
        batch_size=8,
        input_dim=8,
        hidden_dim=4,
        output_dim=6,
        layer_stack_option=LinearLayerStackOptions.ADAPTIVE,
        num_layers=2,
        embedding_dim=8,
        source_sequence_length: int = 6,
        target_sequence_length: int = 6,
        layer_norm_position: AbsolutePositionalEmbeddingOptions = AbsolutePositionalEmbeddingOptions.LEARNED,
        dropout_probability: float = 0.0,
        causal_attention_mask_flag: bool = False,
        attention_model_type=LinearLayerStackOptions.ADAPTIVE,
        attention_num_heads=4,
        attention_target_sequence_length=18,
        attention_source_sequence_length=20,
        attention_target_dtype=float32,
        attention_dropout_probability=0.0,
        attention_key_value_bias_flag=False,
        attention_zero_attention_flag=False,
        attention_causal_attention_mask_flag=False,
        attention_add_key_value_bias_flag=False,
        attention_average_attention_weights_flag=False,
        attention_return_attention_weights_flag=False,
        attention_query_key_projection_dim: int = 0,
        attention_value_projection_dim: int = 0,
        attention_adaptive_stack_num_layers=2,
        attention_adaptive_stack_activation=ActivationOptions.RELU,
        attention_adaptive_stack_residual_flag=False,
        attention_adaptive_stack_dropout_probability=0.0,
        attention_adaptive_weight_option: AdaptiveWeightOptions = AdaptiveWeightOptions.GENERATOR,
        attention_adaptive_bias_option: AdaptiveBiasOptions = AdaptiveBiasOptions.GENERATOR,
        attention_adaptive_mixture_top_k=3,
        attention_adaptive_mixture_num_experts=6,
        attention_adaptive_mixture_weighted_parameters_flag=False,
        attention_adaptive_mixture_clip_parameter_option=ClipParameterOptions.BEFORE,
        attention_adaptive_mixture_clip_range=5.0,
        attention_adaptive_init_sampler_model_option: AdaptiveRouterOptions = AdaptiveRouterOptions.SHARED_ROUTER,
        attention_adaptive_time_tracker_flag: bool = False,
        attention_adaptive_behaviour_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        attention_adaptive_behaviour_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        attention_adaptive_behaviour_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        attention_adaptive_behaviour_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        attention_adaptive_behaviour_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        attention_adaptive_behaviour_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        attention_router_bias_flag: bool = False,
        attention_router_noisy_topk_flag: bool = False,
        attention_router_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        attention_router_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        attention_router_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        attention_router_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        attention_router_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        attention_router_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        attention_router_layer_stack_option=LinearLayerStackOptions.BASE,
        attention_sampler_threshold=0.0,
        attention_sampler_filter_above_threshold=False,
        attention_sampler_num_topk_samples=0,
        attention_sampler_normalize_probabilities_flag=False,
        attention_sampler_switch_loss_weight=0.0,
        attention_sampler_zero_centred_loss_weight=0.0,
        attention_sampler_mutual_information_loss_weight=0.0,
        attention_sampler_coefficient_of_variation_loss_weight=0.0,
        attention_experts_layer_stack_option=LinearLayerStackOptions.BASE,
        attention_experts_compute_expert_mixture_flag=True,
        attention_experts_weighting_position_option=ExpertWeightingPositionOptions.BEFORE_EXPERTS,
        attention_experts_init_sampler_option=InitSamplerOptions.DISABLED,
        attention_experts_weighted_parameters_flag=False,
        attention_experts_bias_flag: bool = False,
        attention_experts_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        attention_experts_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        attention_experts_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        attention_experts_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        attention_experts_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        attention_experts_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        forward_adaptive_stack_num_layers=2,
        forward_adaptive_stack_activation=ActivationOptions.RELU,
        forward_adaptive_stack_residual_flag=False,
        forward_adaptive_stack_dropout_probability=0.0,
        forward_adaptive_weight_option: AdaptiveWeightOptions = AdaptiveWeightOptions.GENERATOR,
        forward_adaptive_bias_option: AdaptiveBiasOptions = AdaptiveBiasOptions.GENERATOR,
        forward_adaptive_mixture_top_k=3,
        forward_adaptive_mixture_num_experts=6,
        forward_adaptive_mixture_weighted_parameters_flag=False,
        forward_adaptive_mixture_clip_parameter_option=ClipParameterOptions.BEFORE,
        forward_adaptive_mixture_clip_range=5.0,
        forward_adaptive_init_sampler_model_option: AdaptiveRouterOptions = AdaptiveRouterOptions.SHARED_ROUTER,
        forward_adaptive_time_tracker_flag: bool = False,
        forward_adaptive_behaviour_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        forward_adaptive_behaviour_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        forward_adaptive_behaviour_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        forward_adaptive_behaviour_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        forward_adaptive_behaviour_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        forward_adaptive_behaviour_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        forward_router_bias_flag: bool = False,
        forward_router_noisy_topk_flag: bool = False,
        forward_router_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        forward_router_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        forward_router_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        forward_router_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        forward_router_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        forward_router_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        forward_router_layer_stack_option=LinearLayerStackOptions.BASE,
        forward_sampler_threshold=0.0,
        forward_sampler_filter_above_threshold=False,
        forward_sampler_num_topk_samples=0,
        forward_sampler_normalize_probabilities_flag=False,
        forward_sampler_switch_loss_weight=0.0,
        forward_sampler_zero_centred_loss_weight=0.0,
        forward_sampler_mutual_information_loss_weight=0.0,
        forward_sampler_coefficient_of_variation_loss_weight=0.0,
        forward_experts_layer_stack_option=LinearLayerStackOptions.BASE,
        forward_experts_compute_expert_mixture_flag=True,
        forward_experts_weighting_position_option=ExpertWeightingPositionOptions.BEFORE_EXPERTS,
        forward_experts_init_sampler_option=InitSamplerOptions.DISABLED,
        forward_experts_weighted_parameters_flag=False,
        forward_experts_bias_flag: bool = False,
        forward_experts_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        forward_experts_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        forward_experts_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        forward_experts_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        forward_experts_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        forward_experts_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        forward_experts_stack_num_layers=2,
        forward_experts_stack_activation=ActivationOptions.RELU,
        forward_experts_stack_residual_flag=False,
        forward_experts_stack_dropout_probability=0.0,
        stack_bias_flag=False,
        stack_num_layers: int = 2,
        stack_hidden_dim: int = 0,
        stack_activation: ActivationOptions = ActivationOptions.RELU,
        stack_residual_flag: bool = False,
        stack_dropout_probability: float = 0.0,
    ) -> "TransformerConfig":
        _hidden_dim = max(input_dim, output_dim)
        stack_hidden_dim = stack_hidden_dim if stack_hidden_dim > 0 else _hidden_dim

        attention_config = MultiHeadAttentionPresets.multi_head_attention_preset(
            input_dim=input_dim,
            hidden_dim=hidden_dim,
            output_dim=output_dim,
            model_type=attention_model_type,
            batch_size=batch_size,
            num_heads=attention_num_heads,
            embedding_dim=embedding_dim,
            query_key_projection_dim=(
                attention_query_key_projection_dim
                if attention_query_key_projection_dim > 0
                else embedding_dim
            ),
            value_projection_dim=(
                attention_value_projection_dim
                if attention_value_projection_dim > 0
                else embedding_dim
            ),
            target_sequence_length=attention_target_sequence_length,
            source_sequence_length=attention_source_sequence_length,
            target_dtype=attention_target_dtype,
            attention_option=AttentionOptions.INDEPENDENT,
            dropout_probability=attention_dropout_probability,
            key_value_bias_flag=attention_key_value_bias_flag,
            zero_attention_flag=attention_zero_attention_flag,
            causal_attention_mask_flag=attention_causal_attention_mask_flag,
            add_key_value_bias_flag=attention_add_key_value_bias_flag,
            average_attention_weights_flag=attention_average_attention_weights_flag,
            return_attention_weights_flag=attention_return_attention_weights_flag,
            adaptive_stack_num_layers=attention_adaptive_stack_num_layers,
            adaptive_stack_activation=attention_adaptive_stack_activation,
            adaptive_stack_residual_flag=attention_adaptive_stack_residual_flag,
            adaptive_stack_dropout_probability=attention_adaptive_stack_dropout_probability,
            projector_adaptive_weight_option=attention_adaptive_weight_option,
            projector_adaptive_bias_option=attention_adaptive_bias_option,
            projector_adaptive_mixture_top_k=attention_adaptive_mixture_top_k,
            projector_adaptive_mixture_num_experts=attention_adaptive_mixture_num_experts,
            projector_adaptive_mixture_weighted_parameters_flag=attention_adaptive_mixture_weighted_parameters_flag,
            projector_adaptive_mixture_clip_parameter_option=attention_adaptive_mixture_clip_parameter_option,
            projector_adaptive_mixture_clip_range=attention_adaptive_mixture_clip_range,
            projector_adaptive_init_sampler_model_option=attention_adaptive_init_sampler_model_option,
            projector_adaptive_time_tracker_flag=attention_adaptive_time_tracker_flag,
            projector_adaptive_behaviour_generator_depth=attention_adaptive_behaviour_generator_depth,
            projector_adaptive_behaviour_diagonal_option=attention_adaptive_behaviour_diagonal_option,
            projector_adaptive_behaviour_bias_option=attention_adaptive_behaviour_bias_option,
            projector_adaptive_behaviour_memory_option=attention_adaptive_behaviour_memory_option,
            projector_adaptive_behaviour_memory_size_option=attention_adaptive_behaviour_memory_size_option,
            projector_adaptive_behaviour_memory_position_option=attention_adaptive_behaviour_memory_position_option,
            projector_router_bias_flag=attention_router_bias_flag,
            projector_router_noisy_topk_flag=attention_router_noisy_topk_flag,
            projector_router_generator_depth=attention_router_generator_depth,
            projector_router_diagonal_option=attention_router_diagonal_option,
            projector_router_bias_option=attention_router_bias_option,
            projector_router_memory_option=attention_router_memory_option,
            projector_router_memory_size_option=attention_router_memory_size_option,
            projector_router_memory_position_option=attention_router_memory_position_option,
            projector_router_layer_stack_option=attention_router_layer_stack_option,
            projector_sampler_threshold=attention_sampler_threshold,
            projector_sampler_filter_above_threshold=attention_sampler_filter_above_threshold,
            projector_sampler_num_topk_samples=attention_sampler_num_topk_samples,
            projector_sampler_normalize_probabilities_flag=attention_sampler_normalize_probabilities_flag,
            projector_sampler_switch_loss_weight=attention_sampler_switch_loss_weight,
            projector_sampler_zero_centred_loss_weight=attention_sampler_zero_centred_loss_weight,
            projector_sampler_mutual_information_loss_weight=attention_sampler_mutual_information_loss_weight,
            projector_sampler_coefficient_of_variation_loss_weight=attention_sampler_coefficient_of_variation_loss_weight,
            projector_experts_layer_stack_option=attention_experts_layer_stack_option,
            projector_experts_compute_expert_mixture_flag=attention_experts_compute_expert_mixture_flag,
            projector_experts_weighting_position_option=attention_experts_weighting_position_option,
            projector_experts_init_sampler_option=attention_experts_init_sampler_option,
            projector_experts_weighted_parameters_flag=attention_experts_weighted_parameters_flag,
            projector_experts_bias_flag=attention_experts_bias_flag,
            projector_experts_generator_depth=attention_experts_generator_depth,
            projector_experts_diagonal_option=attention_experts_diagonal_option,
            projector_experts_bias_option=attention_experts_bias_option,
            projector_experts_memory_option=attention_experts_memory_option,
            projector_experts_memory_size_option=attention_experts_memory_size_option,
            projector_experts_memory_position_option=attention_experts_memory_position_option,
            stack_bias_flag=stack_bias_flag,
            stack_num_layers=stack_num_layers,
            stack_hidden_dim=stack_hidden_dim,
            stack_activation=stack_activation,
            stack_residual_flag=stack_residual_flag,
            stack_dropout_probability=stack_dropout_probability,
        )

        feed_forward_config = TransformerPresets.transformer_feed_forward_preset(
            input_dim=input_dim,
            hidden_dim=embedding_dim,
            output_dim=output_dim,
            layer_stack_option=layer_stack_option,
            num_layers=num_layers,
            adaptive_stack_num_layers=forward_adaptive_stack_num_layers,
            adaptive_stack_activation=forward_adaptive_stack_activation,
            adaptive_stack_residual_flag=forward_adaptive_stack_residual_flag,
            adaptive_stack_dropout_probability=forward_adaptive_stack_dropout_probability,
            adaptive_weight_option=forward_adaptive_weight_option,
            adaptive_bias_option=forward_adaptive_bias_option,
            adaptive_mixture_top_k=forward_adaptive_mixture_top_k,
            adaptive_mixture_num_experts=forward_adaptive_mixture_num_experts,
            adaptive_mixture_weighted_parameters_flag=forward_adaptive_mixture_weighted_parameters_flag,
            adaptive_mixture_clip_parameter_option=forward_adaptive_mixture_clip_parameter_option,
            adaptive_mixture_clip_range=forward_adaptive_mixture_clip_range,
            adaptive_init_sampler_model_option=forward_adaptive_init_sampler_model_option,
            adaptive_time_tracker_flag=forward_adaptive_time_tracker_flag,
            adaptive_behaviour_generator_depth=forward_adaptive_behaviour_generator_depth,
            adaptive_behaviour_diagonal_option=forward_adaptive_behaviour_diagonal_option,
            adaptive_behaviour_bias_option=forward_adaptive_behaviour_bias_option,
            adaptive_behaviour_memory_option=forward_adaptive_behaviour_memory_option,
            adaptive_behaviour_memory_size_option=forward_adaptive_behaviour_memory_size_option,
            adaptive_behaviour_memory_position_option=forward_adaptive_behaviour_memory_position_option,
            router_bias_flag=forward_router_bias_flag,
            router_noisy_topk_flag=forward_router_noisy_topk_flag,
            router_generator_depth=forward_router_generator_depth,
            router_diagonal_option=forward_router_diagonal_option,
            router_bias_option=forward_router_bias_option,
            router_memory_option=forward_router_memory_option,
            router_memory_size_option=forward_router_memory_size_option,
            router_memory_position_option=forward_router_memory_position_option,
            router_layer_stack_option=forward_router_layer_stack_option,
            sampler_threshold=forward_sampler_threshold,
            sampler_filter_above_threshold=forward_sampler_filter_above_threshold,
            sampler_num_topk_samples=forward_sampler_num_topk_samples,
            sampler_normalize_probabilities_flag=forward_sampler_normalize_probabilities_flag,
            sampler_switch_loss_weight=forward_sampler_switch_loss_weight,
            sampler_zero_centred_loss_weight=forward_sampler_zero_centred_loss_weight,
            sampler_mutual_information_loss_weight=forward_sampler_mutual_information_loss_weight,
            sampler_coefficient_of_variation_loss_weight=forward_sampler_coefficient_of_variation_loss_weight,
            experts_layer_stack_option=forward_experts_layer_stack_option,
            experts_compute_expert_mixture_flag=forward_experts_compute_expert_mixture_flag,
            experts_weighting_position_option=forward_experts_weighting_position_option,
            experts_init_sampler_option=forward_experts_init_sampler_option,
            experts_weighted_parameters_flag=forward_experts_weighted_parameters_flag,
            experts_bias_flag=forward_experts_bias_flag,
            experts_generator_depth=forward_experts_generator_depth,
            experts_diagonal_option=forward_experts_diagonal_option,
            experts_bias_option=forward_experts_bias_option,
            experts_memory_option=forward_experts_memory_option,
            experts_memory_size_option=forward_experts_memory_size_option,
            experts_memory_position_option=forward_experts_memory_position_option,
            experts_stack_num_layers=forward_experts_stack_num_layers,
            experts_stack_activation=forward_experts_stack_activation,
            experts_stack_residual_flag=forward_experts_stack_residual_flag,
            experts_stack_dropout_probability=forward_experts_stack_dropout_probability,
            stack_bias_flag=stack_bias_flag,
            stack_num_layers=stack_num_layers,
            stack_hidden_dim=stack_hidden_dim,
            stack_activation=stack_activation,
            stack_residual_flag=stack_residual_flag,
            stack_dropout_probability=stack_dropout_probability,
        )

        config = TransformerConfig(
            num_layers=num_layers,
            source_sequence_length=source_sequence_length,
            target_sequence_length=target_sequence_length,
            embedding_dim=embedding_dim,
            layer_norm_position=layer_norm_position,
            dropout_probability=dropout_probability,
            causal_attention_mask_flag=causal_attention_mask_flag,
            attention_config=attention_config,
            feed_forward_config=feed_forward_config,
        )

        if not return_model_config_flag:
            return config

        return ModelConfig(
            batch_size=batch_size,
            input_dim=input_dim,
            output_dim=output_dim,
            layer_stack_config=config,
        )

    @staticmethod
    def transformer_linear_base_preset(
        return_model_config_flag: bool = False,
        batch_size: int = 8,
        num_layers: int = 2,
        layer_norm_position: LayerNormPositionOptions = LayerNormPositionOptions.NONE,
        num_heads: int = 4,
        embedding_dim: int = 0,
        query_key_projection_dim: int = 0,
        value_projection_dim: int = 0,
        target_sequence_length: int = 0,
        source_sequence_length: int = 0,
        target_dtype=float32,
        attention_option: bool = False,
        dropout_probability: float = 0.0,
        key_value_bias_flag: bool = False,
        zero_attention_flag: bool = False,
        causal_attention_mask_flag: bool = False,
        add_key_value_bias_flag: bool = False,
        average_attention_weights_flag: bool = False,
        return_attention_weights_flag: bool = False,
        attn_stack_num_layers: int = 1,
        attn_bias_flag: bool = False,
        ff_stack_num_layers: int = 2,
        ff_bias_flag: bool = False,
        stack_activation: ActivationOptions = ActivationOptions.RELU,
        stack_residual_flag: bool = False,
    ) -> "TransformerConfig":
        config = TransformerConfig(
            num_layers=num_layers,
            source_sequence_length=source_sequence_length,
            target_sequence_length=target_sequence_length,
            embedding_dim=embedding_dim,
            layer_norm_position=layer_norm_position,
            dropout_probability=dropout_probability,
            causal_attention_mask_flag=causal_attention_mask_flag,
            attention_config=MultiHeadAttentionPresets.multi_head_attention_linear_base_preset(
                batch_size=batch_size,
                layer_norm_position=layer_norm_position,
                bias_flag=attn_bias_flag,
                num_heads=num_heads,
                embedding_dim=embedding_dim,
                query_key_projection_dim=query_key_projection_dim,
                value_projection_dim=value_projection_dim,
                target_sequence_length=target_sequence_length,
                source_sequence_length=source_sequence_length,
                target_dtype=target_dtype,
                attention_option=attention_option,
                dropout_probability=dropout_probability,
                key_value_bias_flag=key_value_bias_flag,
                zero_attention_flag=zero_attention_flag,
                causal_attention_mask_flag=causal_attention_mask_flag,
                add_key_value_bias_flag=add_key_value_bias_flag,
                average_attention_weights_flag=average_attention_weights_flag,
                return_attention_weights_flag=return_attention_weights_flag,
                stack_num_layers=attn_stack_num_layers,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=dropout_probability,
            ),
            feed_forward_config=TransformerPresets.transformer_feed_forward_linear_base_preset(
                input_dim=embedding_dim,
                hidden_dim=embedding_dim,
                output_dim=embedding_dim,
                layer_norm_position=layer_norm_position,
                bias_flag=ff_bias_flag,
                stack_num_layers=ff_stack_num_layers,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=dropout_probability,
            ),
        )

        if not return_model_config_flag:
            return config

        return ModelConfig(
            batch_size=batch_size,
            input_dim=input_dim,
            output_dim=output_dim,
            layer_stack_config=config,
        )

    @staticmethod
    def transformer_linear_adaptive_preset(
        return_model_config_flag: bool = False,
        batch_size: int = 8,
        num_layers: int = 2,
        layer_norm_position: LayerNormPositionOptions = LayerNormPositionOptions.NONE,
        num_heads: int = 4,
        embedding_dim: int = 0,
        query_key_projection_dim: int = 0,
        value_projection_dim: int = 0,
        target_sequence_length: int = 0,
        source_sequence_length: int = 0,
        target_dtype=float32,
        attention_option: bool = False,
        dropout_probability: float = 0.0,
        key_value_bias_flag: bool = False,
        zero_attention_flag: bool = False,
        causal_attention_mask_flag: bool = False,
        add_key_value_bias_flag: bool = False,
        average_attention_weights_flag: bool = False,
        return_attention_weights_flag: bool = False,
        attn_stack_num_layers: int = 1,
        attn_bias_flag: bool = False,
        attn_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        attn_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        attn_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        attn_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        attn_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        attn_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        attn_behaviour_stack_num_layers: int = 2,
        ff_stack_num_layers: int = 2,
        ff_bias_flag: bool = False,
        ff_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        ff_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        ff_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        ff_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        ff_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        ff_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        ff_behaviour_stack_num_layers: int = 2,
        stack_activation: ActivationOptions = ActivationOptions.RELU,
        stack_residual_flag: bool = False,
    ) -> "TransformerConfig":
        config = TransformerConfig(
            num_layers=num_layers,
            source_sequence_length=source_sequence_length,
            target_sequence_length=target_sequence_length,
            embedding_dim=embedding_dim,
            layer_norm_position=layer_norm_position,
            dropout_probability=dropout_probability,
            causal_attention_mask_flag=causal_attention_mask_flag,
            attention_config=MultiHeadAttentionPresets.multi_head_attention_linear_adaptive_preset(
                batch_size=batch_size,
                layer_norm_position=layer_norm_position,
                bias_flag=attn_bias_flag,
                num_heads=num_heads,
                embedding_dim=embedding_dim,
                generator_depth=attn_generator_depth,
                diagonal_option=attn_diagonal_option,
                bias_option=attn_bias_option,
                memory_option=attn_memory_option,
                memory_size_option=attn_memory_size_option,
                memory_position_option=attn_memory_position_option,
                query_key_projection_dim=query_key_projection_dim,
                value_projection_dim=value_projection_dim,
                target_sequence_length=target_sequence_length,
                source_sequence_length=source_sequence_length,
                target_dtype=target_dtype,
                attention_option=attention_option,
                dropout_probability=dropout_probability,
                key_value_bias_flag=key_value_bias_flag,
                zero_attention_flag=zero_attention_flag,
                causal_attention_mask_flag=causal_attention_mask_flag,
                add_key_value_bias_flag=add_key_value_bias_flag,
                average_attention_weights_flag=average_attention_weights_flag,
                return_attention_weights_flag=return_attention_weights_flag,
                stack_num_layers=attn_stack_num_layers,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=dropout_probability,
                adaptive_behaviour_stack_num_layers=attn_behaviour_stack_num_layers,
            ),
            feed_forward_config=TransformerPresets.transformer_feed_forward_linear_adaptive_preset(
                batch_size=batch_size,
                input_dim=embedding_dim,
                hidden_dim=embedding_dim,
                output_dim=embedding_dim,
                layer_norm_position=layer_norm_position,
                bias_flag=ff_bias_flag,
                generator_depth=ff_generator_depth,
                diagonal_option=ff_diagonal_option,
                bias_option=ff_bias_option,
                memory_option=ff_memory_option,
                memory_size_option=ff_memory_size_option,
                memory_position_option=ff_memory_position_option,
                stack_num_layers=ff_stack_num_layers,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=dropout_probability,
                adaptive_behaviour_stack_num_layers=ff_behaviour_stack_num_layers,
            ),
        )

        if not return_model_config_flag:
            return config

        return ModelConfig(
            batch_size=batch_size,
            input_dim=input_dim,
            output_dim=output_dim,
            layer_stack_config=config,
        )
