from torch import float32
from Emperor.base.enums import ActivationOptions
from Emperor.linears.utils.presets import LinearPresets
from Emperor.linears.options import LinearLayerStackOptions
from Emperor.adaptive.options import AdaptiveLayerStackOptions
from Emperor.transformer.utils.layers import TransformerConfig
from Emperor.adaptive.utils.layers import AdaptiveRouterOptions
from Emperor.experts.options import MixtureOfExpertsStackOptions
from Emperor.experts.utils.presets import MixtureOfExpertsPresets
from Emperor.transformer.utils.feed_forward import FeedForwardConfig
from Emperor.attention.utils.presets import MultiHeadAttentionPresets
from Emperor.adaptive.utils.presets import AdaptiveParameterLayerPresets
from Emperor.adaptive.utils.mixtures.types.utils.enums import ClipParameterOptions
from Emperor.experts.utils.enums import ExpertWeightingPositionOptions, LayerRoleOptions
from Emperor.adaptive.utils.mixtures.options import (
    AdaptiveBiasOptions,
    AdaptiveWeightOptions,
)
from Emperor.behaviours.utils.enums import (
    DynamicBiasOptions,
    DynamicDepthOptions,
    DynamicDiagonalOptions,
    LinearMemoryOptions,
    LinearMemoryPositionOptions,
    LinearMemorySizeOptions,
)


class TransformerPresets:
    @staticmethod
    def transformer_feed_forward_preset(
        input_dim=8,
        hidden_dim=4,
        output_dim=6,
        layer_stack_option=LinearLayerStackOptions.ADAPTIVE,
        num_layers=2,
        adaptive_stack_num_layers=2,
        adaptive_stack_activation=ActivationOptions.RELU,
        adaptive_stack_residual_flag=False,
        adaptive_stack_dropout_probability=0.0,
        adaptive_weight_option: AdaptiveWeightOptions = AdaptiveWeightOptions.GENERATOR,
        adaptive_bias_option: AdaptiveBiasOptions = AdaptiveBiasOptions.GENERATOR,
        adaptive_mixture_top_k=3,
        adaptive_mixture_num_experts=6,
        adaptive_mixture_weighted_parameters_flag=False,
        adaptive_mixture_clip_parameter_option=ClipParameterOptions.BEFORE,
        adaptive_mixture_clip_range=5.0,
        adaptive_init_sampler_model_option: AdaptiveRouterOptions = AdaptiveRouterOptions.SHARED_ROUTER,
        adaptive_time_tracker_flag: bool = False,
        adaptive_behaviour_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        adaptive_behaviour_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        adaptive_behaviour_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        adaptive_behaviour_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        adaptive_behaviour_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        adaptive_behaviour_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        router_bias_flag: bool = False,
        router_noisy_topk_flag: bool = False,
        router_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        router_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        router_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        router_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        router_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        router_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        router_layer_stack_option=LinearLayerStackOptions.BASE,
        sampler_threshold=0.0,
        sampler_filter_above_threshold=False,
        sampler_num_topk_samples=0,
        sampler_normalize_probabilities_flag=False,
        sampler_switch_loss_weight=0.0,
        sampler_zero_centred_loss_weight=0.0,
        sampler_mutual_information_loss_weight=0.0,
        sampler_coefficient_of_variation_loss_weight=0.0,
        experts_layer_stack_option=LinearLayerStackOptions.BASE,
        experts_compute_expert_mixture_flag=True,
        experts_weighting_position_option=ExpertWeightingPositionOptions.BEFORE_EXPERTS,
        experts_init_sampler_model_flag=False,
        experts_weighted_parameters_flag=False,
        experts_layer_role_option=LayerRoleOptions.GENERAL,
        experts_bias_flag: bool = False,
        experts_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        experts_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        experts_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        experts_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        experts_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        experts_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        experts_stack_num_layers=2,
        experts_stack_activation=ActivationOptions.RELU,
        experts_stack_residual_flag=False,
        experts_stack_dropout_probability=0.0,
        stack_bias_flag=False,
        stack_num_layers: int = 2,
        stack_hidden_dim: int = 0,
        stack_activation: ActivationOptions = ActivationOptions.RELU,
        stack_residual_flag: bool = False,
        stack_dropout_probability: float = 0.0,
    ) -> "FeedForwardConfig":
        _hidden_dim = max(input_dim, output_dim)
        stack_hidden_dim = stack_hidden_dim if stack_hidden_dim > 0 else _hidden_dim

        projector_config = None
        if layer_stack_option == MixtureOfExpertsStackOptions.BASE:
            projector_config = MixtureOfExpertsPresets.experts_stack_preset(
                input_dim=input_dim,
                output_dim=output_dim,
                router_model_bias_flag=router_bias_flag,
                router_model_noisy_topk_flag=router_noisy_topk_flag,
                router_model_generator_depth=router_generator_depth,
                router_model_diagonal_option=router_diagonal_option,
                router_model_bias_option=router_bias_option,
                router_model_memory_option=router_memory_option,
                router_model_memory_size_option=router_memory_size_option,
                router_model_memory_position_option=router_memory_position_option,
                router_model_layer_stack_option=router_layer_stack_option,
                sampler_threshold=sampler_threshold,
                sampler_filter_above_threshold=sampler_filter_above_threshold,
                sampler_num_topk_samples=sampler_num_topk_samples,
                sampler_normalize_probabilities_flag=sampler_normalize_probabilities_flag,
                sampler_switch_loss_weight=sampler_switch_loss_weight,
                sampler_zero_centred_loss_weight=sampler_zero_centred_loss_weight,
                sampler_mutual_information_loss_weight=sampler_mutual_information_loss_weight,
                sampler_coefficient_of_variation_loss_weight=sampler_coefficient_of_variation_loss_weight,
                experts_layer_stack_option=experts_layer_stack_option,
                experts_compute_expert_mixture_flag=experts_compute_expert_mixture_flag,
                experts_weighting_position_option=experts_weighting_position_option,
                experts_init_sampler_model_flag=experts_init_sampler_model_flag,
                experts_weighted_parameters_flag=experts_weighted_parameters_flag,
                experts_layer_role_option=experts_layer_role_option,
                experts_model_bias_flag=experts_bias_flag,
                experts_model_generator_depth=experts_generator_depth,
                experts_model_diagonal_option=experts_diagonal_option,
                experts_model_bias_option=experts_bias_option,
                experts_model_memory_option=experts_memory_option,
                experts_model_memory_size_option=experts_memory_size_option,
                experts_model_memory_position_option=experts_memory_position_option,
                experts_stack_num_layers=experts_stack_num_layers,
                experts_stack_activation=experts_stack_activation,
                experts_stack_residual_flag=experts_stack_residual_flag,
                experts_stack_dropout_probability=experts_stack_dropout_probability,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=stack_hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            )

        if layer_stack_option == AdaptiveLayerStackOptions.BASE:
            projector_config = AdaptiveParameterLayerPresets.adaptive_parameter_layer_stack_preset(
                input_dim=input_dim,
                output_dim=output_dim,
                hidden_dim=hidden_dim,
                num_layers=adaptive_stack_num_layers,
                activation=adaptive_stack_activation,
                residual_flag=adaptive_stack_residual_flag,
                dropout_probability=adaptive_stack_dropout_probability,
                adaptive_weight_option=adaptive_weight_option,
                adaptive_bias_option=adaptive_bias_option,
                adaptive_mixture_top_k=adaptive_mixture_top_k,
                adaptive_mixture_num_experts=adaptive_mixture_num_experts,
                adaptive_mixture_weighted_parameters_flag=adaptive_mixture_weighted_parameters_flag,
                adaptive_mixture_clip_parameter_option=adaptive_mixture_clip_parameter_option,
                adaptive_mixture_clip_range=adaptive_mixture_clip_range,
                adaptive_init_sampler_model_option=adaptive_init_sampler_model_option,
                adaptive_time_tracker_flag=adaptive_time_tracker_flag,
                adaptive_behaviour_generator_depth=adaptive_behaviour_generator_depth,
                adaptive_behaviour_diagonal_option=adaptive_behaviour_diagonal_option,
                adaptive_behaviour_bias_option=adaptive_behaviour_bias_option,
                adaptive_behaviour_memory_option=adaptive_behaviour_memory_option,
                adaptive_behaviour_memory_size_option=adaptive_behaviour_memory_size_option,
                adaptive_behaviour_memory_position_option=adaptive_behaviour_memory_position_option,
                experts_router_model_bias_flag=router_bias_flag,
                experts_router_model_noisy_topk_flag=router_noisy_topk_flag,
                experts_router_model_generator_depth=router_generator_depth,
                experts_router_model_diagonal_option=router_diagonal_option,
                experts_router_model_bias_option=router_bias_option,
                experts_router_model_memory_option=router_memory_option,
                experts_router_model_memory_size_option=router_memory_size_option,
                experts_router_model_memory_position_option=router_memory_position_option,
                experts_router_model_layer_stack_option=router_layer_stack_option,
                experts_sampler_threshold=sampler_threshold,
                experts_sampler_filter_above_threshold=sampler_filter_above_threshold,
                experts_sampler_num_topk_samples=sampler_num_topk_samples,
                experts_sampler_normalize_probabilities_flag=sampler_normalize_probabilities_flag,
                experts_sampler_switch_loss_weight=sampler_switch_loss_weight,
                experts_sampler_zero_centred_loss_weight=sampler_zero_centred_loss_weight,
                experts_sampler_mutual_information_loss_weight=sampler_mutual_information_loss_weight,
                experts_sampler_coefficient_of_variation_loss_weight=sampler_coefficient_of_variation_loss_weight,
                experts_layer_stack_option=experts_layer_stack_option,
                experts_compute_expert_mixture_flag=experts_compute_expert_mixture_flag,
                experts_weighting_position_option=experts_weighting_position_option,
                experts_init_sampler_model_flag=experts_init_sampler_model_flag,
                experts_weighted_parameters_flag=experts_weighted_parameters_flag,
                experts_layer_role_option=experts_layer_role_option,
                experts_model_bias_flag=experts_bias_flag,
                experts_model_generator_depth=experts_generator_depth,
                experts_model_diagonal_option=experts_diagonal_option,
                experts_model_bias_option=experts_bias_option,
                experts_model_memory_option=experts_memory_option,
                experts_model_memory_size_option=experts_memory_size_option,
                experts_model_memory_position_option=experts_memory_position_option,
                stack_bias_flag=stack_bias_flag,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=stack_hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            )
        if layer_stack_option == LinearLayerStackOptions.BASE:
            projector_config = LinearPresets.base_linear_layer_stack_preset(
                input_dim=input_dim,
                output_dim=output_dim,
                bias_flag=stack_bias_flag,
                data_monitor=None,
                parameter_monitor=None,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=stack_hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            )
        if layer_stack_option == LinearLayerStackOptions.ADAPTIVE:
            projector_config = LinearPresets.adaptive_linear_layer_stack_preset(
                input_dim=input_dim,
                output_dim=output_dim,
                bias_flag=router_bias_flag,
                generator_depth=experts_generator_depth,
                diagonal_option=experts_diagonal_option,
                bias_option=experts_bias_option,
                memory_option=experts_memory_option,
                memory_size_option=experts_memory_size_option,
                memory_position_option=experts_memory_position_option,
                stack_num_layers=stack_num_layers,
                stack_hidden_dim=stack_hidden_dim,
                stack_activation=stack_activation,
                stack_residual_flag=stack_residual_flag,
                stack_dropout_probability=stack_dropout_probability,
            )

        return FeedForwardConfig(
            layer_stack_option=layer_stack_option,
            input_dim=input_dim,
            output_dim=output_dim,
            num_layers=num_layers,
            override_config=projector_config,
        )

    @staticmethod
    def transformer_preset(
        input_dim=8,
        hidden_dim=4,
        output_dim=6,
        layer_stack_option=LinearLayerStackOptions.ADAPTIVE,
        num_layers=2,
        embedding_dim=8,
        source_sequence_length: int = 6,
        target_sequence_length: int = 6,
        layer_norm_dim: int = 8,
        causal_attention_mask_flag: bool = False,
        attention_model_type=LinearLayerStackOptions.ADAPTIVE,
        attention_batch_size=8,
        attention_num_heads=4,
        attention_target_sequence_length=18,
        attention_source_sequence_length=20,
        attention_target_dtype=float32,
        attention_dropout_probability=0.0,
        attention_key_value_bias_flag=False,
        attention_zero_attention_flag=False,
        attention_causal_attention_mask_flag=False,
        attention_add_key_value_bias_flag=False,
        attention_average_attention_weights_flag=False,
        attention_return_attention_weights_flag=False,
        attention_adaptive_stack_num_layers=2,
        attention_adaptive_stack_activation=ActivationOptions.RELU,
        attention_adaptive_stack_residual_flag=False,
        attention_adaptive_stack_dropout_probability=0.0,
        attention_adaptive_weight_option: AdaptiveWeightOptions = AdaptiveWeightOptions.GENERATOR,
        attention_adaptive_bias_option: AdaptiveBiasOptions = AdaptiveBiasOptions.GENERATOR,
        attention_adaptive_mixture_top_k=3,
        attention_adaptive_mixture_num_experts=6,
        attention_adaptive_mixture_weighted_parameters_flag=False,
        attention_adaptive_mixture_clip_parameter_option=ClipParameterOptions.BEFORE,
        attention_adaptive_mixture_clip_range=5.0,
        attention_adaptive_init_sampler_model_option: AdaptiveRouterOptions = AdaptiveRouterOptions.SHARED_ROUTER,
        attention_adaptive_time_tracker_flag: bool = False,
        attention_adaptive_behaviour_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        attention_adaptive_behaviour_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        attention_adaptive_behaviour_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        attention_adaptive_behaviour_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        attention_adaptive_behaviour_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        attention_adaptive_behaviour_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        attention_router_bias_flag: bool = False,
        attention_router_noisy_topk_flag: bool = False,
        attention_router_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        attention_router_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        attention_router_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        attention_router_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        attention_router_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        attention_router_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        attention_router_layer_stack_option=LinearLayerStackOptions.BASE,
        attention_sampler_threshold=0.0,
        attention_sampler_filter_above_threshold=False,
        attention_sampler_num_topk_samples=0,
        attention_sampler_normalize_probabilities_flag=False,
        attention_sampler_switch_loss_weight=0.0,
        attention_sampler_zero_centred_loss_weight=0.0,
        attention_sampler_mutual_information_loss_weight=0.0,
        attention_sampler_coefficient_of_variation_loss_weight=0.0,
        attention_experts_layer_stack_option=LinearLayerStackOptions.BASE,
        attention_experts_compute_expert_mixture_flag=True,
        attention_experts_weighting_position_option=ExpertWeightingPositionOptions.BEFORE_EXPERTS,
        attention_experts_init_sampler_model_flag=False,
        attention_experts_weighted_parameters_flag=False,
        attention_experts_layer_role_option=LayerRoleOptions.GENERAL,
        attention_experts_bias_flag: bool = False,
        attention_experts_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        attention_experts_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        attention_experts_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        attention_experts_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        attention_experts_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        attention_experts_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        forward_adaptive_stack_num_layers=2,
        forward_adaptive_stack_activation=ActivationOptions.RELU,
        forward_adaptive_stack_residual_flag=False,
        forward_adaptive_stack_dropout_probability=0.0,
        forward_adaptive_weight_option: AdaptiveWeightOptions = AdaptiveWeightOptions.GENERATOR,
        forward_adaptive_bias_option: AdaptiveBiasOptions = AdaptiveBiasOptions.GENERATOR,
        forward_adaptive_mixture_top_k=3,
        forward_adaptive_mixture_num_experts=6,
        forward_adaptive_mixture_weighted_parameters_flag=False,
        forward_adaptive_mixture_clip_parameter_option=ClipParameterOptions.BEFORE,
        forward_adaptive_mixture_clip_range=5.0,
        forward_adaptive_init_sampler_model_option: AdaptiveRouterOptions = AdaptiveRouterOptions.SHARED_ROUTER,
        forward_adaptive_time_tracker_flag: bool = False,
        forward_adaptive_behaviour_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        forward_adaptive_behaviour_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        forward_adaptive_behaviour_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        forward_adaptive_behaviour_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        forward_adaptive_behaviour_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        forward_adaptive_behaviour_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        forward_router_bias_flag: bool = False,
        forward_router_noisy_topk_flag: bool = False,
        forward_router_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        forward_router_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        forward_router_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        forward_router_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        forward_router_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        forward_router_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        forward_router_layer_stack_option=LinearLayerStackOptions.BASE,
        forward_sampler_threshold=0.0,
        forward_sampler_filter_above_threshold=False,
        forward_sampler_num_topk_samples=0,
        forward_sampler_normalize_probabilities_flag=False,
        forward_sampler_switch_loss_weight=0.0,
        forward_sampler_zero_centred_loss_weight=0.0,
        forward_sampler_mutual_information_loss_weight=0.0,
        forward_sampler_coefficient_of_variation_loss_weight=0.0,
        forward_experts_layer_stack_option=LinearLayerStackOptions.BASE,
        forward_experts_compute_expert_mixture_flag=True,
        forward_experts_weighting_position_option=ExpertWeightingPositionOptions.BEFORE_EXPERTS,
        forward_experts_init_sampler_model_flag=False,
        forward_experts_weighted_parameters_flag=False,
        forward_experts_layer_role_option=LayerRoleOptions.GENERAL,
        forward_experts_bias_flag: bool = False,
        forward_experts_generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        forward_experts_diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        forward_experts_bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        forward_experts_memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        forward_experts_memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        forward_experts_memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
        forward_experts_stack_num_layers=2,
        forward_experts_stack_activation=ActivationOptions.RELU,
        forward_experts_stack_residual_flag=False,
        forward_experts_stack_dropout_probability=0.0,
        stack_bias_flag=False,
        stack_num_layers: int = 2,
        stack_hidden_dim: int = 0,
        stack_activation: ActivationOptions = ActivationOptions.RELU,
        stack_residual_flag: bool = False,
        stack_dropout_probability: float = 0.0,
    ) -> "TransformerConfig":
        _hidden_dim = max(input_dim, output_dim)
        stack_hidden_dim = stack_hidden_dim if stack_hidden_dim > 0 else _hidden_dim

        attention_config = MultiHeadAttentionPresets.multi_head_attention_preset(
            input_dim=input_dim,
            hidden_dim=hidden_dim,
            output_dim=output_dim,
            model_type=attention_model_type,
            batch_size=attention_batch_size,
            num_heads=attention_num_heads,
            embedding_dim=embedding_dim,
            query_key_projection_dim=embedding_dim,
            value_projection_dim=embedding_dim,
            target_sequence_length=attention_target_sequence_length,
            source_sequence_length=attention_source_sequence_length,
            target_dtype=attention_target_dtype,
            is_self_attention_projector_flag=True,
            dropout_probability=attention_dropout_probability,
            key_value_bias_flag=attention_key_value_bias_flag,
            zero_attention_flag=attention_zero_attention_flag,
            causal_attention_mask_flag=attention_causal_attention_mask_flag,
            add_key_value_bias_flag=attention_add_key_value_bias_flag,
            average_attention_weights_flag=attention_average_attention_weights_flag,
            return_attention_weights_flag=attention_return_attention_weights_flag,
            adaptive_stack_num_layers=attention_adaptive_stack_num_layers,
            adaptive_stack_activation=attention_adaptive_stack_activation,
            adaptive_stack_residual_flag=attention_adaptive_stack_residual_flag,
            adaptive_stack_dropout_probability=attention_adaptive_stack_dropout_probability,
            projector_adaptive_weight_option=attention_adaptive_weight_option,
            projector_adaptive_bias_option=attention_adaptive_bias_option,
            projector_adaptive_mixture_top_k=attention_adaptive_mixture_top_k,
            projector_adaptive_mixture_num_experts=attention_adaptive_mixture_num_experts,
            projector_adaptive_mixture_weighted_parameters_flag=attention_adaptive_mixture_weighted_parameters_flag,
            projector_adaptive_mixture_clip_parameter_option=attention_adaptive_mixture_clip_parameter_option,
            projector_adaptive_mixture_clip_range=attention_adaptive_mixture_clip_range,
            projector_adaptive_init_sampler_model_option=attention_adaptive_init_sampler_model_option,
            projector_adaptive_time_tracker_flag=attention_adaptive_time_tracker_flag,
            projector_adaptive_behaviour_generator_depth=attention_adaptive_behaviour_generator_depth,
            projector_adaptive_behaviour_diagonal_option=attention_adaptive_behaviour_diagonal_option,
            projector_adaptive_behaviour_bias_option=attention_adaptive_behaviour_bias_option,
            projector_adaptive_behaviour_memory_option=attention_adaptive_behaviour_memory_option,
            projector_adaptive_behaviour_memory_size_option=attention_adaptive_behaviour_memory_size_option,
            projector_adaptive_behaviour_memory_position_option=attention_adaptive_behaviour_memory_position_option,
            projector_router_bias_flag=attention_router_bias_flag,
            projector_router_noisy_topk_flag=attention_router_noisy_topk_flag,
            projector_router_generator_depth=attention_router_generator_depth,
            projector_router_diagonal_option=attention_router_diagonal_option,
            projector_router_bias_option=attention_router_bias_option,
            projector_router_memory_option=attention_router_memory_option,
            projector_router_memory_size_option=attention_router_memory_size_option,
            projector_router_memory_position_option=attention_router_memory_position_option,
            projector_router_layer_stack_option=attention_router_layer_stack_option,
            projector_sampler_threshold=attention_sampler_threshold,
            projector_sampler_filter_above_threshold=attention_sampler_filter_above_threshold,
            projector_sampler_num_topk_samples=attention_sampler_num_topk_samples,
            projector_sampler_normalize_probabilities_flag=attention_sampler_normalize_probabilities_flag,
            projector_sampler_switch_loss_weight=attention_sampler_switch_loss_weight,
            projector_sampler_zero_centred_loss_weight=attention_sampler_zero_centred_loss_weight,
            projector_sampler_mutual_information_loss_weight=attention_sampler_mutual_information_loss_weight,
            projector_sampler_coefficient_of_variation_loss_weight=attention_sampler_coefficient_of_variation_loss_weight,
            projector_experts_layer_stack_option=attention_experts_layer_stack_option,
            projector_experts_compute_expert_mixture_flag=attention_experts_compute_expert_mixture_flag,
            projector_experts_weighting_position_option=attention_experts_weighting_position_option,
            projector_experts_init_sampler_model_flag=attention_experts_init_sampler_model_flag,
            projector_experts_weighted_parameters_flag=attention_experts_weighted_parameters_flag,
            projector_experts_layer_role_option=attention_experts_layer_role_option,
            projector_experts_bias_flag=attention_experts_bias_flag,
            projector_experts_generator_depth=attention_experts_generator_depth,
            projector_experts_diagonal_option=attention_experts_diagonal_option,
            projector_experts_bias_option=attention_experts_bias_option,
            projector_experts_memory_option=attention_experts_memory_option,
            projector_experts_memory_size_option=attention_experts_memory_size_option,
            projector_experts_memory_position_option=attention_experts_memory_position_option,
            stack_bias_flag=stack_bias_flag,
            stack_num_layers=stack_num_layers,
            stack_hidden_dim=stack_hidden_dim,
            stack_activation=stack_activation,
            stack_residual_flag=stack_residual_flag,
            stack_dropout_probability=stack_dropout_probability,
        )

        feed_forward_config = TransformerPresets.transformer_feed_forward_preset(
            input_dim=input_dim,
            hidden_dim=embedding_dim,
            output_dim=output_dim,
            layer_stack_option=layer_stack_option,
            num_layers=num_layers,
            adaptive_stack_num_layers=forward_adaptive_stack_num_layers,
            adaptive_stack_activation=forward_adaptive_stack_activation,
            adaptive_stack_residual_flag=forward_adaptive_stack_residual_flag,
            adaptive_stack_dropout_probability=forward_adaptive_stack_dropout_probability,
            adaptive_weight_option=forward_adaptive_weight_option,
            adaptive_bias_option=forward_adaptive_bias_option,
            adaptive_mixture_top_k=forward_adaptive_mixture_top_k,
            adaptive_mixture_num_experts=forward_adaptive_mixture_num_experts,
            adaptive_mixture_weighted_parameters_flag=forward_adaptive_mixture_weighted_parameters_flag,
            adaptive_mixture_clip_parameter_option=forward_adaptive_mixture_clip_parameter_option,
            adaptive_mixture_clip_range=forward_adaptive_mixture_clip_range,
            adaptive_init_sampler_model_option=forward_adaptive_init_sampler_model_option,
            adaptive_time_tracker_flag=forward_adaptive_time_tracker_flag,
            adaptive_behaviour_generator_depth=forward_adaptive_behaviour_generator_depth,
            adaptive_behaviour_diagonal_option=forward_adaptive_behaviour_diagonal_option,
            adaptive_behaviour_bias_option=forward_adaptive_behaviour_bias_option,
            adaptive_behaviour_memory_option=forward_adaptive_behaviour_memory_option,
            adaptive_behaviour_memory_size_option=forward_adaptive_behaviour_memory_size_option,
            adaptive_behaviour_memory_position_option=forward_adaptive_behaviour_memory_position_option,
            router_bias_flag=forward_router_bias_flag,
            router_noisy_topk_flag=forward_router_noisy_topk_flag,
            router_generator_depth=forward_router_generator_depth,
            router_diagonal_option=forward_router_diagonal_option,
            router_bias_option=forward_router_bias_option,
            router_memory_option=forward_router_memory_option,
            router_memory_size_option=forward_router_memory_size_option,
            router_memory_position_option=forward_router_memory_position_option,
            router_layer_stack_option=forward_router_layer_stack_option,
            sampler_threshold=forward_sampler_threshold,
            sampler_filter_above_threshold=forward_sampler_filter_above_threshold,
            sampler_num_topk_samples=forward_sampler_num_topk_samples,
            sampler_normalize_probabilities_flag=forward_sampler_normalize_probabilities_flag,
            sampler_switch_loss_weight=forward_sampler_switch_loss_weight,
            sampler_zero_centred_loss_weight=forward_sampler_zero_centred_loss_weight,
            sampler_mutual_information_loss_weight=forward_sampler_mutual_information_loss_weight,
            sampler_coefficient_of_variation_loss_weight=forward_sampler_coefficient_of_variation_loss_weight,
            experts_layer_stack_option=forward_experts_layer_stack_option,
            experts_compute_expert_mixture_flag=forward_experts_compute_expert_mixture_flag,
            experts_weighting_position_option=forward_experts_weighting_position_option,
            experts_init_sampler_model_flag=forward_experts_init_sampler_model_flag,
            experts_weighted_parameters_flag=forward_experts_weighted_parameters_flag,
            experts_layer_role_option=forward_experts_layer_role_option,
            experts_bias_flag=forward_experts_bias_flag,
            experts_generator_depth=forward_experts_generator_depth,
            experts_diagonal_option=forward_experts_diagonal_option,
            experts_bias_option=forward_experts_bias_option,
            experts_memory_option=forward_experts_memory_option,
            experts_memory_size_option=forward_experts_memory_size_option,
            experts_memory_position_option=forward_experts_memory_position_option,
            experts_stack_num_layers=forward_experts_stack_num_layers,
            experts_stack_activation=forward_experts_stack_activation,
            experts_stack_residual_flag=forward_experts_stack_residual_flag,
            experts_stack_dropout_probability=forward_experts_stack_dropout_probability,
            stack_bias_flag=stack_bias_flag,
            stack_num_layers=stack_num_layers,
            stack_hidden_dim=stack_hidden_dim,
            stack_activation=stack_activation,
            stack_residual_flag=stack_residual_flag,
            stack_dropout_probability=stack_dropout_probability,
        )

        return TransformerConfig(
            num_layers=num_layers,
            source_sequence_length=source_sequence_length,
            target_sequence_length=target_sequence_length,
            layer_norm_dim=layer_norm_dim,
            causal_attention_mask_flag=causal_attention_mask_flag,
            attention_config=attention_config,
            feed_forward_config=feed_forward_config,
        )
