from Emperor.config import ModelConfig
from Emperor.base.layer import LayerStackConfig
from Emperor.linears.options import LinearLayerOptions
from Emperor.sampler.utils.routers import RouterConfig
from Emperor.linears.utils.layers import DynamicLinearLayerConfig
from Emperor.base.enums import ActivationOptions, LayerNormPositionOptions
from Emperor.linears.utils.enums import (
    DynamicBiasOptions,
    DynamicDepthOptions,
    DynamicDiagonalOptions,
    LinearMemoryOptions,
    LinearMemoryPositionOptions,
    LinearMemorySizeOptions,
)
from Emperor.sampler.utils.samplers import SamplerConfig


class SamplerConfigs:
    @staticmethod
    def router_preset(
        batch_size: int = 2,
        input_dim: int = 12,
        hidden_dim: int = 16,
        num_experts: int = 6,
        bias_flag: bool = True,
        noisy_topk_flag: bool = False,
        residual_flag: bool = False,
        dropout_probability: float = 0.0,
        num_layers: int = 2,
        activation: ActivationOptions = ActivationOptions.RELU,
        model_type: LinearLayerOptions = LinearLayerOptions.BASE,
        bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
    ) -> "ModelConfig":
        return ModelConfig(
            batch_size=batch_size,
            input_dim=input_dim,
            output_dim=num_experts,
            router_model_config=RouterConfig(
                model_type=model_type,
                num_experts=num_experts,
                noisy_topk_flag=noisy_topk_flag,
                override_config=LayerStackConfig(
                    model_type=model_type,
                    input_dim=input_dim,
                    hidden_dim=hidden_dim,
                    output_dim=num_experts,
                    num_layers=num_layers,
                    activation=activation,
                    layer_norm_position=LayerNormPositionOptions.NONE,
                    residual_flag=residual_flag,
                    adaptive_computation_flag=False,
                    dropout_probability=dropout_probability,
                    override_config=DynamicLinearLayerConfig(
                        input_dim=input_dim,
                        output_dim=hidden_dim,
                        bias_flag=bias_flag,
                        data_monitor=None,
                        parameter_monitor=None,
                        generator_depth=generator_depth,
                        diagonal_option=diagonal_option,
                        bias_option=bias_option,
                        memory_option=memory_option,
                        memory_size_option=memory_size_option,
                        memory_position_option=memory_position_option,
                        override_config=LayerStackConfig(
                            model_type=LinearLayerOptions.BASE,
                            input_dim=input_dim,
                            hidden_dim=hidden_dim,
                            output_dim=hidden_dim,
                            num_layers=num_layers,
                            activation=activation,
                            layer_norm_position=LayerNormPositionOptions.NONE,
                            residual_flag=residual_flag,
                            adaptive_computation_flag=False,
                            dropout_probability=dropout_probability,
                            override_config=DynamicLinearLayerConfig(
                                input_dim=input_dim,
                                output_dim=hidden_dim,
                                bias_flag=bias_flag,
                                generator_depth=generator_depth,
                                data_monitor=None,
                                parameter_monitor=None,
                            ),
                        ),
                    ),
                ),
            ),
        )

    @staticmethod
    def sampler_preset(
        batch_size: int = 2,
        input_dim: int = 12,
        hidden_dim: int = 16,
        num_experts: int = 6,
        bias_flag: bool = True,
        noisy_topk_flag: bool = False,
        residual_flag: bool = False,
        dropout_probability: float = 0.0,
        num_layers: int = 2,
        activation: ActivationOptions = ActivationOptions.RELU,
        model_type: LinearLayerOptions = LinearLayerOptions.BASE,
        bias_option: DynamicBiasOptions = DynamicBiasOptions.DISABLED,
        memory_option: LinearMemoryOptions = LinearMemoryOptions.DISABLED,
        generator_depth: DynamicDepthOptions = DynamicDepthOptions.DISABLED,
        diagonal_option: DynamicDiagonalOptions = DynamicDiagonalOptions.DISABLED,
        memory_size_option: LinearMemorySizeOptions = LinearMemorySizeOptions.DISABLED,
        memory_position_option: LinearMemoryPositionOptions = LinearMemoryPositionOptions.BEFORE_AFFINE,
    ) -> "ModelConfig":
        return ModelConfig(
            batch_size=batch_size,
            input_dim=input_dim,
            output_dim=num_experts,
            sampler_model_config=SamplerConfig(
                top_k=SAMPLER_TOP_K,
                threshold=SAMPLER_THRESHOLD,
                filter_above_threshold=SAMPLER_FILTER_THRESHOLD,
                num_topk_samples=SAMPLER_NUM_TOPK_SAMPLES,
                normalize_probabilities_flag=SAMPLER_NORMALIZE_PROBABILITIES_FLAG,
                noisy_topk_flag=SAMPLER_NOISY_TOPK_FLAG,
                num_experts=num_experts,
                coefficient_of_variation_loss_weight=SAMPLER_COEFFICIENT_OF_VARIATION_WEIGHT,
                switch_loss_weight=SAMPLER_SWITCH_WEIGHT,
                zero_centred_loss_weight=SAMPLER_ZERO_CENTRED_WEIGHT,
                mutual_information_loss_weight=SAMPLER_MUTUAL_INFORMATION_WEIGHT,
                override_config=RouterConfig(
                    model_type=model_type,
                    num_experts=num_experts,
                    noisy_topk_flag=noisy_topk_flag,
                    override_config=LayerStackConfig(
                        model_type=model_type,
                        input_dim=input_dim,
                        hidden_dim=hidden_dim,
                        output_dim=num_experts,
                        num_layers=num_layers,
                        activation=activation,
                        layer_norm_position=LayerNormPositionOptions.NONE,
                        residual_flag=residual_flag,
                        adaptive_computation_flag=False,
                        dropout_probability=dropout_probability,
                        override_config=DynamicLinearLayerConfig(
                            input_dim=input_dim,
                            output_dim=hidden_dim,
                            bias_flag=bias_flag,
                            data_monitor=None,
                            parameter_monitor=None,
                            generator_depth=generator_depth,
                            diagonal_option=diagonal_option,
                            bias_option=bias_option,
                            memory_option=memory_option,
                            memory_size_option=memory_size_option,
                            memory_position_option=memory_position_option,
                            override_config=LayerStackConfig(
                                model_type=LinearLayerOptions.BASE,
                                input_dim=input_dim,
                                hidden_dim=hidden_dim,
                                output_dim=hidden_dim,
                                num_layers=num_layers,
                                activation=activation,
                                layer_norm_position=LayerNormPositionOptions.NONE,
                                residual_flag=residual_flag,
                                adaptive_computation_flag=False,
                                dropout_probability=dropout_probability,
                                override_config=DynamicLinearLayerConfig(
                                    input_dim=input_dim,
                                    output_dim=hidden_dim,
                                    bias_flag=bias_flag,
                                    generator_depth=generator_depth,
                                    data_monitor=None,
                                    parameter_monitor=None,
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        )
