from torch import Tensor
from dataclasses import dataclass, field
from Emperor.base.layer import LayerStackConfig
from Emperor.base.utils import Module, ConfigBase
from Emperor.linears.options import LinearLayerStackOptions

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from Emperor.config import ModelConfig


@dataclass
class RouterConfig(ConfigBase):
    layer_stack_option: LinearLayerStackOptions = field(
        default=LinearLayerStackOptions.BASE,
        metadata={"help": "Number of layers added to the router"},
    )
    num_experts: int = field(
        default=0,
        metadata={"help": "Router output dimension"},
    )
    noisy_topk_flag: bool = field(
        default=False,
        metadata={
            "help": "When `True` noise will be added to the logit scores generated by the router. Note the size of the generated logits will be `num_experts` * 2"
        },
    )


class RouterModel(Module):
    def __init__(
        self,
        cfg: "ModelConfig",
        overrides: "RouterConfig | None" = None,
    ) -> None:
        super().__init__()
        config = getattr(cfg, "router_model_config", cfg)
        self.cfg: "RouterConfig" = self._overwrite_config(config, overrides)
        self.main_cfg = self._resolve_main_config(self.cfg, cfg)

        self.layer_stack_option = self.cfg.layer_stack_option.value
        self.num_experts = self.cfg.num_experts
        self.noisy_topk_flag = self.cfg.noisy_topk_flag

        self.num_experts = (
            2 * self.num_experts if self.noisy_topk_flag else self.num_experts
        )
        self.__assert_input_requirements()
        model_overrides = LayerStackConfig(output_dim=self.num_experts)
        self.model = self.layer_stack_option(
            self.main_cfg, model_overrides
        ).build_model()

    def __assert_input_requirements(self):
        assert self.num_experts > 0, (
            "The number of experts (num_experts) must be greater than zero."
        )

    def compute_logit_scores(self, input_batch: Tensor) -> Tensor:
        return self.model(input_batch)
