from torch import Tensor
from dataclasses import dataclass, field
from emperor.base.layer import LayerStackConfig
from emperor.base.utils import Module, ConfigBase

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from emperor.linears.options import LinearLayerStackOptions


@dataclass
class RouterConfig(ConfigBase):
    input_dim: int | None = field(
        default=None,
        metadata={"help": "Number of layers added to the router"},
    )
    layer_stack_option: "LinearLayerStackOptions | None" = field(
        default=None,
        metadata={"help": "Number of layers added to the router"},
    )
    num_experts: int | None = field(
        default=None,
        metadata={"help": "Router output dimension"},
    )
    noisy_topk_flag: bool | None = field(
        default=None,
        metadata={
            "help": "When `True` noise will be added to the logit scores generated by the router. Note the size of the generated logits will be `num_experts` * 2"
        },
    )


class RouterModel(Module):
    def __init__(
        self,
        cfg: "RouterConfig",
        overrides: "RouterConfig | None" = None,
    ) -> None:
        super().__init__()
        config = getattr(cfg, "router_model_config", cfg)
        self.cfg: "RouterConfig" = self._overwrite_config(config, overrides)
        self.main_cfg = self._resolve_main_config(self.cfg, cfg)

        self.input_dim = self.cfg.input_dim
        self.layer_stack_option = self.cfg.layer_stack_option.value
        self.num_experts = self.cfg.num_experts
        self.noisy_topk_flag = self.cfg.noisy_topk_flag

        self.num_experts = (
            2 * self.num_experts if self.noisy_topk_flag else self.num_experts
        )
        self.__assert_input_requirements()
        self.model = self.__create_router_model()

    def __create_router_model(self):
        overrides = LayerStackConfig(
            input_dim=self.input_dim, output_dim=self.num_experts
        )
        return self.layer_stack_option(self.main_cfg, overrides).build_model()

    def __assert_input_requirements(self):
        assert self.num_experts > 0, (
            "The number of experts (num_experts) must be greater than zero."
        )

    def compute_logit_scores(self, input_batch: Tensor) -> Tensor:
        return self.model(input_batch)
