"""Generated package-owned Runtime Defaults presentation metadata."""

from model_runtime.packages.configuration_metadata import (
    RuntimeDefaultsSection,
)

# Generated by tools/generate_model_package_inspection_metadata.py.
# Do not edit by hand; run the generator after intentional metadata changes.
# fmt: off
CONFIGURATION_METADATA_SECTIONS: tuple[RuntimeDefaultsSection, ...] = (
    RuntimeDefaultsSection(('Trainer',), (
        ('TRAINER_ACCELERATOR', 15, (15,)),
        ('TRAINER_DEVICES', 16, (16,)),
        ('TRAINER_GRADIENT_CLIP_VAL', 17, (17,)),
        ('TRAINER_GRADIENT_CLIP_ALGORITHM', 18, (18,)),
        ('TRAINER_ACCUMULATE_GRAD_BATCHES', 19, (19,)),
        ('TRAINER_PRECISION', 20, (20,)),
        ('TRAINER_DETERMINISTIC', 21, (21,)),
        ('TRAINER_BENCHMARK', 22, (22,)),
        ('TRAINER_MAX_STEPS', 23, (23,)),
        ('TRAINER_MAX_TIME', 24, (24,)),
        ('TRAINER_VAL_CHECK_INTERVAL', 25, (25,)),
        ('TRAINER_LIMIT_TRAIN_BATCHES', 26, (26,)),
        ('TRAINER_LIMIT_VAL_BATCHES', 27, (27,)),
        ('TRAINER_OVERFIT_BATCHES', 28, (28,)),
        ('TRAINER_NUM_SANITY_VAL_STEPS', 29, (29,)),
        ('TRAINER_LOG_EVERY_N_STEPS', 30, (30,)),
        ('TRAINER_ENABLE_PROGRESS_BAR', 31, (31,)),
        ('TRAINER_ENABLE_CHECKPOINTING', 32, (32,)),
        ('TRAINER_ENABLE_MODEL_SUMMARY', 33, (33,)),
        ('TRAINER_PROFILER', 34, (34,)),
        ('MONITOR_LOG_EVERY_N_STEPS', 35, (35,)),
    )),
    RuntimeDefaultsSection(('Run',), (
        ('DATA_NUM_WORKERS', 38, (38,)),
        ('RUN_TEST_AFTER_FIT', 39, (39,)),
        ('SEED', 40, (40,)),
    )),
    RuntimeDefaultsSection(('Callback',), (
        ('CALLBACK_EARLY_STOPPING_PATIENCE', 43, (43,)),
        ('CALLBACK_EARLY_STOPPING_METRIC', 44, (44,)),
        ('CALLBACK_EARLY_STOPPING_MIN_DELTA', 45, (45,)),
        ('CALLBACK_EARLY_STOPPING_STRICT', 46, (46,)),
        ('CALLBACK_EARLY_STOPPING_CHECK_FINITE', 47, (47,)),
        ('CALLBACK_CHECKPOINT_FLAG', 48, (48,)),
    )),
    RuntimeDefaultsSection(('Global',), (
        ('BATCH_SIZE', 51, (51,)),
        ('LEARNING_RATE', 52, (52,)),
        ('NUM_EPOCHS', 53, (53,)),
    )),
    RuntimeDefaultsSection(('Model',), (
        ('INPUT_DIM', 56, (56,)),
        ('HIDDEN_DIM', 57, (57,)),
        ('RUNTIME_VALUE_CONSTRAINTS', 58, (58,)),
        ('OUTPUT_DIM', 59, (59,)),
    )),
    RuntimeDefaultsSection(('Layer Stack Options',), (
        ('STACK_NUM_LAYERS', 63, (63,)),
        ('STACK_ACTIVATION', 64, (64,)),
        ('STACK_DROPOUT_PROBABILITY', 65, (65,)),
    )),
    RuntimeDefaultsSection(('Residual Options',), (
        ('STACK_RESIDUAL_CONNECTION_OPTION', 71, (71,)),
        ('STACK_RESIDUAL_MODEL_FLAG', 72, (72,)),
    )),
    RuntimeDefaultsSection(('Residual Options', 'Residual Stack Options'), (
        ('RESIDUAL_STACK_INDEPENDENT_FLAG', 75, (75,)),
        ('RESIDUAL_STACK_HIDDEN_DIM', 76, (76,)),
        ('RESIDUAL_STACK_LAYER_NORM_POSITION', 77, (77,)),
        ('RESIDUAL_STACK_NUM_LAYERS', 78, (78,)),
        ('RESIDUAL_STACK_ACTIVATION', 79, (79,)),
        ('RESIDUAL_STACK_RESIDUAL_CONNECTION_OPTION', 80, (80,)),
        ('RESIDUAL_STACK_RESIDUAL_MODEL_FLAG', 81, (81,)),
        ('RESIDUAL_STACK_DROPOUT_PROBABILITY', 82, (82,)),
        ('RESIDUAL_STACK_LAST_LAYER_BIAS_OPTION', 83, (83,)),
        ('RESIDUAL_STACK_APPLY_OUTPUT_POSTPROCESSING_FLAG', 84, (84,)),
        ('RESIDUAL_STACK_BIAS_FLAG', 85, (85,)),
    )),
    RuntimeDefaultsSection(('Parametric Generator Mixture Options',), (
        ('ADAPTIVE_MIXTURE_TOP_K', 88, (88,)),
        ('ADAPTIVE_MIXTURE_NUM_EXPERTS', 89, (89,)),
        ('ADAPTIVE_MIXTURE_WEIGHTED_PARAMETERS_FLAG', 90, (90,)),
        ('ADAPTIVE_MIXTURE_CLIP_PARAMETER_OPTION', 91, (91,)),
        ('ADAPTIVE_MIXTURE_CLIP_RANGE', 94, (94,)),
        ('ADAPTIVE_BIAS_OPTION', 95, (95,)),
    )),
    RuntimeDefaultsSection(('Sampler Model Options',), (
        ('SAMPLER_THRESHOLD', 98, (98,)),
        ('SAMPLER_FILTER_ABOVE_THRESHOLD', 99, (99,)),
        ('SAMPLER_NUM_TOPK_SAMPLES', 100, (100,)),
        ('SAMPLER_NORMALIZE_PROBABILITIES_FLAG', 101, (101,)),
        ('SAMPLER_NOISY_TOPK_FLAG', 102, (102,)),
        ('SAMPLER_COEFFICIENT_OF_VARIATION_LOSS_WEIGHT', 103, (103,)),
        ('SAMPLER_SWITCH_LOSS_WEIGHT', 104, (104,)),
        ('SAMPLER_ZERO_CENTRED_LOSS_WEIGHT', 105, (105,)),
        ('SAMPLER_MUTUAL_INFORMATION_LOSS_WEIGHT', 106, (106,)),
    )),
    RuntimeDefaultsSection(('Generator Expert Stack Options',), (
        ('GENERATOR_STACK_NUM_LAYERS', 109, (109,)),
        ('GENERATOR_STACK_HIDDEN_DIM', 110, (110,)),
        ('GENERATOR_STACK_ACTIVATION', 111, (111,)),
        ('GENERATOR_STACK_DROPOUT_PROBABILITY', 112, (112,)),
    )),
)

SEARCH_METADATA_SECTIONS: tuple[RuntimeDefaultsSection, ...] = (
    RuntimeDefaultsSection((), (
        ('SEARCH_SPACE_LEARNING_RATE', 5, (5,)),
        ('SEARCH_SPACE_HIDDEN_DIM', 7, (7,)),
        ('SEARCH_SPACE_STACK_DROPOUT_PROBABILITY', 9, (9,)),
        ('SEARCH_SPACE_STACK_ACTIVATION', 11, (11,)),
        ('SEARCH_SPACE_ADAPTIVE_MIXTURE_NUM_EXPERTS', 16, (16,)),
        ('SEARCH_SPACE_ADAPTIVE_BIAS_OPTION', 18, (18,)),
        ('SEARCH_SPACE_ADAPTIVE_MIXTURE_CLIP_PARAMETER_OPTION', 20, (20,)),
    )),
)
# fmt: on

__all__ = ["CONFIGURATION_METADATA_SECTIONS", "SEARCH_METADATA_SECTIONS"]
