"""Pydantic request/response schemas that define the viewer HTTP contract.

These shapes are validated on the frontend by the Zod schemas in
``viewer/frontend/src/lib/api.ts``; keep the two in sync.
"""

from __future__ import annotations

from viewer.backend.schemas._base import (
    ApiResponseModel,
    ConfigOverrides,
    ConfigValue,
    JsonObject,
    JsonValue,
)
from viewer.backend.schemas._capabilities import CapabilitiesResponse
from viewer.backend.schemas._config_snapshots import (
    ConfigSnapshotCreateRequest,
    ConfigSnapshotRenameRequest,
    ConfigSnapshotResponse,
    ConfigSnapshotsResponse,
)
from viewer.backend.schemas._health import HealthResponse
from viewer.backend.schemas._inspection import (
    GraphConfigFieldResponse,
    GraphConfigResponse,
    GraphEdgeResponse,
    GraphNodeResponse,
    InspectRequest,
    InspectResponse,
)
from viewer.backend.schemas._logs import (
    LogExperimentDeleteResponse,
    LogExperimentResponse,
    LogExperimentsResponse,
    LogRunDeleteAffectedValuesResponse,
    LogRunDeleteBlockerResponse,
    LogRunDeleteCandidateResponse,
    LogRunDeleteCountsResponse,
    LogRunDeleteFiltersRequest,
    LogRunDeletePlanResponse,
    LogRunDeleteResponse,
    LogRunResponse,
    LogRunsResponse,
    LogRunTagsResponse,
    LogScalarSeriesResponse,
    LogScalarsRequest,
    LogScalarsResponse,
    LogTagsRequest,
    LogTagsResponse,
)
from viewer.backend.schemas._models import (
    ConfigFieldResponse,
    ConfigSchemaResponse,
    DatasetResponse,
    DatasetsResponse,
    ModelsResponse,
    MonitorOptionResponse,
    MonitorsResponse,
    PresetResponse,
    PresetsResponse,
    SearchAxisResponse,
    SearchSpaceResponse,
)
from viewer.backend.schemas._monitor_data import (
    HistogramBucketResponse,
    HistogramResponse,
    ImageResponse,
    LogParameterStatusRequest,
    LogParameterStatusResponse,
    MonitorDataResponse,
    ParameterChannelStatusResponse,
    ParameterNodeStatusResponse,
    ParameterStatusResponse,
    ScalarPointResponse,
    ScalarSeriesResponse,
)
from viewer.backend.schemas._training import (
    SubmittedTrainingRunChangeRequest,
    SubmittedTrainingRunPlanRequest,
    SubmittedTrainingRunPlanSummaryRequest,
    SubmittedTrainingRunRequest,
    TrainingJobCreateRequest,
    TrainingJobResponse,
    TrainingResultLinkResponse,
    TrainingRunChangeResponse,
    TrainingRunPlanCreateRequest,
    TrainingRunPlanResponse,
    TrainingRunPlanSummaryResponse,
    TrainingRunResponse,
    TrainingSearchRequest,
    TrainingSearchResponse,
)

__all__ = [
    "ConfigValue",
    "ConfigOverrides",
    "JsonValue",
    "JsonObject",
    "ApiResponseModel",
    "CapabilitiesResponse",
    "ConfigSnapshotResponse",
    "ConfigSnapshotsResponse",
    "ConfigSnapshotCreateRequest",
    "ConfigSnapshotRenameRequest",
    "HealthResponse",
    "ModelsResponse",
    "PresetResponse",
    "PresetsResponse",
    "DatasetResponse",
    "DatasetsResponse",
    "MonitorOptionResponse",
    "MonitorsResponse",
    "ConfigFieldResponse",
    "ConfigSchemaResponse",
    "SearchAxisResponse",
    "SearchSpaceResponse",
    "GraphConfigFieldResponse",
    "GraphConfigResponse",
    "GraphNodeResponse",
    "GraphEdgeResponse",
    "InspectRequest",
    "InspectResponse",
    "TrainingJobCreateRequest",
    "TrainingRunPlanCreateRequest",
    "TrainingSearchResponse",
    "TrainingSearchRequest",
    "TrainingRunChangeResponse",
    "SubmittedTrainingRunChangeRequest",
    "TrainingRunResponse",
    "SubmittedTrainingRunRequest",
    "TrainingRunPlanSummaryResponse",
    "SubmittedTrainingRunPlanSummaryRequest",
    "TrainingRunPlanResponse",
    "SubmittedTrainingRunPlanRequest",
    "TrainingResultLinkResponse",
    "TrainingJobResponse",
    "ScalarPointResponse",
    "ScalarSeriesResponse",
    "HistogramBucketResponse",
    "HistogramResponse",
    "ImageResponse",
    "MonitorDataResponse",
    "ParameterChannelStatusResponse",
    "ParameterNodeStatusResponse",
    "ParameterStatusResponse",
    "LogParameterStatusRequest",
    "LogParameterStatusResponse",
    "LogRunResponse",
    "LogRunsResponse",
    "LogExperimentResponse",
    "LogExperimentsResponse",
    "LogExperimentDeleteResponse",
    "LogRunDeleteFiltersRequest",
    "LogRunDeleteCandidateResponse",
    "LogRunDeleteAffectedValuesResponse",
    "LogRunDeleteCountsResponse",
    "LogRunDeleteBlockerResponse",
    "LogRunDeletePlanResponse",
    "LogRunDeleteResponse",
    "LogTagsRequest",
    "LogRunTagsResponse",
    "LogTagsResponse",
    "LogScalarsRequest",
    "LogScalarSeriesResponse",
    "LogScalarsResponse",
]
