"""Shared request limits for the Viewer API contract."""

from __future__ import annotations

MAX_LOG_REQUEST_RUN_IDS = 50
MAX_LOG_DELETE_FILTER_VALUES = 50
MAX_LOG_SCALAR_TAGS = 50
MAX_LOG_MEDIA_TAGS = 20
DEFAULT_LOG_SCALAR_MAX_POINTS = 500
MAX_LOG_SCALAR_MAX_POINTS = 2000
