from torch import Tensor
import torch.nn as nn
from dataclasses import dataclass, field
from Emperor.base.utils import LayerBlock, randn, matmul
from torch.nn.parameter import Parameter
from Emperor.base.utils import Module, DataClassBase
from torch.nn import Linear, Sequential

from typing import TYPE_CHECKING

from Emperor.components.parameter_generators.utils.linears import (
    DynamicDiagonalLinearLayer,
    LinearLayer,
    LinearLayerConfig,
)

if TYPE_CHECKING:
    from Emperor.config import ModelConfig


@dataclass
class RouterConfig(DataClassBase):
    input_dim: int | None = field(
        default=None,
        metadata={"help": "Router input dimension"},
    )
    hidden_dim: int | None = field(
        default=None,
        metadata={"help": "Router hidden dimension"},
    )
    output_dim: int | None = field(
        default=None,
        metadata={"help": "Router output dimension"},
    )
    residual_flag: bool | None = field(
        default=False,
        metadata={
            "help": "If true when you have 3 or more layers a residual connection is added between layers"
        },
    )
    noisy_topk_flag: int | None = field(
        default=None,
        metadata={
            "help": "When `True` noise will be added to the logit scores generated by the router. Note the size of the generated logits will be `output_dim` * 2"
        },
    )
    activation: nn.Module | None = field(
        default=None,
        metadata={"help": "Router activation function."},
    )
    num_layers: int | None = field(
        default=None,
        metadata={"help": "Number of layers added to the router"},
    )
    diagonal_linear_model_flag: bool | None = field(
        default=None,
        metadata={
            "help": "When `True` a `DynamicDiagonalLinearLayer` will be used instead of `nn.Linear`"
        },
    )


class RouterModel(Module):
    def __init__(
        self,
        cfg: "RouterConfig | ModelConfig",
        overrides: "RouterConfig | None" = None,
    ) -> None:
        super().__init__()
        config = getattr(cfg, "router_model_config", cfg)
        self.cfg: "RouterConfig" = self._overwrite_config(config, overrides)

        self.input_dim = self.cfg.input_dim
        self.hidden_dim = self.cfg.hidden_dim
        self.output_dim = self.cfg.output_dim
        self.residual_flag = self.cfg.residual_flag
        self.noisy_topk_flag = self.cfg.noisy_topk_flag
        self.activation = self.cfg.activation
        self.num_layers = self.cfg.num_layers
        self.diagonal_linear_model_flag = self.cfg.diagonal_linear_model_flag

        self.router_output_dim = (
            2 * self.output_dim if self.noisy_topk_flag else self.output_dim
        )

        self.compute_weight_flag = True
        self.__assert_input_requirements()
        self._build_models()

    def __assert_input_requirements(self):
        assert self.input_dim > 0, "input_dim must be a positive integer"
        assert self.hidden_dim > 0, "hidden_dim must be a positive integer"
        assert self.output_dim > 0, "output_dim must be a positive integer"
        assert isinstance(self.residual_flag, bool), "residual_flag must be a boolean"
        assert isinstance(self.noisy_topk_flag, bool), (
            "noisy_topk_flag must be a boolean"
        )
        assert self.num_layers > 0, "num_layers must be a positive integer"
        assert isinstance(self.diagonal_linear_model_flag, bool), (
            "diagonal_linear_model_flag must be a boolean"
        )

        self._valudate_fields(self.cfg, RouterConfig)
        assert self.num_layers > 0, (
            f"Expected `num_layers` in `RouterModel` to be at least one, received {type(self.num_layers)}"
        )

    def __build_model(self) -> Linear | Sequential:
        router_layers = []

        layer_adjustment = self.__add_initial_layer(router_layers)
        self.__add_hidden_layers(router_layers, layer_adjustment)
        self.__add_output_layer(router_layers)

        model = Sequential(*router_layers)
        self._initialize_parameters(model)
        return model

    def __add_initial_layer(self, router_layers: list) -> int:
        if self.input_dim != self.hidden_dim and self.num_layers > 1:
            layer = self.__create_router_layer(self.input_dim, self.hidden_dim, False)
            router_layers.append(layer)
            return 2
        return 1

    def __add_hidden_layers(self, router_layers: list, layer_adjustment: int) -> None:
        for _ in range(self.num_layers - layer_adjustment):
            layer = self.__create_router_layer(self.hidden_dim, self.hidden_dim)
            router_layers.append(layer)

    def __add_output_layer(self, router_layers: list) -> None:
        layer_input = self.hidden_dim if self.num_layers > 1 else self.input_dim
        router_layers.append(Linear(layer_input, self.router_output_dim, bias=False))

    def __create_router_layer(
        self,
        input_dim: int,
        output_dim: int,
        residual_connection_flag: bool = True,
    ):
        return LayerBlock(
            model=self.__create_router_layer_model(
                input_dim,
                output_dim,
            ),
            activation_function_module=self.activation,
            layer_norm_module=nn.LayerNorm(output_dim),
            residual_connection_flag=residual_connection_flag,
        )

    def __create_router_layer_model(
        self,
        input_dim: int,
        output_dim: int,
    ) -> DynamicDiagonalLinearLayer | LinearLayer:
        cfg = LinearLayerConfig(
            input_dim=input_dim,
            output_dim=output_dim,
            bias_flag=True,
            anti_diagonal_flag=True,
        )
        if self.diagonal_linear_model_flag:
            return DynamicDiagonalLinearLayer(cfg)
        return LinearLayer(cfg)

    def _compute_bias_logit_scores(self, input_batch: Tensor) -> Tensor:
        return self.bias_router_model(input_batch)


class RouterLayer(Module):
    def __init__(
        self,
        hidden_dim: int,
        activation: Module,
        residual_flag: bool = False,
    ):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.activation = activation
        self.residual_flag = residual_flag
        self.layer = Linear(self.hidden_dim, self.hidden_dim)

    def forward(self, input_batch: Tensor):
        output = self.layer(input_batch)
        output = self.activation(output)
        if self.residual_flag:
            output = output + input_batch
        return output


class VectorChoiceRouterModel(RouterModel):
    def __init__(self, cfg: "RouterInputs | ModelConfig") -> None:
        super().__init__(cfg)

    def _build_models(self) -> None:
        self.weight_router_model = Parameter(
            randn(self.input_dim, self.input_dim, self.router_output_dim)
        )
        self._initialize_parameters(self.weight_router_model)
        self.bias_router_model = None
        if self.compute_bias_logits_flag:
            self.bias_router_model = Parameter(
                randn(self.output_dim, self.input_dim, self.router_output_dim)
            )
            self._initialize_parameters(self.bias_router_model)

    def _compute_weight_logit_scores(self, input_batch: Tensor) -> Tensor:
        return matmul(input_batch, self.weight_router_model)

    def _compute_bias_logit_scores(self, input_batch: Tensor) -> Tensor:
        return matmul(input_batch, self.bias_router_model)
