from dataclasses import dataclass, field, fields
import torch
from torch import Tensor


from Emperor.components.parameter_generators.utils.losses import AuxiliaryLosses
from Emperor.base.utils import Module, DataClassBase
from Emperor.base.utils import (
    sigmoid,
    randn_like,
    masked_fill,
    tensor,
    zeros,
    arange,
    expand_dims,
    concat,
    prod,
    device,
)

from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from Emperor.config import ModelConfig


@dataclass
class SamplerConfig(DataClassBase):
    top_k: int | None = field(
        default=None,
        metadata={
            "help": "Inidicates the top-k probabilities and indices to be selected from a distribution"
        },
    )
    threshold: float | None = field(
        default=None,
        metadata={
            "help": "If all elements in the softmax distribution are below the threshold, the current layer's computation remains unaffected. However, the token will be masked in the subsequent layer."
        },
    )
    dynamic_topk_threshold: float | None = field(
        default=None,
        metadata={
            "help": "Applies only to `SamplerFull`, used to generate a dynamic topk, all elements below this threshold will be turned off"
        },
    )
    num_topk_samples: int | None = field(
        default=None,
        metadata={
            "help": "From the top_k candidates, num_topk_samples will be substituted with randomly sampled elements from the distribution"
        },
    )
    normalize_probabilities_flag: bool | None = field(
        default=None,
        metadata={
            "help": "When `True` the sampled probabilities using `topk` or `threshold` are normalized to ensure probaiblities are added to 1"
        },
    )
    noisy_topk_flag: bool | None = field(
        default=None,
        metadata={
            "help": "When `True` noise will be added to the logit scores generated by the router"
        },
    )
    router_output_dim: int | None = field(
        default=None,
        metadata={"help": "Router output dimension"},
    )


class SamplerBase(Module):
    def __init__(
        self,
        cfg: "SamplerConfig | ModelConfig",
        overrides: "SamplerConfig | None" = None,
    ) -> None:
        super().__init__()

        config = getattr(cfg, "sampler_model_config", cfg)
        self.cfg: "SamplerConfig" = self._overwrite_config(config, overrides)

        self.top_k = self.cfg.top_k
        self.threshold = self.cfg.threshold
        self.noisy_topk_flag = self.cfg.noisy_topk_flag
        self.num_topk_samples = self.cfg.num_topk_samples
        self.dynamic_topk_threshold = self.cfg.dynamic_topk_threshold
        self.normalize_probabilities_flag = self.cfg.normalize_probabilities_flag
        self.router_output_dim = self.cfg.router_output_dim
        self.__validate_input_parameters()

        self.noise_epsilon = 1e-2
        self.auxiliary_losses = AuxiliaryLosses(self.cfg)

    def __validate_input_parameters(self):
        self._valudate_fields(self.cfg, SamplerConfig)

        assert self.top_k >= 0, f"top_k must be non-negative, got {self.top_k}"
        assert self.num_topk_samples <= self.top_k, (
            f"num_topk_samples ({self.num_topk_samples}) cannot exceed top_k ({self.top_k})"
        )
        assert 0.0 <= self.threshold <= 1.0, (
            f"threshold must be between 0.0 and 1.0 (inclusive), got {self.threshold}"
        )
        assert 0.0 <= self.dynamic_topk_threshold <= 1.0, (
            f"dynamic_topk_threshold must be between 0.0 and 1.0 (inclusive), got {self.dynamic_topk_threshold}"
        )

    def sample_probabilities_and_indices(
        self,
        logit_scores: Tensor,
        skip_mask: Tensor | None = None,
    ) -> tuple[Tensor, Tensor | None, Tensor | None]:
        full_probabilities, logits = self.__compute_masked_probabilities(
            logit_scores, skip_mask
        )
        probabilities, indices = self.__sample_probabilities_and_indices(
            full_probabilities
        )

        self._compute_loss(logits, full_probabilities, probabilities, indices)

        probabilities = self._normalize_probabilities(probabilities)

        skip_mask = self.__update_mask_given_threshold(full_probabilities, skip_mask)

        return probabilities, indices, skip_mask

    def __compute_masked_probabilities(
        self,
        logit_scores: Tensor,
        skip_mask: Tensor | None = None,
    ) -> tuple[Tensor, Tensor]:
        logits = self.__add_noise_to_logits(logit_scores)
        probabilities = torch.softmax(logits, dim=-1)
        return self.__apply_skip_mask(probabilities, logits, skip_mask)

    def __add_noise_to_logits(self, logit_scores_matrix: Tensor) -> Tensor:
        if not self.noisy_topk_flag:
            return logit_scores_matrix

        num_chuncks = 2
        logit_scores_matrix_chunk, raw_noise_std_matrix = logit_scores_matrix.chunk(
            num_chuncks, dim=-1
        )
        logit_scores_matrix = logit_scores_matrix_chunk

        if self.training:
            noise_std = sigmoid(raw_noise_std_matrix) + self.noise_epsilon
            noise = randn_like(logit_scores_matrix)
            # TODO: In the future maybe scale the noise by `raw_noise_std`
            # or scale `noise` by some `decaying_noise_amplifier` scalar
            noisy_logit_scores = logit_scores_matrix + noise * noise_std
            logit_scores_matrix = noisy_logit_scores

        return logit_scores_matrix

    def __apply_skip_mask(
        self,
        probabilities: Tensor,
        logits_scores: Tensor,
        skip_mask: Tensor | None = None,
    ) -> tuple[Tensor, Tensor]:
        if skip_mask is not None:
            mask = skip_mask == 0
            probabilities = masked_fill(probabilities, mask, 0)
            logits_scores = masked_fill(logits_scores, mask, 0)

        return probabilities, logits_scores

    def __update_mask_given_threshold(
        self,
        probabilities: Tensor,
        skip_mask: Tensor | None = None,
    ) -> Tensor | None:
        if skip_mask is None or self.threshold == 0.0:
            return skip_mask
        threshold_mask = probabilities < self.threshold
        mask_update = threshold_mask.all(dim=-1).unsqueeze(-1)
        return masked_fill(skip_mask, mask_update, 0)

    def __sample_probabilities_and_indices(
        self, probabilities_matrix: Tensor
    ) -> Tensor | tuple[Tensor, Tensor]:
        selected_probs, selected_indices = self._probability_sampling_strategy(
            probabilities_matrix
        )
        return selected_probs, selected_indices

    def _compute_loss(
        self,
        logits: Tensor,
        full_probabilities: Tensor,
        probabilities: Tensor,
        indices: Tensor,
    ) -> float:
        return 0.0

    def _probability_sampling_strategy(
        self, probabilities_matrix: Tensor
    ) -> Tensor | tuple[Tensor, None]:
        return probabilities_matrix, None

    def _normalize_probabilities(self, probabilities: Tensor) -> Tensor:
        if not self.normalize_probabilities_flag:
            return probabilities
        return probabilities / (torch.sum(probabilities, dim=-1, keepdim=True) + 1e-6)


class SamplerSparse(SamplerBase):
    def __init__(
        self,
        cfg: "SamplerConfig | ModelConfig",
        overrides: "SamplerConfig | None" = None,
    ) -> None:
        super().__init__(cfg, overrides)

    def _probability_sampling_strategy(
        self, probabilities_matrix: Tensor
    ) -> Tensor | tuple[Tensor, Tensor | None]:
        probability, indices = torch.max(probabilities_matrix, dim=-1)
        return probability, indices

    def _compute_loss(
        self,
        logits: Tensor,
        full_probabilities: Tensor,
        probabilities: Tensor,
        indices: Tensor,
        skip_mask: Optional[Tensor] = None,
    ) -> None:
        input_dim = prod(tensor(probabilities.shape))
        output_dim = self.router_output_dim
        gates_buffer = zeros(input_dim, output_dim).to(device)

        gates = gates_buffer.scatter(
            1,
            indices.view(-1, 1),
            probabilities.view(-1, 1),
        ).to(device)

        logits = logits.reshape(-1, output_dim)
        full_probabilities = full_probabilities.reshape(-1, output_dim)
        if skip_mask is not None:
            skip_mask = skip_mask.reshape(-1, output_dim)

        self.auxiliary_losses.update_accumulated_statistics(
            logits, full_probabilities, gates, skip_mask
        )


class SamplerTopk(SamplerBase):
    def __init__(
        self,
        cfg: "SamplerConfig | ModelConfig",
        overrides: "SamplerConfig | None" = None,
    ) -> None:
        super().__init__(cfg, overrides)

    def _probability_sampling_strategy(
        self, probabilities_matrix: Tensor
    ) -> Tensor | tuple[Tensor, Tensor]:
        probabilities, indices = self.__sample_topk_probabilities(probabilities_matrix)

        return probabilities, indices

    def __sample_topk_probabilities(
        self, probabilities_matrix: Tensor
    ) -> tuple[Tensor, Tensor]:
        if self.training and (self.num_topk_samples > 0):
            probabilities, indices = self.__sample_deterministic_and_random_topk(
                probabilities_matrix
            )
        else:
            probabilities, indices = torch.topk(probabilities_matrix, self.top_k)

        return probabilities, indices

    def __sample_deterministic_and_random_topk(
        self, probabilities_matrix: Tensor
    ) -> tuple[Tensor, Tensor]:
        num_deterministic = self.top_k - self.num_topk_samples
        _, topk_deterministic_indices = probabilities_matrix.topk(
            num_deterministic, dim=-1
        )

        masked_probs = probabilities_matrix + 1e-6
        batch_indices = expand_dims(arange(probabilities_matrix.size(0)), dim=1)
        masked_probs[batch_indices, topk_deterministic_indices] = 0
        topk_random_indices = torch.multinomial(masked_probs, self.num_topk_samples)

        final_topk_indices = concat(
            [topk_deterministic_indices, topk_random_indices], dim=-1
        )

        final_topk_probs = torch.gather(probabilities_matrix, 1, final_topk_indices)

        return final_topk_probs, final_topk_indices

    def _compute_loss(
        self,
        logits: Tensor,
        full_probabilities: Tensor,
        probabilities: Tensor,
        indices: Tensor,
        skip_mask: Optional[Tensor] = None,
    ) -> None:
        input_dim = prod(tensor(probabilities.shape))
        output_dim = self.router_output_dim

        gates_buffer = zeros(input_dim, output_dim).to(device)
        gates = gates_buffer.scatter(
            1,
            indices.view(-1, self.top_k),
            probabilities.view(-1, self.top_k),
        ).to(device)

        logits = logits.reshape(-1, output_dim)
        full_probabilities = logits.reshape(-1, output_dim)
        if skip_mask is not None:
            skip_mask = skip_mask.reshape(-1, output_dim)

        self.auxiliary_losses.update_accumulated_statistics(
            logits, full_probabilities, gates, skip_mask
        )


class SamplerFull(SamplerBase):
    def __init__(
        self,
        cfg: "SamplerConfig | ModelConfig",
        overrides: "SamplerConfig | None" = None,
    ) -> None:
        super().__init__(cfg, overrides)
        self.auxiliary_losses = None

    def _probability_sampling_strategy(
        self, probability_matrix: Tensor
    ) -> tuple[Tensor, Tensor | None]:
        probability_matrix = self.__apply_dynamic_topk_threshold_mask(
            probability_matrix
        )
        return probability_matrix, None

    def __apply_dynamic_topk_threshold_mask(self, probabilities: Tensor) -> Tensor:
        if self.dynamic_topk_threshold == 0.0:
            return probabilities

        dynamic_topk_mask = probabilities < self.dynamic_topk_threshold
        masked_probabilities = torch.where(dynamic_topk_mask, 0.0, probabilities)
        normalized_probabilities = self._normalize_probabilities(masked_probabilities)
        return normalized_probabilities


class SamplerModel(Module):
    def __init__(
        self,
        cfg: "SamplerConfig | ModelConfig",
        overrides: "SamplerConfig | None" = None,
    ) -> None:
        super().__init__()
        self.cfg = cfg
        self.overrides = overrides

        config = getattr(cfg, "sampler_model_config", cfg)
        self.sampler_config: "SamplerConfig" = self._overwrite_config(config, overrides)

        self.router_output_dim = self.sampler_config.router_output_dim
        self.sampler_model = self._init_sampler_model()

    def _init_sampler_model(self) -> SamplerBase:
        if self.sampler_config.top_k == 1:
            return SamplerSparse(self.cfg, self.overrides)
        elif self.sampler_config.top_k == self.router_output_dim:
            return SamplerFull(self.cfg, self.overrides)
        else:
            return SamplerTopk(self.cfg, self.overrides)

    def forward(
        self,
        input_matrix: Tensor,
        skip_mask: Tensor | None = None,
    ) -> tuple[Tensor, Tensor | None, Tensor | None]:
        return self.sampler_model.sample_probabilities_and_indices(
            input_matrix, skip_mask
        )
