from __future__ import annotations

import argparse
from collections.abc import Mapping, Sequence
from importlib import import_module
from pathlib import Path
from types import ModuleType
from typing import Any, cast

from model_runtime.packages.configuration_metadata import (
    configuration_field_metadata,
)
from models.catalog import discover_model_packages

_REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
_MODELS_ROOT = _REPOSITORY_ROOT / "src" / "models"
_GENERATED_FILENAME = "_inspection_metadata.py"

_Field = tuple[str, int, tuple[int, ...]]
_Section = tuple[tuple[str, ...], tuple[_Field, ...]]


def _entry_path(entry: Mapping[str, Any]) -> tuple[str, ...]:
    raw_path = entry.get("sectionPath", [])
    if not isinstance(raw_path, list) or any(
        not isinstance(item, str) for item in raw_path
    ):
        raise ValueError("Legacy metadata sectionPath must be a string list.")
    return tuple(cast(list[str], raw_path))


def _field(key: str, entry: Mapping[str, Any]) -> _Field:
    line = entry.get("line")
    sort_key = entry.get("sortKey")
    if type(line) is not int:
        raise ValueError(f"Legacy metadata field {key!r} has an invalid line.")
    if not isinstance(sort_key, list) or any(
        type(item) is not int for item in sort_key
    ):
        raise ValueError(f"Legacy metadata field {key!r} has an invalid sortKey.")
    return key, line, tuple(cast(list[int], sort_key))


def _sections(metadata: Mapping[str, Mapping[str, Any]]) -> tuple[_Section, ...]:
    sections: list[tuple[tuple[str, ...], list[_Field]]] = []
    for key, entry in metadata.items():
        path = _entry_path(entry)
        if not sections or sections[-1][0] != path:
            sections.append((path, []))
        sections[-1][1].append(_field(key, entry))
    return tuple((path, tuple(fields)) for path, fields in sections)


def _render_sections(name: str, sections: tuple[_Section, ...]) -> list[str]:
    lines = [f"{name}: tuple[RuntimeDefaultsSection, ...] = ("]
    for path, fields in sections:
        lines.append(f"    RuntimeDefaultsSection({path!r}, (")
        lines.extend(f"        {field!r}," for field in fields)
        lines.append("    )),")
    lines.append(")")
    return lines


def _metadata_sources(catalog_key: str) -> tuple[ModuleType, ModuleType]:
    package_module = "models." + catalog_key.replace("/", ".")
    configuration = import_module(package_module + ".config")
    search = import_module(package_module + ".search_space")
    return configuration, search


def _render_package(catalog_key: str) -> str:
    configuration_source, search_source = _metadata_sources(catalog_key)
    configuration = configuration_field_metadata(configuration_source)
    search = configuration_field_metadata(
        search_source,
        include_search_space=True,
    )
    lines = [
        '"""Generated package-owned Runtime Defaults presentation metadata."""',
        "",
        "from model_runtime.packages.configuration_metadata import (",
        "    RuntimeDefaultsSection,",
        ")",
        "",
        "# Generated by tools/generate_model_package_inspection_metadata.py.",
        "# Do not edit by hand; run the generator after intentional metadata changes.",
        "# fmt: off",
        *_render_sections(
            "CONFIGURATION_METADATA_SECTIONS",
            _sections(configuration),
        ),
        "",
        *_render_sections("SEARCH_METADATA_SECTIONS", _sections(search)),
        "# fmt: on",
        "",
        '__all__ = ["CONFIGURATION_METADATA_SECTIONS", "SEARCH_METADATA_SECTIONS"]',
        "",
    ]
    return "\n".join(lines)


def _target_path(catalog_key: str) -> Path:
    model_type, model_name = catalog_key.split("/", 1)
    return _MODELS_ROOT / model_type / model_name / _GENERATED_FILENAME


def _synchronize(*, check: bool) -> tuple[Path, ...]:
    stale: list[Path] = []
    for package in discover_model_packages():
        path = _target_path(package.catalog_key)
        expected = _render_package(package.catalog_key)
        actual = path.read_text(encoding="utf-8") if path.exists() else None
        if actual == expected:
            continue
        stale.append(path)
        if not check:
            path.write_text(expected, encoding="utf-8")
    return tuple(stale)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate package-owned Runtime Defaults metadata declarations."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report stale generated declarations without writing them.",
    )
    args = parser.parse_args(argv)
    stale = _synchronize(check=args.check)
    if args.check and stale:
        for path in stale:
            print(path.relative_to(_REPOSITORY_ROOT))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
