import argparse
import importlib
from enum import Enum
from typing import Any

from torch.nn import Module


def _load_model_parts(model_name: str) -> tuple[type[Enum], Any, type[Module], type]:
    module_path = f"models.{model_name}"
    config_module = importlib.import_module(f"{module_path}.config")
    presets_module = importlib.import_module(f"{module_path}.presets")
    model_module = importlib.import_module(f"{module_path}.model")
    return (
        presets_module.ExperimentOptions,
        presets_module.ExperimentPresets(),
        model_module.Model,
        config_module.DATASET_OPTIONS[0],
    )


def _module_details(module: Module) -> str:
    details = []
    if hasattr(module, "gate_model"):
        details.append(
            "gate="
            + ("enabled" if getattr(module, "gate_model", None) is not None else "off")
        )
    if hasattr(module, "halting_model"):
        details.append(
            "halting="
            + (
                "enabled"
                if getattr(module, "halting_model", None) is not None
                else "off"
            )
        )
    if hasattr(module, "input_dim") and hasattr(module, "output_dim"):
        details.append(f"{module.input_dim}->{module.output_dim}")
    if hasattr(module, "dropout_probability"):
        details.append(f"dropout={module.dropout_probability}")
    if not details:
        return ""
    return " [" + ", ".join(details) + "]"


def _print_module_tree(module: Module) -> None:
    print(f"model: {type(module).__name__}{_module_details(module)}")
    _print_tree_children(module, "")


def _print_tree_children(module: Module, prefix: str) -> None:
    children = list(module.named_children())
    for index, (child_name, child) in enumerate(children):
        branch = "`- " if index == len(children) - 1 else "|- "
        next_prefix = prefix + ("   " if index == len(children) - 1 else "|  ")
        print(
            f"{prefix}{branch}{child_name}: "
            f"{type(child).__name__}{_module_details(child)}"
        )
        _print_tree_children(child, next_prefix)


def _option_description(option: Enum) -> str:
    value = option.value
    if isinstance(value, str):
        return value
    return ""


def _print_model_structure(
    option: Enum,
    config_index: int,
    config_count: int,
    model: Module,
) -> None:
    suffix = f" config {config_index + 1}/{config_count}" if config_count > 1 else ""

    print("=" * 100)
    print(f"{option.name}{suffix}")
    description = _option_description(option)
    if description:
        print(f"description: {description}")
    _print_module_tree(model)


def print_experiment_models(
    experiment_options: type[Enum],
    presets: Any,
    model_type: type[Module],
    dataset: type,
    args: argparse.Namespace,
) -> None:
    options = (
        list(experiment_options)
        if args.all_options
        else [experiment_options.get_option(args.option)]
    )

    for option in options:
        configs = presets.get_config(option, dataset)
        for index, cfg in enumerate(configs):
            model = model_type(cfg)
            _print_model_structure(
                option,
                index,
                len(configs),
                model,
            )


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Print model structures generated by experiment presets."
    )
    parser.add_argument(
        "--model",
        required=True,
        help="Model package to inspect.",
    )
    option_group = parser.add_mutually_exclusive_group(required=True)
    option_group.add_argument(
        "--option",
        help="Experiment option to print.",
    )
    option_group.add_argument(
        "--all-options",
        action="store_true",
        help="Print every experiment option.",
    )
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    experiment_options, presets, model_type, dataset = _load_model_parts(args.model)
    print_experiment_models(experiment_options, presets, model_type, dataset, args)


if __name__ == "__main__":
    main()
