# Shared trainer configuration defaults for all models
GRADIENT_CLIP_VAL: float = 0.0
GRADIENT_CLIP_ALGORITHM: str = "norm"
ACCUMULATE_GRAD_BATCHES: int = 1
PRECISION: str = "32-true"
DETERMINISTIC: bool = False
BENCHMARK: bool = True
MAX_STEPS: int = -1
MAX_TIME: str | None = None
VAL_CHECK_INTERVAL: float = 1.0
LIMIT_TRAIN_BATCHES: float = 1.0
LIMIT_VAL_BATCHES: float = 1.0
OVERFIT_BATCHES: int | float = 0.0
NUM_SANITY_VAL_STEPS: int = 2
LOG_EVERY_N_STEPS: int = 50
ENABLE_PROGRESS_BAR: bool = True
PROFILER: str | None = None
EARLY_STOPPING_PATIENCE: int = 0
EARLY_STOPPING_METRIC: str = "validation_loss"
CHECKPOINT_FLAG: bool = False
